Repository EC-CUBE/ec-cube, pull requests merged in 2018-04, with the labels that each got.

#2999 [管理画面UI実装]商品登録/規格設定ページへの移動時に商品情報が保存できる
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Form/Type/Admin/ProductType.php
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Product/product.twig
  tests/Eccube/Tests/Web/Admin/Product/ProductContorllerTest.php
Labels: Status: fix-me

#3056 セキュリティ強化
  src/Eccube/Controller/EntryController.php
  src/Eccube/Controller/ShoppingController.php
  tests/Eccube/Tests/Web/AbstractShoppingControllerTestCase.php
  tests/Eccube/Tests/Web/CartValidationTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithMultipleNonmemberTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithMultipleTest.php
Labels: bug:High

#2961 expression-languageを追加
  composer.json
  composer.lock
  symfony.lock
Labels: Status: fix-me

#2944 商品一覧画面のクエリ改善
  src/Eccube/Repository/ProductRepository.php
Labels: Status: ready-for-merge

#3078 [master] composer update 2018-04-23
  composer.lock
Labels: enhancement

#3036 メッセージID化への対応
  src/Eccube/Form/Type/Admin/NewsType.php
  src/Eccube/Form/Type/Install/Step1Type.php
  src/Eccube/Form/Type/Install/Step3Type.php
  src/Eccube/Form/Type/Install/Step4Type.php
  src/Eccube/Form/Type/Install/Step5Type.php
  src/Eccube/Form/Type/Master/MailTemplateType.php
  src/Eccube/Form/Type/ZipType.php
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Content/cache.twig
  src/Eccube/Resource/template/admin/Customer/delivery_edit.twig
  src/Eccube/Resource/template/admin/Customer/edit.twig
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Order/order_item_prototype.twig
  src/Eccube/Resource/template/admin/Order/search_product.twig
  src/Eccube/Resource/template/admin/Product/class_name.twig
  src/Eccube/Resource/template/admin/Product/csv_category.twig
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Shipping/csv_shipping.twig
  src/Eccube/Resource/template/admin/Shipping/edit.twig
  src/Eccube/Resource/template/admin/login.twig
  src/Eccube/Resource/template/admin/login_frame.twig
  src/Eccube/Resource/template/install/complete.twig
  src/Eccube/Resource/template/install/frame.twig
  src/Eccube/Resource/template/install/step1.twig
  src/Eccube/Resource/template/install/step2.twig
  src/Eccube/Resource/template/install/step3.twig
  src/Eccube/Resource/template/install/step4.twig
  src/Eccube/Resource/template/install/step5.twig
Labels: Status: fix-me
