Repository EC-CUBE/ec-cube, pull requests merged in 2018-07, with the labels that each got.

#3240 PaymentMethod をコンテナから取得するよう修正
  app/config/eccube/services.yaml
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/DependencyInjection/Compiler/PaymentMethodPass.php
  src/Eccube/Entity/Payment.php
  src/Eccube/Kernel.php
  src/Eccube/Resource/doctrine/import_csv/dtb_payment.csv
  src/Eccube/Service/Payment/Method/Cash.php
  src/Eccube/Service/Payment/Method/CreditCard.php
  src/Eccube/Service/Payment/Method/EccubePaymentCreditCard.php
  src/Eccube/Service/Payment/PaymentDispatcher.php
  src/Eccube/Service/Payment/PaymentMethodInterface.php
  src/Eccube/Service/Payment/PaymentResult.php
  src/Eccube/Service/PaymentService.php
  tests/Eccube/Tests/Service/Payment/PaymentMethodTest.php
Labels: Status: ready-for-merge

#3231 カート追加後のカートボタンが動作しない不具合修正
  html/template/default/assets/js/script.js
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: ready-for-merge

#3218 【ログイン】ログイン失敗時に「次回から自動的にログインする」のチェックボックスが外れる
  src/Eccube/Controller/Mypage/MypageController.php
  src/Eccube/EventListener/SecurityListener.php
Labels: Status: ready-for-merge

#3230 注文完了時にメッセージを表示できるように対応
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Entity/Order.php
  src/Eccube/Resource/template/admin/Mail/order.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Shopping/complete.twig
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
Labels: Status: needs-review

#3239 プラグインの削除時に不正なproxyが生成される問題を修正
  src/Eccube/Service/EntityProxyService.php
  tests/Eccube/Tests/Service/EntityProxyServiceTest.php
Labels: Status: needs-review

#3241 注文番号のカラム名をorder_noに変更し、注文番号の採番の仕方を追加、マイページでURLに受注IDを利用していたのを注文番号に変更
  app/config/eccube/packages/eccube.yaml
  app/config/eccube/packages/purchaseflow.yaml
  codeception/acceptance/_bootstrap.php
  src/Eccube/Controller/Mypage/MypageController.php
  src/Eccube/Entity/Order.php
  src/Eccube/Form/Type/Admin/SearchOrderType.php
  src/Eccube/Form/Type/Admin/SearchShippingType.php
  src/Eccube/Repository/OrderRepository.php
  src/Eccube/Repository/ShippingRepository.php
  src/Eccube/Resource/doctrine/import_csv/dtb_order.csv
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Mail/order.twig
  src/Eccube/Resource/template/admin/Mail/point_notify.twig
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Shipping/index.twig
  src/Eccube/Resource/template/admin/Shipping/order_item_prototype.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mail/point_notify.twig
  src/Eccube/Resource/template/default/Mypage/history.twig
  src/Eccube/Resource/template/default/Mypage/index.twig
  src/Eccube/Service/PurchaseFlow/Processor/OrderCodeProcessor.php
  src/Eccube/Service/PurchaseFlow/Processor/OrderNoProcessor.php
  src/Eccube/ServiceProvider/PurchaseFlowServiceProvider.php
  tests/Eccube/Tests/Fixture/Generator.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/OrderNoProcessorTest.php
  tests/Eccube/Tests/Web/Admin/Order/OrderControllerTest.php
  tests/Eccube/Tests/Web/Mypage/MypageControllerTest.php
Labels: Status: ready-for-merge

#3238 プラグインの有効無効判定が動作していなかった問題を修正
  src/Eccube/DependencyInjection/Compiler/PluginPass.php
  src/Eccube/DependencyInjection/EccubeExtension.php
  src/Eccube/Kernel.php
  tests/Eccube/Tests/Twig/Extension/EccubeBlockExtensionTest.php
  tests/Eccube/Tests/Twig/Extension/FunctionsTest.php
Labels: Status: needs-review

#3256 関係のないプラグインが無効化される問題を修正
  src/Eccube/DependencyInjection/Compiler/PluginPass.php
Labels: bug

#3248 phpunit can run with plugin
  src/Eccube/DependencyInjection/EccubeExtension.php
Labels: Status: ready-for-merge

#3161 CSVアップロード時の文字コード変換処理を修正
  src/Eccube/Controller/Admin/Product/CsvImportController.php
Labels: enhancement

#3273 動作要件変更
  README.md
Labels: document

#3261 購入画面で配送方法の並び順が効いていない修正
  src/Eccube/Repository/DeliveryRepository.php
Labels: Status: fix-me

#3186 【ショップマスター/会員登録・編集】郵便番号検索が効かない
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
  src/Eccube/Resource/template/admin/Shipping/edit.twig
Labels: Status: ready-for-merge

#3279 21【支払方法設定】表示非表示を有効する
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
  src/Eccube/Form/Type/Admin/PaymentRegisterType.php
  src/Eccube/Repository/PaymentRepository.php
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
  tests/Eccube/Tests/Web/Admin/Setting/Shop/PaymentControllerTest.php
Labels: Status: needs-review

#3209 【ご注文手続き】お客様情報にメールアドレスも表示したい
  src/Eccube/Resource/template/default/Shopping/index.twig
Labels: Status: needs-review

#3143 [管理画面UI実装]商品登録/画像の削除ができる
  html/template/admin/assets/css/app.css
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/scss/component/_form.scss
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: css

#3154 テストコードの修正
  src/Eccube/Controller/Admin/Setting/System/SecurityController.php
  src/Eccube/Controller/Admin/Store/TemplateController.php
  tests/Eccube/Tests/Web/Admin/Setting/System/SecurityControllerTest.php
  tests/Eccube/Tests/Web/Admin/Store/TemplateControllerTest.php
Labels: Status: needs-review

#3207 【商品登録（規格設定）】ラベルが翻訳されていない
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Product/product_class.twig
Labels: Status: fix-me

#3205 【商品管理/商品登録】在庫数のエラーメッセージが翻訳されていない
  src/Eccube/Form/Type/Admin/ProductClassEditType.php
  src/Eccube/Form/Type/Admin/ProductClassType.php
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Product/product_class.twig
Labels: Status: fix-me

#3220 【商品マスター】商品複製時の確認ダイアログが、modalになっていない
  codeception/_support/Page/Admin/ProductManagePage.php
  codeception/acceptance/EA03ProductCest.php
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Product/index.twig
Labels: Status: fix-me

#3211 【お問い合せ】お問い合せ返信メールの名前ラベルが翻訳されてない
  src/Eccube/Resource/template/default/Mail/contact_mail.twig
Labels: Status: fix-me

#3299 26【支払方法設定】支払方法名称の入力チェック追加
  src/Eccube/Form/Type/Admin/PaymentRegisterType.php
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
Labels: Status: fix-me

#3291 3【購入確認画面】購入確認画面でポイントを確認できるようにする
  src/Eccube/Resource/template/default/Shopping/confirm.twig
Labels: Status: needs-review

#3301 25【配送方法登録】デフォルトの商品種別修正
  src/Eccube/Controller/Admin/Setting/Shop/DeliveryController.php
Labels: Status: fix-me, Status: needs-review

#3314 151生年月日　今日の日付で登録できないように
  src/Eccube/Form/Type/Admin/CustomerType.php
  src/Eccube/Form/Type/CustomerType.php
  src/Eccube/Form/Type/Front/EntryType.php
  src/Eccube/Resource/locale/messages.en.php
  src/Eccube/Resource/locale/messages.ja.php
Labels: Status: fix-me

#3251 【レイアウト管理】スマホでアクセスしても、スマホ用のレイアウトが適用されていない
  src/Eccube/EventListener/MobileTemplatePathListener.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Resource/template/smartphone/Block/logo.twig
Labels: Status: ready-for-merge

#3326 103商品%の検索修正
  src/Eccube/Repository/ProductRepository.php
Labels: Status: fix-me, Status: needs-review

#3309 206【パスワード再発行】ログイン状態で/forgotアクセスできないようにする
  src/Eccube/Controller/ForgotController.php
Labels: Status: needs-review

#3319 52メールのヘッダー/フッターは入力必須ではなくする
  src/Eccube/Form/Type/Admin/MailType.php
Labels: Status: fix-me

#3201 【商品管理/商品マスター】個別のチェックボックスを外しても、一括操作のチェックボックスがOFFにならない
  codeception/_support/Page/Admin/ProductManagePage.php
  src/Eccube/Resource/template/admin/Product/index.twig
Labels: Status: fix-me

#3305 MySQLだとDoctrineのDateTimeTzが使えなくて+9h表示されちゃうので
  src/Eccube/Kernel.php
Labels: Status: needs-review

#3404 Update Readme
  README.md
Labels: document

#3307 規格、数量未入力でカート追加ボタン押下した時にエラーが出るようにする対応、カートへ追加した時にダイアログを表示する対応
  codeception/_support/Page/Front/ProductDetailPage.php
  codeception/acceptance/EF02ProductCest.php
  codeception/acceptance/EF03OrderCest.php
  html/template/default/assets/css/component/3.1.inputText.min.css
  html/template/default/assets/css/component/3.2.inputMisc.min.css
  html/template/default/assets/css/project/14.1.product.min.css
  html/template/default/assets/css/style.min.css
  html/template/default/assets/scss/project/14.1.product.scss
  src/Eccube/Controller/Block/CartController.php
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/default/Block/cart.twig
  src/Eccube/Resource/template/default/Block/header.twig
  src/Eccube/Resource/template/default/Block/nav_sp.twig
  src/Eccube/Resource/template/default/Product/detail.twig
Labels: Status: needs-review

#3421 Fix debug bar error
  src/Eccube/DataCollector/EccubeDataCollector.php
Labels: Status: needs-review
