Repository EC-CUBE/ec-cube, pull requests merged in 2018-06, with the labels that each got.

#3147 [master] composer update 2018-06-04
  composer.lock
Labels: enhancement

#3171 販売種別が異なる場合にカートへの追加が失敗する不具合を修正
  src/Eccube/Controller/ProductController.php
Labels: bug:Middle

#3173 配送先情報がすでに設定されている状態でカートに変更がなければ配送先を復元する
  codeception/acceptance/EF03OrderCest.php
Labels: Status: fix-me

#3197 【ブロック管理】ブロックのデータ未入力でもエラー文言が表示されない
  src/Eccube/Form/Type/Admin/BlockType.php
  src/Eccube/Resource/template/admin/Content/block_edit.twig
Labels: Status: ready-for-merge

#3203 不要な結合条件を削除
  src/Eccube/Repository/PageLayoutRepository.php
Labels: Status: ready-for-merge, enhancement

#3179 新規登録確認画面に追加フィールド用の記述を追加
  src/Eccube/Resource/template/default/Entry/confirm.twig
Labels: Status: ready-for-merge, bug:Low, template

#3202 【商品一覧】ページャーの文言漏れ
  src/Eccube/Resource/locale/messages.ja.php
Labels: Status: ready-for-merge

#3176 名前とカナの入力チェックエラーメッセージを修正
  src/Eccube/Form/Type/KanaType.php
  src/Eccube/Form/Type/NameType.php
  src/Eccube/Resource/locale/message.ja.yml
Labels: bug:Low

#3227 スタイルシートの最新版を反映
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/css/bootstrap.min.css
  html/template/default/assets/css/component/3.1.inputText.min.css
  html/template/default/assets/css/component/3.2.inputMisc.min.css
  html/template/default/assets/css/project/11.2.header.min.css
  html/template/default/assets/css/style.min.css
  html/template/default/assets/js/script.js
  html/template/default/assets/scss/project/11.2.header.scss
  src/Eccube/Resource/template/default/Block/category.twig
  src/Eccube/Resource/template/default/Block/nav_sp.twig
Labels: Status: ready-for-merge

#2947 メールテンプレート削除時の不具合修正
  src/Eccube/Entity/MailHistory.php
  src/Eccube/Resource/template/admin/Order/mail.twig
Labels: Status: needs-review, bug:Low
