Repository EC-CUBE/ec-cube, pull requests merged in 2018-02, with the labels that each got.

#2819 管理画面でのログ表示を動作するように修正
  src/Eccube/Controller/Admin/Setting/System/LogController.php
  src/Eccube/Form/Type/Admin/LogType.php
  src/Eccube/Form/Type/Admin/MemberType.php
  src/Eccube/Resource/locale/messages.ja.php
Labels: Status: fix-me

#2854 heroku-postgresqlのversion指定
  app.json
Labels: bug:Low

#2832 商品検索画面のカテゴリのソート順を修正
  src/Eccube/Form/Type/Admin/SearchProductType.php
Labels: bug:Low

#2858 会員登録画面初期表示時に出るエラーメッセージを抑制
  src/Eccube/Controller/Admin/Customer/CustomerEditController.php
Labels: bug:Low

#2866 styleguide商品マスタのメッセージ切り出し
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Product/index.twig
Labels: experimental

#2861 コマンドラインインストーラ
  src/Eccube/Command/InstallerCommand.php
Labels: experimental
