Repository EC-CUBE/ec-cube, pull requests merged in 2018-10, with the labels that each got.

#3892 scheme update時のエラー対応
  codeception/acceptance/EA01TopCest.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Entity/Cart.php
  src/Eccube/Entity/Delivery.php
  src/Eccube/Entity/OrderPdf.php
Labels: bug

#3934 Fix html5 validate conflict with ladda spinner
  html/template/admin/assets/js/function.js
Labels: bug

#3932 Search text no matter if is in lower or upper case
  html/template/admin/assets/js/function.js
  src/Eccube/Resource/template/admin/Content/block.twig
  src/Eccube/Resource/template/admin/Content/layout.twig
  src/Eccube/Resource/template/admin/Content/page.twig
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: enhancement

#3908 日本語メッセージベタ書きを修正
  src/Eccube/Controller/ProductController.php
Labels: bug

#3895 管理画面のシステムメンバー登録における不要なバリデートの削除
  src/Eccube/Form/Type/Admin/MemberType.php
Labels: Status: ready-for-merge, bug:Low

#3930 DoctrineMigrationBundle を動くよう修正
  app/DoctrineMigrations/Version20181017090225.php
  app/config/eccube/bundles.php
  app/config/eccube/packages/doctrine_migrations.yaml
Labels: enhancement

#3937 キーワード置換できていなかったのを修正
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug:Low

#3941 [master] composer update 2018-10-22
  composer.lock
Labels: enhancement

#3909 ツールチップのおかしな日本語を修正
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug:Low
