Repository EC-CUBE/ec-cube, pull requests merged in 2018-08, with the labels that each got.

#3355 【ファイル管理】ドットファイルが表示されない
  codeception/_support/Page/Admin/FileManagePage.php
  codeception/acceptance/EA06ContentsManagementCest.php
  src/Eccube/Controller/Admin/Content/FileController.php
Labels: Status: fix-me, Status: needs-review

#3384 【 商品登録】カテゴリの表示崩れ（Firefox）
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: Status: needs-review

#3457 Fix license identifiers
  composer.json
Labels: bug:Low

#3376 #50 【権限設定】拒否URLに部分一致のページはメニューに表示されるがアクセスできない
  src/Eccube/Twig/Extension/EccubeExtension.php
Labels: Status: needs-review

#3403 サンプルとして入っていたスマホ用のtwigファイルを削除
  src/Eccube/Resource/template/smartphone/.gitkeep
  src/Eccube/Resource/template/smartphone/Block/logo.twig
  src/Eccube/Resource/template/smartphone/index.twig
Labels: Status: needs-review

#3475 【受注一覧】出荷完了メール送信済みの場合に、アイコンが表示されない
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Order/index.twig
Labels: bug

#3506 コマンドをlazy loadするように修正
  src/Eccube/Command/CsvLoaderCommand.php
  src/Eccube/Command/GenerateDummyDataCommand.php
  src/Eccube/Command/GenerateProxyCommand.php
  src/Eccube/Command/LoadDataFixturesEccubeCommand.php
  src/Eccube/Command/PluginDisableCommand.php
  src/Eccube/Command/PluginEnableCommand.php
  src/Eccube/Command/PluginInstallCommand.php
  src/Eccube/Command/PluginUninstallCommand.php
Labels: Status: needs-review

#3303 54【マスターデータ管理】IDを「0」を削除可能にする
  src/Eccube/Controller/Admin/Setting/System/MasterdataController.php
  tests/Eccube/Tests/Web/Admin/Setting/System/MasterdataControllerTest.php
Labels: Status: needs-review

#3442 #31 【支払方法登録】アップロードした画像の周辺をクリックすると、画像が消えて未アップロード状態になる
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
Labels: Status: fix-me

#3518 管理画面TOPお知らせの参照URL変更
  app/config/eccube/packages/eccube.yaml
Labels: enhancement

#3513 プロパティのアクセス修飾子をprivateからprotectedに変更した #3512
  src/Eccube/Controller/Admin/Product/CsvImportController.php
Labels: enhancement

#3398 #278 【ご注文手続き】ご利用ポイントに不正な値でバリデーションエラー発生後に、そのまま次画面に遷移できる
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Service/PurchaseFlow/Processor/PointProcessor.php
Labels: bug

#3529 fix ページ管理 右上のページ検索は画面内検索のためformタグを削除
  src/Eccube/Resource/template/admin/Content/page.twig
Labels: bug

#3318 12商品詳細から来た時は商品詳細画面へ戻す
  src/Eccube/Controller/Admin/Product/ProductClassController.php
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Product/product_class.twig
Labels: Status: needs-review, question

#3509 ShoppingControllerでエラー発生時のログ出力不具合修正
  src/Eccube/Controller/ShoppingController.php
Labels: bug

#3523 fix 出荷管理画面 出荷メール・出荷完了処理にてメッセージが２重で表示される問題を修正
  src/Eccube/Resource/template/admin/Order/confirmationModal_js.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
Labels: bug

#3434 #146 【パスワード変更】パスワードリセットのタイミングをパスワード再発行のタイミングとする
  codeception/acceptance/EF06OtherCest.php
  src/Eccube/Controller/ForgotController.php
  src/Eccube/Form/Type/Front/PassowrdResetType.php
  src/Eccube/Repository/CustomerRepository.php
  src/Eccube/Resource/doctrine/import_csv/dtb_page.csv
  src/Eccube/Resource/locale/messages.en.php
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/default/Forgot/reset.twig
  src/Eccube/Resource/template/default/Mypage/login.twig
  src/Eccube/Service/MailService.php
  tests/Eccube/Tests/Web/ForgotControllerTest.php
Labels: Status: needs-review

#3539 商品一覧画面で「カートに入れる」ボタンを一番下に揃える対応
  codeception/acceptance/EF02ProductCest.php
  html/template/default/assets/css/project/13.2.shelf.min.css
  html/template/default/assets/css/style.min.css
  html/template/default/assets/scss/project/13.2.shelf.scss
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: fix-me

#3473 【ショップマスター】「商品ごとの送料設定」が機能していない
  src/Eccube/Form/Type/Shopping/ShippingType.php
  src/Eccube/Service/PurchaseFlow/Processor/DeliveryFeePreprocessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/DeliveryFeeProcessorTest.php
Labels: Status: fix-me

#3431 【購入画面】支払い方法の手数料が反映されない
  app/config/eccube/packages/purchaseflow.yaml
  app/config/eccube/services_test.yaml
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Service/PurchaseFlow/Processor/PaymentChargePreprocessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/PaymentChargeProcessorTest.php
Labels: Status: needs-review

#3520 【ページ管理】「モバイル」に表記を統一
  src/Eccube/Entity/Master/DeviceType.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Form/Type/Admin/MainEditType.php
  src/Eccube/Resource/doctrine/import_csv/dtb_template.csv
  src/Eccube/Resource/doctrine/import_csv/mtb_device_type.csv
  src/Eccube/Service/OrderHelper.php
  src/Eccube/Service/ShoppingService.php
  tests/Eccube/Tests/Web/Admin/Content/BlockControllerTest.php
Labels: Status: fix-me, Status: needs-review

#3530 プラグインから独自にログファイルを出力できるようにログ関数を作成、monologの設定を修正
  app/config/eccube/packages/prod/monolog.yml
  app/config/eccube/services.yaml
  src/Eccube/Resource/functions/log.php
Labels: Status: needs-review, document

#3574 会員登録時の利用規約チェックボックス対応
  codeception/acceptance/EF04CustomerCest.php
  html/template/default/assets/css/component/3.1.inputText.min.css
  html/template/default/assets/css/component/3.2.inputMisc.min.css
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.min.css
  html/template/default/assets/scss/component/3.1.inputText.scss
  html/template/default/assets/scss/component/3.2.inputMisc.scss
  src/Eccube/Form/Type/Front/EntryType.php
  src/Eccube/Resource/template/default/Entry/confirm.twig
  src/Eccube/Resource/template/default/Entry/index.twig
  src/Eccube/Resource/template/default/Form/form_div_layout.twig
  tests/Eccube/Tests/Web/EntryControllerTest.php
Labels: Status: needs-review

#3408 #268 【ショッピングカート】複数カートになった状態で選択したカートのご注文内容確認へ遷移しない
  src/Eccube/Controller/CartController.php
  src/Eccube/Resource/template/default/Cart/index.twig
  src/Eccube/Service/CartService.php
  tests/Eccube/Tests/Web/AbstractShoppingControllerTestCase.php
  tests/Eccube/Tests/Web/CartValidationTest.php
Labels: Status: needs-review

#3490 [MOCKUP] インストール確認画面(依存あり)
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
  src/Eccube/Resource/template/admin/Store/plugin_confirm_panel.twig
Labels: Status: fix-me

#3491 [MOCKUP] アップデート確認画面
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
Labels: Status: fix-me

#3592 商品サムネイルのサイズ調整　スライダーの調整
  codeception/_support/Page/Front/ProductDetailPage.php
  codeception/acceptance/EF02ProductCest.php
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/js/script.js
  html/template/default/assets/scss/project/_12.1.slider.scss
  src/Eccube/Resource/template/default/Product/detail.twig
Labels: Status: needs-review

#3558 issue #199 商品サムネイルのサイズ調整　スライダーの調整
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/css/bootstrap.min.css
  html/template/default/assets/css/project/12.1.slider.min.css
  html/template/default/assets/css/style.min.css
  html/template/default/assets/js/script.js
  html/template/default/assets/scss/project/12.1.slider.scss
  src/Eccube/Resource/template/default/Product/detail.twig
Labels: Status: needs-review

#3613 fix ブロック管理に存在しているギャラリー(gallery)のスペルを正しいものに修正
  src/Eccube/Resource/doctrine/import_csv/dtb_block.csv
  src/Eccube/Resource/template/default/Block/gallery.twig
Labels: bug

#3624 権限管理：メッセージIDが出力されていたので修正
  src/Eccube/Form/Type/Admin/AuthorityRoleType.php
Labels: bug:Low

#3581 feat 管理画面（受注一覧・商品一覧）、フロント画面（商品一覧）のN+1問題対応
  src/Eccube/DataCollector/EccubeDataCollector.php
  src/Eccube/Repository/OrderRepository.php
  src/Eccube/Repository/ProductRepository.php
Labels: Status: needs-review, enhancement

#3614 fix SERVER_SOFTWAREの判定を修正
  src/Eccube/Controller/Install/InstallController.php
Labels: bug

#3621 .htaccessの除外する拡張子にmapが含まれていなかったため、無視するように追加
  .htaccess
Labels: Status: fix-me

#3620 fix バリデーションエラー時に支払い方法画像が消えてしまうのを修正
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
Labels: bug

#3646 mtb_order_status_colorの実装
  src/Eccube/Entity/Master/OrderStatusColor.php
  src/Eccube/Entity/Order.php
  src/Eccube/Repository/Master/OrderStatusColorRepository.php
  src/Eccube/Resource/doctrine/import_csv/definition.yml
  src/Eccube/Resource/doctrine/import_csv/mtb_order_status_color.csv
  src/Eccube/Resource/template/admin/Order/index.twig
Labels: document

#3639 UpdateDate, CreateDateの更新処理をSaveEventSubscriberに統一
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Repository/CustomerFavoriteProductRepository.php
  src/Eccube/Service/PluginService.php
Labels: enhancement

#3533 fix ページ管理 ファイルの重複チェックを追加
  src/Eccube/Form/Type/Admin/MainEditType.php
Labels: bug

#3651 ダミーデータ生成時の受注番号を変更
  tests/Eccube/Tests/Fixture/Generator.php
Labels: enhancement

#3553 サブリクエストの場合でもTwigにグローバル変数を登録
  src/Eccube/EventListener/TwigInitializeListener.php
Labels: bug:High

#3644 【PC】【受注管理】受注登録画面にてお届け先時間を指定して注文した受注に、お届け先時間が反映されていない
  src/Eccube/Resource/template/admin/Order/edit.twig
Labels: Status: fix-me

#3664 Fix layout of the shipping multiple page
  codeception/_support/Page/Front/MultipleShippingPage.php
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/project/_15.2.order.scss
  src/Eccube/Resource/template/default/Shopping/shipping_multiple.twig
Labels: Status: fix-me

#3662 メッセージが日本語で表示できていなかったところを修正
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/Cart/index.twig
  src/Eccube/Resource/template/default/Contact/index.twig
  src/Eccube/Resource/template/default/Product/detail.twig
Labels: bug

#3650 ShoppingController/ShoppingMultipleControllerの実装見直し
  src/Eccube/Controller/AbstractShoppingController.php
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/CartController.php
  src/Eccube/Controller/NonMemberShoppingController.php
  src/Eccube/Controller/ShippingMultipleController.php
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/DataCollector/EccubeDataCollector.php
  src/Eccube/Entity/Order.php
  src/Eccube/Event/EccubeEvents.php
  src/Eccube/EventListener/SecurityListener.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Form/Type/Shopping/OrderType.php
  src/Eccube/Request/Context.php
  src/Eccube/Resource/template/default/Shopping/confirm.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
  src/Eccube/Resource/template/default/Shopping/shipping_edit.twig
  src/Eccube/Resource/template/default/Shopping/shopping_error.twig
  src/Eccube/Service/CartService.php
  src/Eccube/Service/Composer/ComposerApiService.php
  src/Eccube/Service/MailService.php
  src/Eccube/Service/OrderHelper.php
  src/Eccube/Service/OrderService.php
  src/Eccube/Service/Payment/Method/Cash.php
  src/Eccube/Service/PluginApiService.php
  src/Eccube/Service/PluginService.php
  src/Eccube/Service/PurchaseFlow/Processor/OrderUpdateProcessor.php
  src/Eccube/Service/ShoppingService.php
  src/Eccube/Twig/Extension/EccubeExtension.php
  tests/Eccube/Tests/Service/OrderHelperTest.php
  tests/Eccube/Tests/Service/OrderServiceTest.php
  tests/Eccube/Tests/Service/ShoppingServiceTest.php
  tests/Eccube/Tests/Web/AbstractShoppingControllerTestCase.php
  tests/Eccube/Tests/Web/CartValidationTest.php
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithMultipleNonmemberTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithMultipleTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithNonmemberTest.php
Labels: Status: needs-review, document

#3631 管理画面から送信する受注メール送信履歴の登録方法修正（3系から）
  src/Eccube/Controller/Admin/Order/MailController.php
Labels: Status: needs-review, bug

#3590 New styleguide for content/new page
  codeception/_support/Page/Admin/AbstractAdminPage.php
  codeception/_support/Page/Admin/NewsEditPage.php
  codeception/_support/Page/Admin/NewsManagePage.php
  codeception/acceptance/EA06ContentsManagementCest.php
  codeception/acceptance/_bootstrap.php
  src/Eccube/Controller/Admin/Content/NewsController.php
  src/Eccube/Entity/News.php
  src/Eccube/Form/Type/Admin/NewsType.php
  src/Eccube/Repository/NewsRepository.php
  src/Eccube/Resource/doctrine/import_csv/dtb_news.csv
  src/Eccube/Resource/template/admin/Content/news.twig
  src/Eccube/Resource/template/admin/Content/news_edit.twig
  tests/Eccube/Tests/Repository/NewsRepositoryTest.php
  tests/Eccube/Tests/Web/Admin/Content/NewsControllerTest.php
Labels: Status: needs-review

#3678 php-cs-fixerを適用
  codeception/acceptance/_bootstrap.php
  src/Eccube/Controller/Admin/Content/BlockController.php
  src/Eccube/Controller/Admin/Customer/CustomerDeliveryEditController.php
  src/Eccube/Controller/Mypage/DeliveryController.php
  tests/Eccube/Tests/Repository/CustomerRepositoryGetQueryBuilderBySearchDataTest.php
  tests/Eccube/Tests/Transaction/TransactionListenerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/DeliveryControllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/MailControllerTest.php
Labels: Status: needs-review

#3656 管理画面のメニュー幅をブラウザサイズに合わせて調整
  html/template/admin/assets/css/app.css
  html/template/admin/assets/css/maps/app.css.map
  html/template/admin/assets/scss/component/_contentsArea.scss
  html/template/admin/assets/scss/component/_headerBar.scss
  html/template/admin/assets/scss/component/_mainNavArea.scss
  html/template/admin/assets/scss/mixin/_media.scss
  html/template/default/assets/css/maps/style.css.map
Labels: Status: fix-me

#3676 メールプレビューは、メール本文を確認しやすいようにモーダルのサイズを大きくした。
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
  src/Eccube/Resource/template/admin/Setting/Shop/mail.twig
Labels: enhancement

#3680 新着情報管理で、管理画面とフロントで並び順が異なる不具合と、表示が5件より多い場合の表示制御の不具合を修正
  codeception/acceptance/_bootstrap.php
  src/Eccube/Repository/NewsRepository.php
  src/Eccube/Resource/template/admin/Content/news.twig
  src/Eccube/Resource/template/admin/Content/news_edit.twig
  src/Eccube/Resource/template/default/Block/news.twig
Labels: bug

#3681 レイアウト管理実装で不要となった変数/処理を削除・BlockPositionの機能をPageからLayoutに移行
  src/Eccube/Controller/Admin/Content/LayoutController.php
  src/Eccube/Controller/Admin/Content/PageController.php
  src/Eccube/Controller/UserDataController.php
  src/Eccube/Entity/BlockPosition.php
  src/Eccube/Entity/Layout.php
  src/Eccube/Entity/Page.php
  src/Eccube/Entity/PageLayout.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Form/Type/Admin/MainEditType.php
  src/Eccube/Repository/PageRepository.php
  src/Eccube/Resource/doctrine/import_csv/dtb_block_position.csv
  src/Eccube/Resource/doctrine/import_csv/dtb_page.csv
  src/Eccube/Resource/template/admin/Content/layout.twig
  src/Eccube/Resource/template/default/default_frame.twig
  tests/Eccube/Tests/Fixture/Generator.php
  tests/Eccube/Tests/Repository/LayoutRepositoryTest.php
  tests/Eccube/Tests/Repository/PageRepositoryTest.php
  tests/Eccube/Tests/Web/Admin/Content/LayoutControllerTest.php
  tests/Eccube/Tests/Web/Admin/Content/PageControllerTest.php
  tests/Eccube/Tests/Web/UserDataControllerTest.php
Labels: Status: needs-review

#3705 使用していない変数 ProductCategory::sort_no を削除
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Entity/ProductCategory.php
  src/Eccube/Resource/doctrine/import_csv/dtb_product_category.csv
  tests/Eccube/Tests/Fixture/Generator.php
Labels: Status: needs-review

#3589 datetimepickerをbootstrap4に合わせるためライブラリを変更、税率設定の適用日時を変更
  codeception/_support/Page/Admin/TaxManagePage.php
  codeception/acceptance/EA07BasicinfoCest.php
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/css/bootstrap-datetimepicker.css
  html/template/admin/assets/css/bootstrap-datetimepicker.min.css
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/maps/app.min.css.map
  html/template/admin/assets/css/maps/bootstrap-datetimepicker.min.css.map
  html/template/admin/assets/css/maps/bootstrap.min.css.map
  html/template/admin/assets/css/tempusdominus-bootstrap-4.css
  html/template/admin/assets/css/tempusdominus-bootstrap-4.min.css
  html/template/admin/assets/js/vendor/bootstrap-datetimepicker.js
  html/template/admin/assets/js/vendor/bootstrap-datetimepicker.min.js
  html/template/admin/assets/js/vendor/moment-ja.js
  html/template/admin/assets/js/vendor/moment-with-locales.js
  html/template/admin/assets/js/vendor/moment-with-locales.min.js
  html/template/admin/assets/js/vendor/moment.js
  html/template/admin/assets/js/vendor/moment.min.js
  html/template/admin/assets/js/vendor/tempusdominus-bootstrap-4.js
  html/template/admin/assets/js/vendor/tempusdominus-bootstrap-4.min.js
  html/template/default/assets/css/maps/style.min.css.map
  html/template/default/assets/css/project/17.1.address.min.css
  html/template/default/assets/css/style.min.css
  src/Eccube/Form/Type/Admin/OrderPdfType.php
  src/Eccube/Form/Type/Admin/SearchCustomerType.php
  src/Eccube/Form/Type/Admin/SearchOrderType.php
  src/Eccube/Form/Type/Admin/SearchProductType.php
  src/Eccube/Form/Type/Admin/TaxRuleType.php
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Order/order_pdf.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
  src/Eccube/Resource/template/admin/Setting/Shop/tax_rule.twig
  tests/Eccube/Tests/Web/Admin/Setting/Shop/TaxRuleControllerTest.php
Labels: Status: fix-me, Status: needs-review

#3713 SPでカートボタンが押せない問題の対応+カート関連の細かい修正
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/js/script.js
  html/template/default/assets/scss/component/_7.3.cart.scss
  html/template/default/assets/scss/project/_11.2.header.scss
Labels: bug

#3607 商品登録画面で商品画像のサムネイル画像位置と大きさを変更
  html/template/admin/assets/css/app.css
  html/template/admin/assets/css/maps/app.css.map
  html/template/admin/assets/scss/component/_form.scss
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: Status: needs-review
