Repository EC-CUBE/ec-cube, pull requests merged in 2018-05, with the labels that each got.

#3090 [master] composer update 2018-04-30
  composer.lock
Labels: enhancement

#3092 [master] composer update 2018-05-07
  composer.lock
Labels: enhancement

#3131 テンプレート切り替えが動作しない問題を修正
  src/Eccube/Controller/Admin/Order/MailController.php
  src/Eccube/Service/MailService.php
Labels: bug:Middle

#3113 symfony移植：管理画面＞プラグインの画面が表示できる
  app/config/eccube/packages/eccube.yaml
  app/config/eccube/packages/eccube_nav.yaml
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Resource/locale/messages.ja.php
  src/Eccube/Resource/template/admin/Store/authentication_setting.twig
  src/Eccube/Resource/template/admin/Store/plugin.twig
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
  src/Eccube/Resource/template/admin/Store/plugin_confirm_panel.twig
  src/Eccube/Resource/template/admin/Store/plugin_handler.twig
  src/Eccube/Resource/template/admin/Store/plugin_install.twig
  src/Eccube/Resource/template/admin/Store/plugin_search.twig
  src/Eccube/Resource/template/admin/Store/plugin_search_panel.twig
  src/Eccube/Resource/template/admin/Store/plugin_table.twig
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
  src/Eccube/Resource/template/admin/Store/unregisterd_plugin_table.twig
  src/Eccube/Service/Composer/ComposerProcessService.php
Labels: Status: fix-me
