Repository EC-CUBE/ec-cube, pull requests merged in 2018-12, with the labels that each got.

#4041 商品規格のポイント付与率が取れてないので修正
  src/Eccube/Service/PurchaseFlow/Processor/AddPointProcessor.php
Labels: Status: ready-for-merge, bug:Middle

#4037 jaとenのメッセージファイルを同期
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/locale/validators.en.yaml
  src/Eccube/Resource/locale/validators.ja.yaml
Labels: Status: ready-for-merge, bug:Low

#4020 マイページでポイント有効時のみ保有ポイントが表示されるよう修正
  src/Eccube/Resource/template/default/Mypage/navi.twig
Labels: Status: ready-for-merge, affected:template, bug:Low
