Repository EC-CUBE/ec-cube, pull requests merged in 2018-11, with the labels that each got.

#3960 プラグインのマイグレーション機能
  app/Plugin/MigrationSample/DoctrineMigrations/Version20181101012712.php
  app/Plugin/MigrationSample/Entity/BaseInfo3Trait.php
  app/Plugin/MigrationSample/PluginManager.php
  app/Plugin/MigrationSample/composer.json
  app/config/eccube/services.yaml
  src/Eccube/Plugin/AbstractPluginManager.php
Labels: affected:plugin, enhancement

#3946 フリガナのプレースホルダーが両方メイになっているのを修正
  src/Eccube/Resource/template/default/Mypage/change.twig
  src/Eccube/Resource/template/default/Mypage/delivery_edit.twig
  src/Eccube/Resource/template/default/Shopping/nonmember.twig
  src/Eccube/Resource/template/default/Shopping/shipping_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_multiple_edit.twig
Labels: bug:Low

#3921 Fix error when payment limit and point use
  src/Eccube/Form/Type/Shopping/OrderType.php
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
Labels: bug

#3970 Fix typo in services.yaml
  app/config/eccube/services.yaml
Labels: bug:Low

#3974 商品CSV登録でmessage_idが表示される不具合を修正
  src/Eccube/Controller/Admin/Product/CsvImportController.php
Labels: bug:Low

#3940 Fix shopping overlay in firefox + other
  app/DoctrineMigrations/Version20181109101907.php
  src/Eccube/Resource/doctrine/import_csv/dtb_page.csv
  src/Eccube/Resource/template/default/Shopping/index.twig
Labels: affected:template, bug:Low

#3893 余計な。を削除
  src/Eccube/Resource/template/admin/Store/plugin_handler.twig
Labels: bug:Low

#3983 在庫が無い商品規格のエラーIDを日本語と英語で同一となるよう修正
  src/Eccube/Entity/Product.php
  src/Eccube/Resource/locale/messages.en.php
Labels: bug:Low

#3986 郵便番号検索のリンク先URLをhttpsに変更
  src/Eccube/Resource/template/default/Contact/index.twig
  src/Eccube/Resource/template/default/Entry/index.twig
  src/Eccube/Resource/template/default/Mypage/change.twig
  src/Eccube/Resource/template/default/Mypage/delivery_edit.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
  src/Eccube/Resource/template/default/Shopping/nonmember.twig
  src/Eccube/Resource/template/default/Shopping/shipping_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_multiple_edit.twig
Labels: bug:Low

#3989 マスタデータ管理のヘッダー定数を修正
  src/Eccube/Resource/template/admin/Setting/System/masterdata.twig
Labels: bug:Low

#3993 インストール時にディレクトリに加えてファイルの書き込み権限もチェックする処理を追加
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/install/step2.twig
  tests/Eccube/Tests/Web/Install/InstallControllerTest.php
Labels: enhancement

#3991 管理画面へのアクセス制御(3.0)
  .htaccess.sample
  html/.htaccess
  src/Eccube/Application.php
  src/Eccube/Controller/Admin/AdminController.php
  src/Eccube/Controller/Admin/Setting/System/SecurityController.php
  src/Eccube/Form/Type/Install/Step3Type.php
  src/Eccube/Resource/locale/message.ja.yml
  src/Eccube/Resource/template/admin/error.twig
  src/Eccube/Resource/template/admin/index.twig
  tests/Eccube/Tests/Form/Type/Install/Step3TypeTest.php
Labels: enhancement

#3994 管理画面のアクセス制限強化
  .htaccess
  src/Eccube/Controller/Admin/AdminController.php
  src/Eccube/Controller/Admin/Setting/System/SecurityController.php
  src/Eccube/Form/Type/Install/Step3Type.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/locale/validators.ja.yaml
  src/Eccube/Resource/template/admin/index.twig
  tests/Eccube/Tests/Form/Type/Install/Step3TypeTest.php
Labels: enhancement

#3978 在庫がマイナスにならないよう 0 チェックを追加
  src/Eccube/Service/PurchaseFlow/Processor/StockReduceProcessor.php
Labels: bug:Middle

#4001 CartItemAllocator のカスタマイズを適用するとシステムエラーが発生する対策
  src/Eccube/Controller/CartController.php
Labels: bug:Middle

#3962 services.yaml を基底とするようにロード順序を修正
  app/config/eccube/packages/mobile_detect.yaml
  app/config/eccube/services_dev.yaml
  src/Eccube/Kernel.php
Labels: bug, bug:Middle

#3999 Order::setCompleteMailMessageで、改行が反映されない問題の修正
  src/Eccube/Resource/template/default/Mail/order.html.twig
Labels: Status: ready-for-merge, bug:Low

#3929 DBのパスワードに記号を利用できない不具合の修正 #3928
  .travis.yml
  app/config/eccube/packages/doctrine.yaml
  src/Eccube/Command/InstallerCommand.php
  src/Eccube/Controller/Install/InstallController.php
Labels: Status: ready-for-merge, bug:Low

#3998 メンテナンス機能を追加
  index.php
  maintenance.php
  src/Eccube/Command/InstallerCommand.php
  src/Eccube/Controller/Install/InstallController.php
Labels: Status: ready-for-merge, enhancement

#4002 ライセンス表記の修正
  composer.json
Labels: Status: ready-for-merge

#3955 バリデーションメッセージをvalidators.ja.yamlに移動
  src/Eccube/Entity/Customer.php
  src/Eccube/Entity/Member.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/locale/validators.ja.yaml
Labels: Status: ready-for-merge, bug:Low

#3851 feat テンプレートのアップロード対策に、アップロード最大ファイルサイズを5Mに変更
  .htaccess
Labels: Status: ready-for-merge, enhancement

#4009 DATABASE_URLのデフォルト値の修正
  .env.dist
Labels: bug:Low

#4003 ライセンス表記の修正
  composer.json
Labels: Status: ready-for-merge

#4007 .htaccessで書かれているBASIC認証のかけ方にApacheバージョンを明記
  html/.htaccess
Labels: enhancement

#4006 .htaccessで書かれているBASIC認証のかけ方にApacheバージョンを明記
  html/.htaccess
Labels: enhancement

#3997 インストール済プラグインをcomposer requireするコマンドを追加
  composer.lock
  src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: document, enhancement

#4012 オーナーズストア周りの表示修正
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Store/plugin_detail_info.twig
  src/Eccube/Resource/template/admin/Store/plugin_detail_modal.twig
  src/Eccube/Resource/template/admin/Store/plugin_search_panel.twig
Labels: enhancement

#4011 .maintenance ファイルを除外
  .gitignore
  .htaccess
  web.config
Labels: Status: ready-for-merge, enhancement

#4000 メンテナンス管理から.maintenanceファイルが作成/削除できる
  app/config/eccube/packages/eccube.yaml
  app/config/eccube/packages/eccube_nav.yaml
  codeception.sh
  index.php
  src/Eccube/Controller/Admin/Content/MaintenanceController.php
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/maintenance.twig
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
  src/Eccube/Service/PluginService.php
  src/Eccube/Service/SystemService.php
Labels: Status: fix-me, Status: ready-for-merge, enhancement

#4016 リダイレクト処理の修正(3.0)
  src/Eccube/Application.php
  src/Eccube/Common/Constant.php
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationFailureHandler.php
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationSuccessHandler.php
Labels: enhancement

#4022 メンテナンス管理からはモードに関わらずメンテナンスを解除する
  src/Eccube/Controller/Admin/Content/MaintenanceController.php
Labels: enhancement

#4023 メンテナンス管理の不具合修正
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Service/SystemService.php
Labels: bug:Middle
