Repository EC-CUBE/ec-cube, pull requests merged in 2018-09, with the labels that each got.

#3735 プラグイン有効/無効時のキャッシュ制御
  src/Eccube/Controller/Admin/Store/PluginController.php
Labels: bug

#3731 プラグインジェネレータを最新化
  src/Eccube/Command/PluginGenerateCommand.php
Labels: Status: needs-review

#3708 会員CSVダウンロードで、検索条件が適用されない不具合を修正
  src/Eccube/Service/CsvExportService.php
Labels: Status: needs-review, bug

#3738 日本語テンプレートへの変換スクリプトを追加
  bin/template_jp.php
  src/Eccube/Resource/template/default/Block/search_product.twig
Labels: Status: ready-for-merge, document

#3737 【DBスキーマ変更】BlockPositionからPageは参照する必要がないので削除
  src/Eccube/Entity/BlockPosition.php
Labels: Status: needs-review, bug

#3688 お届け先を複数指定した際、商品の在庫数が正常に減らない不具合修正
  codeception/acceptance/EF03OrderCest.php
  src/Eccube/Service/PurchaseFlow/Processor/StockReduceProcessor.php
Labels: Status: needs-review

#3755 会員住所の削除処理を実装
  src/Eccube/Resource/template/admin/Customer/edit.twig
  tests/Eccube/Tests/Web/Admin/Customer/CustomerDeliveryEditControllerTest.php
Labels: bug

#3759 TaxRuleControllerTest の修正
  codeception/acceptance/EA07BasicinfoCest.php
  src/Eccube/Form/Type/Admin/TaxRuleType.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/TaxRuleControllerTest.php
Labels: Status: ready-for-merge, bug

#3760 エラーページで DOCTYPE が二重に表示されている
  src/Eccube/Resource/template/default/error.twig
Labels: bug

#3766 システムエラー時にログ出力を行うように修正
  src/Eccube/EventListener/ExceptionListener.php
Labels: Status: ready-for-merge, enhancement

#3767 会員で購入フロー開始した後、マイページで住所を変えても、注文者情報に反映されない問題の修正
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Service/OrderHelper.php
  tests/Eccube/Tests/Service/OrderHelperTest.php
Labels: Status: ready-for-merge, enhancement

#3757 デフォルトの商品CSVをそのままアップロードできない不具合の修正
  src/Eccube/Controller/Admin/Product/CsvImportController.php
Labels: Status: ready-for-merge, bug

#3748 メール履歴が保存できていなかった不具合の修正/マイページの表示を調整
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/js/script.js
  html/template/default/assets/scss/project/_16.2.historyDetail.scss
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/default/Mypage/history.twig
Labels: Status: ready-for-merge, bug

#3751 フロント画面商品一覧の件数を20件刻みに変更
  codeception/acceptance/EF02ProductCest.php
  src/Eccube/Resource/doctrine/import_csv/mtb_product_list_max.csv
Labels: enhancement

#3774 IEで表示時にパンくずの表示崩れを修正
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/component/_7.2.search.scss
Labels: Status: ready-for-merge

#3780 認証キーとcomposerの設定が同期するように修正
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Service/Composer/ComposerApiService.php
Labels: bug

#3756 .htaccess と web.config の見直し
  .htaccess
  bin/.htaccess
  codeception/.htaccess
  html/plugin/web.config
  html/template/web.config
  html/upload/web.config
  html/user_data/web.config
  html/web.config
  web.config
Labels: Status: needs-review

#3750 規格を初期化した商品がカートに投入できない不具合の修正
  src/Eccube/Form/DataTransformer/EntityToIdTransformer.php
  src/Eccube/Form/Type/AddCartType.php
  src/Eccube/Repository/ProductRepository.php
  tests/Eccube/Tests/Repository/ProductRepositoryTest.php
Labels: Status: fix-me, bug

#3771 複数配送時の納品書出力のフォーマット変更
  html/template/admin/assets/pdf/nouhinsyo.pdf
  html/template/admin/assets/pdf/nouhinsyo_multiple.pdf
  src/Eccube/Service/OrderPdfService.php
Labels: Status: ready-for-merge

#3761 仮会員登録時の文言が会員登録が完全に完了したみたいになっている件
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/Entry/complete.twig
Labels: Status: ready-for-merge

#3763 おすすめプラグインの表示
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Command/PluginSchemaUpdateCommand.php
  src/Eccube/Command/PluginUpdateCommand.php
  src/Eccube/Controller/Admin/AdminController.php
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Exception/PluginApiException.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Store/plugin_detail_modal.twig
  src/Eccube/Resource/template/admin/Store/plugin_search.twig
  src/Eccube/Resource/template/admin/Store/plugin_search_panel.twig
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
  src/Eccube/Resource/template/admin/index.twig
  src/Eccube/Service/PluginApiService.php
  src/Eccube/Service/PluginService.php
Labels: Status: needs-review

#3781 composer update
  composer.lock
  symfony.lock
Labels: Status: ready-for-merge

#3787 管理画面の月間グラフバー表示の修正
  src/Eccube/Resource/template/admin/index.twig
Labels: enhancement

#3702 【ショップ設定】ポイント付与率に単位が欲しい
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
Labels: Status: fix-me

#3779 支払方法設定での画像登録時のレイアウト修正、商品登録、支払方法登録画面に商品画像推奨サイズを追加
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
Labels: Status: ready-for-merge

#3789 ポイント設定のTooltip修正
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: needs-review

#3762 【ie フロントTOP】フロントTOPの上から2段目の画像がIEだと縦長に歪んで見えます。
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/project/_12.2.eyecatch.scss
  src/Eccube/Resource/template/default/Block/eyecatch.twig
Labels: Status: fix-me, Status: needs-review

#3667 メールアドレスのRFCチェックを設定ファイルで切り替えられるように対応、デフォルトはRFCのチェックを行わない
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Controller/NonMemberShoppingController.php
  src/Eccube/Form/Type/Admin/CustomerType.php
  src/Eccube/Form/Type/Admin/OrderType.php
  src/Eccube/Form/Type/Admin/ShopMasterType.php
  src/Eccube/Form/Type/Front/ContactType.php
  src/Eccube/Form/Type/Front/CustomerLoginType.php
  src/Eccube/Form/Type/Front/ForgotType.php
  src/Eccube/Form/Type/Front/PassowrdResetType.php
  src/Eccube/Form/Type/Install/Step3Type.php
  src/Eccube/Form/Type/RepeatedEmailType.php
  src/Eccube/Form/Validator/Email.php
  src/Eccube/Form/Validator/EmailValidator.php
  src/Eccube/Kernel.php
  src/Eccube/Resource/template/default/Contact/index.twig
  src/Eccube/Validator/EmailValidator/NoRFCEmailValidator.php
  tests/Eccube/Tests/Form/Type/Admin/CustomerTypeTest.php
  tests/Eccube/Tests/Form/Type/Front/CustomerLoginTypeTest.php
  tests/Eccube/Tests/Form/Type/Front/ForgotTypeTest.php
  tests/Eccube/Tests/Form/Type/RepeatedEmailTypeTest.php
  tests/Eccube/Tests/Form/Validator/EmailValidatorTest.php
  tests/Eccube/Tests/Web/Admin/Customer/CustomerEditControllerTest.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/ShopControllerTest.php
  tests/Eccube/Tests/Web/ContactControllerTest.php
Labels: Status: ready-for-merge, document

#3792 納品書で、商品コードを表示すべきところに商品名が表示されていたのを修正
  src/Eccube/Service/OrderPdfService.php
Labels: bug

#3793 メールテンプレートを `template/default/Mail/` 配下に統一
  src/Eccube/Resource/doctrine/import_csv/dtb_mail_template.csv
  src/Eccube/Resource/template/admin/Mail/entry_confirm.html.twig
  src/Eccube/Resource/template/admin/Mail/entry_confirm.twig
  src/Eccube/Resource/template/admin/Mail/order.html.twig
  src/Eccube/Resource/template/admin/Mail/order.twig
  src/Eccube/Resource/template/admin/Mail/point_notify.twig
  src/Eccube/Resource/template/default/Mail/point_notify.twig
  src/Eccube/Resource/template/default/Mail/shipping_notify.html.twig
  src/Eccube/Resource/template/default/Mail/shipping_notify.twig
  src/Eccube/Service/MailService.php
Labels: bug

#3799 案内やエラーメッセージの文言を変更。
  codeception/acceptance/EF04CustomerCest.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/Shopping/complete.twig
  tests/Eccube/Tests/Web/CartValidationTest.php
Labels: Status: ready-for-merge

#3783 受注編集画面で表示される商品一覧のレイアウト修正
  src/Eccube/Resource/template/admin/Form/bootstrap_4_horizontal_layout.html.twig
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
Labels: Status: ready-for-merge

#3810 支払い方法を検索条件に指定した場合に多重定義エラーとなる不具合の修正
  src/Eccube/Repository/OrderRepository.php
  tests/Eccube/Tests/Repository/OrderRepositoryGetQueryBuilderBySearchDataAdminTest.php
Labels: bug

#3736 フロント画面の画像を調整
  html/template/default/assets/img/top/fpo_355x150.png
  html/upload/save_image/no_image_product.jpg
  html/upload/save_image/no_image_product.png
  src/Eccube/Resource/template/default/Block/category.twig
  src/Eccube/Resource/template/default/Block/new_item.twig
  src/Eccube/Twig/Extension/EccubeExtension.php
Labels: affected:template

#3749 一覧系画面のアイコンの間隔を調整
  codeception/_support/Page/Admin/ClassNameManagePage.php
  codeception/_support/Page/Admin/OrderManagePage.php
  src/Eccube/Resource/template/admin/Content/file.twig
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Product/category.twig
  src/Eccube/Resource/template/admin/Product/class_category.twig
  src/Eccube/Resource/template/admin/Product/class_name.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/admin/Product/tag.twig
  src/Eccube/Resource/template/admin/Setting/Shop/delivery.twig
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_time_prototype.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment.twig
  src/Eccube/Resource/template/admin/Setting/System/member.twig
Labels: affected:template

#3813 HEADメソッドで商品一覧にアクセスされると500エラーが発生するため、500エラーを発生させない対応
  src/Eccube/Controller/ProductController.php
  src/Eccube/Resource/template/default/Product/list.twig
Labels: bug

#3642 【PC】【配送登録】エラー表示
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_edit.twig
Labels: Status: ready-for-merge

#3819 商品規格画面のエンターボタン押した時の項目がコピーされてしまう問題の修正
  src/Eccube/Resource/template/admin/Product/product_class.twig
Labels: bug

#3636 【マイページ】赤伝(マイナス数量の商品)を含む受注は、再注文ボタンを「非表示」にする
  src/Eccube/Controller/Mypage/MypageController.php
  src/Eccube/Resource/template/default/Mypage/history.twig
Labels: Status: ready-for-merge

#3626 未使用関数の削除
  src/Eccube/Repository/CustomerRepository.php
  src/Eccube/Repository/OrderRepository.php
  tests/Eccube/Tests/Repository/CustomerRepositoryTest.php
  tests/Eccube/Tests/Repository/OrderRepositoryTest.php
Labels: Status: ready-for-merge

#3747 Validation postal cost of shipping information
  src/Eccube/Form/Type/Admin/ShippingType.php
Labels: Status: needs-review

#3764 ページトップへのUI がロード時に一瞬表示される
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/component/_2.3.otherbutton.scss
Labels: Status: ready-for-merge

#3818 新着情報の登録「年」を2000年以降から選択できるように変更
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Form/Type/Admin/NewsType.php
Labels: Status: ready-for-merge

#3815 商品一覧のカートボタンの位置を見直し、商品一覧に表示されているタグを削除
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/project/_13.2.shelf.scss
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: ready-for-merge

#3809 非表示や在庫切れなどでカート内に商品がなくなった場合にカート自体を削除する
  src/Eccube/Controller/CartController.php
  src/Eccube/Service/CartService.php
Labels: Status: needs-review, bug

#3828 マイグレーションのテンプレートを削除
  src/Eccube/Resource/template/install/migration.twig
  src/Eccube/Resource/template/install/migration_end.twig
  src/Eccube/Resource/template/install/migration_frame.twig
  src/Eccube/Resource/template/install/migration_plugin.twig
Labels: Status: ready-for-merge

#3822 商品一覧、受注一覧、会員一覧をIEで表示時に横幅に収まるように修正
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Product/index.twig
Labels: Status: fix-me

#3837 商品規格画面から戻る先の制御をフラグで制御するように修正
  src/Eccube/Controller/Admin/Product/ProductClassController.php
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/admin/Product/product_class.twig
Labels: bug

#3829 ページ管理のmetaタグを拡張してOGタグの設定を可能に
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/page_edit.twig
  src/Eccube/Resource/template/default/default_frame.twig
Labels: document, enhancement

#3547 #340 【受注登録】メールの新規作成時にページ離脱防止のアラートが表示されない
  codeception/_support/Page/Admin/OrderEditPage.php
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Form/Type/Admin/OrderType.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: enhancement

#3831 【レイアウト管理】プレビュー機能の追加
  codeception/_support/Page/Admin/LayoutEditPage.php
  codeception/_support/Page/Admin/PageManagePage.php
  codeception/acceptance/EA06ContentsManagementCest.php
  src/Eccube/Controller/Admin/Content/LayoutController.php
  src/Eccube/Entity/Layout.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Form/Type/Admin/LayoutType.php
  src/Eccube/Repository/BlockPositionRepository.php
  src/Eccube/Repository/BlockRepository.php
  src/Eccube/Repository/LayoutRepository.php
  src/Eccube/Resource/doctrine/import_csv/dtb_layout.csv
  src/Eccube/Resource/doctrine/import_csv/dtb_page_layout.csv
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/layout.twig
  tests/Eccube/Tests/Form/Type/Admin/LayoutTypeTest.php
  tests/Eccube/Tests/Repository/BlockPositionRepositoryTest.php
  tests/Eccube/Tests/Repository/LayoutRepositoryTest.php
  tests/Eccube/Tests/Web/Admin/Content/LayoutControllerTest.php
Labels: Status: ready-for-merge

#3835 サイト情報の送信に失敗しても、インストールは継続できるようにする。
  src/Eccube/Controller/Install/InstallController.php
Labels: Status: ready-for-merge

#3844 Cart::sort_no を追加
  src/Eccube/Entity/Cart.php
Labels: enhancement

#3838 エンティティ拡張の自動出力でCSSクラス名を指定できるよう修正
  src/Eccube/Annotation/FormAppend.php
  src/Eccube/Form/Extension/DoctrineOrmExtension.php
  src/Eccube/Resource/template/default/Contact/confirm.twig
  src/Eccube/Resource/template/default/Contact/index.twig
  src/Eccube/Resource/template/default/Entry/confirm.twig
  src/Eccube/Resource/template/default/Entry/index.twig
  src/Eccube/Resource/template/default/Mypage/change.twig
  src/Eccube/Resource/template/default/Mypage/delivery_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_multiple_edit.twig
Labels: document

#3836 SSL強制でないときは、http,httpsどちらでも受け入れるように修正。
  app/config/eccube/packages/security.yaml
  src/Eccube/DependencyInjection/EccubeExtension.php
  src/Eccube/Kernel.php
Labels: Status: needs-review

#3824 同一フォーム利用時にhtml属性のidが被る時があるため、被るフォーム項目はid属性を出力しないように対応
  codeception/_support/Page/Front/TopPage.php
  codeception/acceptance/EF01TopCest.php
  src/Eccube/Resource/template/default/Block/search_product.twig
  src/Eccube/Resource/template/default/Form/form_div_layout.twig
  tests/Eccube/Tests/Web/SearchProductControllerTest.php
Labels: Status: ready-for-merge

#3852 出荷通知メールの注文者情報が配送先情報となっていたので注文者情報に修正
  src/Eccube/Resource/template/default/Mail/shipping_notify.html.twig
  src/Eccube/Resource/template/default/Mail/shipping_notify.twig
  src/Eccube/Service/MailService.php
Labels: bug

#3857 Fix typo
  src/Eccube/Controller/Admin/Content/FileController.php
Labels: bug

#3864 「ページトップへ」を言語ファイルへ切り出し
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/component/_2.3.otherbutton.scss
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/default_frame.twig
Labels: Status: ready-for-merge

#3871 商品一覧のパフォーマンスチューニング
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Controller/Admin/Product/ProductClassController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/ProductController.php
  src/Eccube/Repository/AbstractRepository.php
  src/Eccube/Repository/ProductRepository.php
Labels: document
