Repository EC-CUBE/ec-cube, pull requests merged in 2019-10, with the labels that each got.

#4333 `docker build`処理の高速化と生成されるイメージファイルの軽量化.
  Dockerfile
Labels: improvement

#4324 新着商品をhoverしたときcolorとunderlineの色が異なるのを修正
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/project/_12.6.newItem.scss
Labels: affected:template, css

#4339 時折失敗するテストを修正
  tests/Eccube/Tests/Web/Admin/Order/OrderPdfControllerTest.php
Labels: bug:Low

#4344 RepeatedEmailTypeのバリデーションに文字列長を追加
  src/Eccube/Form/Type/RepeatedEmailType.php
  tests/Eccube/Tests/Form/Type/RepeatedEmailTypeTest.php
Labels: bug:Low

#4342 [webkit系以外] ドロワーの見出しの不要なmergeを削除
  html/template/admin/assets/css/maps/app.css.map
  html/template/admin/assets/css/maps/bootstrap.css.map
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/project/_11.2.header.scss
Labels: affected:template, bug:Low

#4341 カートに追加した商品の数量をマイナスにできてしまう問題の修正
  src/Eccube/Service/PurchaseFlow/Processor/EmptyItemsValidator.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/EmptyItemsValidatorTest.php
Labels: bug:Low

#4352 商品詳細ページのmetaにデフォルトとしてデータを指定
  src/Eccube/Resource/doctrine/import_csv/en/dtb_page.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_page.csv
Labels: Status: ready-for-merge, improvement

#4285 Fix command of doctrine errors #4284
  src/Eccube/Entity/BaseInfo.php
  src/Eccube/Service/Composer/ComposerServiceFactory.php
  src/Eccube/Service/PluginApiService.php
Labels: Status: ready-for-merge, bug:Low

#4353 gulpの見直し
  .gitignore
  gulpconfig.js.sample
  gulpfile.js
  html/template/admin/assets/css/app.css
  html/template/admin/assets/css/app.css.map
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/css/app.min.css.map
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/css/maps/app.css.map
  html/template/admin/assets/css/maps/bootstrap.css.map
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  package-lock.json
  package.json
Labels: Status: ready-for-merge, document, enhancement
