Repository EC-CUBE/ec-cube, pull requests merged in 2019-02, with the labels that each got.

#4017 リダイレクト処理の修正(3.1)
  src/Eccube/Application.php
  src/Eccube/Common/Constant.php
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationFailureHandler.php
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationSuccessHandler.php
Labels: Status: needs-review, enhancement

#4074 [4.0] composer update 2019-02-07
  composer.json
  composer.lock
Labels: enhancement

#4058 Proxy ファイルを利用して doctrine:schema:update コマンドを実行できるよう修正
  .travis.yml
  src/Eccube/Command/UpdateSchemaDoctrineCommand.php
  src/Eccube/Service/PluginService.php
  src/Eccube/Service/SchemaService.php
  tests/Eccube/Tests/Command/UpdateSchemaDoctrineCommandTest.php
  tests/Eccube/Tests/Service/PluginServiceTest.php
  tests/Eccube/Tests/Service/PluginServiceWithEntityExtensionTest.php
Labels: Status: ready-for-merge, bug:High

#4076 InstallerControllerTest で dotenv をバックアップするよう修正
  tests/Eccube/Tests/Web/Install/InstallControllerTest.php
Labels: Status: ready-for-merge, enhancement

#4075 Copy favicon to user_data directory
  app/config/eccube/packages/framework.yaml
  codeception/_support/Page/Admin/FileManagePage.php
  codeception/acceptance/EA06ContentsManagementCest.php
  src/Eccube/Command/LoadDataFixturesEccubeCommand.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/file.twig
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Resource/template/default/error.twig
  tests/Eccube/Tests/Web/Install/InstallControllerTest.php
  tests/Eccube/Tests/Web/TopControllerTest.php
Labels: Status: ready-for-merge, affected:template, affected:外部仕様, enhancement

#4081 独自プラグインの有効/無効ボタンの重なりを修正 (Fixed Original Plugin On/Off button position.)
  src/Eccube/Resource/template/admin/Store/plugin_table.twig
Labels: affected:admin_template, bug:Low

#4084 JS管理追加
  .gitignore
  app/config/eccube/packages/eccube_nav.yaml
  html/user_data/assets/js/customize.js
  src/Eccube/Controller/Admin/Content/JsController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/js.twig
  src/Eccube/Resource/template/default/default_frame.twig
  tests/Eccube/Tests/Web/Admin/Content/JsControllerTest.php
Labels: affected:template, affected:外部仕様, enhancement

#4087 html配下のプラグインディレクトリを削除するように修正
  src/Eccube/Service/PluginService.php
  tests/Eccube/Tests/Service/PluginServiceTest.php
Labels: bug:High
