Repository EC-CUBE/ec-cube, pull requests merged in 2019-04, with the labels that each got.

#4124 テストケースで ID が正常に取得できなかったのを修正
  tests/Eccube/Tests/Web/Admin/Order/OrderPdfControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4127 置換パラメーター名の指定が間違っている
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Mypage/DeliveryControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4128 EccubeTestCase::loginTo の Client を使いまわすよう修正
  tests/Eccube/Tests/Web/Admin/Order/OrderPdfControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4134 Use Docker container to Mailcatcher
  .travis.yml
Labels: Status: ready-for-merge, enhancement

#3499 【ショッピングカート】複数商品に対するエラーメッセージが１つしか表示されない
  src/Eccube/Controller/AbstractController.php
  tests/Eccube/Tests/Web/CartControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4118 [4.0] composer update 2019-03-26
  composer.lock
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
Labels: Status: ready-for-merge

#4121 バリデーションエラー発生時に、ブロックの変更内容が保持されない問題に対応
  codeception/_support/Page/Admin/LayoutEditPage.php
  codeception/_support/Page/Admin/LayoutManagePage.php
  codeception/acceptance/EA06ContentsManagementCest.php
  src/Eccube/Form/Type/Admin/LayoutType.php
Labels: Status: ready-for-merge, bug:Low

#4132 受注ステータス一括変更のテストが落ちるのを修正する試み
  codeception/acceptance/EA04OrderCest.php
Labels: Status: ready-for-merge, bug:Low

#4146 form_div_layout.twigの空白スペースの調整
  src/Eccube/Resource/template/default/Form/form_div_layout.twig
Labels: Status: ready-for-merge, bug:Low

#4138 Use MailCatcher on Docker
  appveyor.yml
Labels: Status: ready-for-merge, enhancement

#4139 大文字の拡張子で画像アップロードできるよう修正
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
  src/Eccube/Controller/Admin/Store/TemplateController.php
  tests/Eccube/Tests/Web/Admin/Product/ProductContorllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/PaymentControllerTest.php
  tests/Eccube/Tests/Web/Admin/Store/TemplateControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4148 管理画面>ファイル管理のファイル削除時にそのままカレントディレクトリに止まるように修正
  src/Eccube/Controller/Admin/Content/FileController.php
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: Status: needs-review, bug:Low

#4147 フロントの注文履歴画面で、お問い合わせ欄の改行がエスケープされないように修正
  src/Eccube/Resource/template/default/Mypage/history.twig
Labels: Status: needs-review, bug:Low

#4145 管理画面の受注管理からお届け時間の指定を「指定なし」に変更できない不具合の修正
  src/Eccube/Form/Type/Admin/ShippingType.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4150 PRテンプレートにレビュワーの確認項目を追加
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: ready-for-merge

#3160 cache:clearコマンドでpluginディレクトリが対象外となっていたため追加
  src/Eccube/Util/Cache.php
  tests/Eccube/Tests/Util/CacheTest.php
Labels: Status: ready-for-merge, bug:Low

#3162 HEADメソッドで商品一覧にアクセスされると500エラーが発生するため、500エラーを発生させない対応
  src/Eccube/Controller/ProductController.php
Labels: Status: ready-for-merge, bug:Low

#3163 メール送信時にhtml特殊文字が本文中にあるとエスケープされていたため、エスケープされないように対応
  src/Eccube/Resource/template/admin/Mail/entry_confirm.twig
  src/Eccube/Resource/template/admin/Mail/order.twig
  src/Eccube/Resource/template/default/Mail/contact_mail.twig
  src/Eccube/Resource/template/default/Mail/customer_withdraw_mail.twig
  src/Eccube/Resource/template/default/Mail/entry_complete.twig
  src/Eccube/Resource/template/default/Mail/entry_confirm.twig
  src/Eccube/Resource/template/default/Mail/forgot_mail.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mail/reset_complete_mail.twig
Labels: Status: ready-for-merge, bug:Low

#3164 お届け先編集時に存在しないURL指定をした時のシステムエラーを修正
  src/Eccube/Controller/Mypage/DeliveryController.php
  tests/Eccube/Tests/Web/Mypage/DeliveryControllerTest.php
Labels: Status: ready-for-merge, bug:Low
