Repository EC-CUBE/ec-cube, pull requests merged in 2019-11, with the labels that each got.

#4371 AppVeyor のバッジが unknown になっていたため修正
  README.md
Labels: improvement

#4374 お届け日のメッセージキー翻訳忘れを修正
  src/Eccube/Form/Type/Admin/SearchOrderType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: ready-for-merge, bug:Low

#4159 eccube_order_no_formatのdtb_order.idの桁数分0埋めの指定をしても動作するように修正
  src/Eccube/Service/PurchaseFlow/Processor/OrderNoProcessor.php
Labels: Status: ready-for-merge, bug:Middle

#4218 商品CSVアップロード時、商品詳細の文字数がDBに保存できる数を超えた場合にエラーメッセージを表示する
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4337 GitHub Actions support
  .github/workflows/action.yml
  codeception/_envs/github_action.yml
Labels: experimental

#4380 2系、3系のリポジトリ変更に伴う README 修正
  README.md
Labels: documentation

#4373 ルート以下ディレクトリにインストールした場合お気に入りに登録できない問題の対応
  src/Eccube/Controller/ProductController.php
Labels: Status: ready-for-merge, bug:Low

#4389 doc4.ec-cube.netページのドキュメント管理リポジトリが変更されたため、こちらも変更.
  README.md
Labels: documentation

#4391 docker-composeによる環境構築に対応
  .env.dist
  Dockerfile
  docker-compose.yml
  web.config
Labels: Status: ready-for-merge

#4231 ユーザー独自プラグインのアップデートしてもスキーマがアップデートされない
  app/config/eccube/packages/codeception/doctrine.yaml
  codeception/_data/plugins/Horizon-1.0.1.tgz
  codeception/acceptance/EA10PluginCest.php
  codeception/acceptance/EF01TopCest.php
  src/Eccube/Service/PluginService.php
  src/Eccube/Util/CacheUtil.php
Labels: Status: fix-me, bug:Middle
