Repository EC-CUBE/ec-cube, pull requests merged in 2019-08, with the labels that each got.

#4247 出荷CSV登録 エラー行番号修正 Fix #4246
  src/Eccube/Controller/Admin/Order/CsvImportController.php
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Admin/Order/CsvImportControllerTest.php
Labels: Status: ready-for-merge, bug:Middle

#4223 PurchaseFlow のツリー表示
  src/Eccube/Service/PurchaseFlow/PurchaseFlow.php
Labels: Status: ready-for-merge, improvement

#4202 カテゴリー編集フォームのイベントに渡す変数を修正
  src/Eccube/Controller/Admin/Product/CategoryController.php
Labels: Status: ready-for-merge, bug:Low

#4189 新規に税率設定する場合に現在の丸め規則をデフォルト値とするよう修正
  src/Eccube/Controller/Admin/Product/ProductClassController.php
  src/Eccube/Repository/TaxRuleRepository.php
  tests/Eccube/Tests/Repository/TaxRuleRepositoryTest.php
  tests/Eccube/Tests/Web/Admin/Product/ProductClassControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/ProductContorllerTest.php
Labels: Status: ready-for-merge, bug:Low, improvement

#4238 開発環境用のservices.yamlをプラグインでも用意できるようにする
  src/Eccube/Kernel.php
Labels: improvement

#4126 在庫が0の状態で注文取り消しができるように修正
  src/Eccube/Service/PurchaseFlow/Processor/StockDiffProcessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/StockDiffProcessorTest.php
Labels: Status: ready-for-merge, bug:Low

#4258 認証キー設定のUIを変更
  codeception/acceptance/EA07BasicinfoCest.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Store/authentication_setting.twig
Labels: improvement

#4235 ファイル管理で複数ファイルのアップロードを実装
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/file.twig
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: improvement

#4229 配送管理でお届け時間が並び替えられない不具合の修正
  src/Eccube/Entity/Delivery.php
Labels: affected:外部仕様, bug:Low

#4225 受注管理 マルチ検索の対象項目修正
  src/Eccube/Repository/OrderRepository.php
  tests/Eccube/Tests/Repository/OrderRepositoryGetQueryBuilderBySearchDataAdminTest.php
Labels: bug:Low

#4266 PullRequestテンプレート：説明の部分をコメントアウトするようにした。
  .github/PULL_REQUEST_TEMPLATE.md
Labels: document

#4270 プラグインのアップデートから有効化処理を削除
  codeception/acceptance/EA10PluginCest.php
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
Labels: Status: ready-for-merge, bug:Middle

#4237 非ログイン時のお気に入り登録挙動修正 Fix #4165
  src/Eccube/Resource/template/default/Mypage/login.twig
  tests/Eccube/Tests/Web/ProductControllerTest.php
Labels: bug:Middle

#4273 認証キー設定のTooltipを変更
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Store/authentication_setting.twig
Labels: Easy, bug:Low

#4276 受注管理での税率・税額を受注時点のデータを元とし編集可能にする
  src/Eccube/Entity/OrderItem.php
  src/Eccube/Form/Type/Admin/OrderItemType.php
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Service/PointHelper.php
  src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
  tests/Eccube/Tests/Form/Type/Admin/OrderItemTypeTest.php
  tests/Eccube/Tests/Repository/ShippingRepositoryTest.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/TaxProcessorTest.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
Labels: 軽減税率対応

#4277 商品CSV登録に除外可能なカラムを設定できるように修正
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: bug:Middle

#4280 プラグイン一覧画面にインストールリンクを設置
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
Labels: improvement

#4281 税率設定：商品CSVの入出力で、商品別税率を登録できるようにする #1741
  app/DoctrineMigrations/Version20190821081036.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_csv.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: affected:外部仕様, improvement, 軽減税率対応

#4283 出荷管理でPurchaseFlowを実行するように修正
  src/Eccube/Controller/Admin/Order/ShippingController.php
  tests/Eccube/Tests/Web/Admin/Order/ShippingControllerTest.php
Labels: bug:Middle

#4287 商品一覧における商品個別税率のN+1問題の改善
  src/Eccube/Service/TaxRuleService.php
Labels: 軽減税率対応

#4286 区分記載請求書対応
  src/Eccube/Entity/Order.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/default/Mail/order.html.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mypage/history.twig
  src/Eccube/Resource/template/default/Shopping/confirm.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
  src/Eccube/Service/OrderPdfService.php
  src/Eccube/Twig/Extension/TaxExtension.php
  tests/Eccube/Tests/Entity/OrderTest.php
  tests/Eccube/Tests/Twig/Extension/TaxExtensionTest.php
Labels: improvement, 軽減税率対応

#4288 インストーラでSQLエラーが発生する問題を修正
  app/config/eccube/services.yaml
Labels: bug:Critical

#4290 明細のバリデーションエラー発生時にシステムエラーになる不具合を修正
  src/Eccube/Form/Type/Admin/OrderItemType.php
Labels: bug:High

#4296 税率が0%の値引き明細はクーポン・ポイントと同様に扱うように変更
  src/Eccube/Entity/Order.php
  src/Eccube/Form/Type/Admin/OrderItemType.php
  tests/Eccube/Tests/Entity/OrderTest.php
Labels: 軽減税率対応

#4295 fix migrationのSQLの記載ミスでエラーが発生していたのを修正
  app/DoctrineMigrations/Version20190821081036.php
Labels: bug:Middle

#4294 商品規格の初期データのIDが0から始まっていたため税率が正しく判定できていなかった問題の修正
  src/Eccube/Repository/TaxRuleRepository.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_product_class.csv
  src/Eccube/Resource/doctrine/import_csv/en/dtb_product_stock.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_product_class.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_product_stock.csv
  tests/Eccube/Tests/Service/CartServiceTest.php
Labels: bug:Low

#4297 合計金額表示エリアの視認性が向上するようにデザインを変更。
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/component/_7.3.cart.scss
  src/Eccube/Entity/Order.php
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/Mail/order.html.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mypage/history.twig
  src/Eccube/Resource/template/default/Shopping/confirm.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
Labels: affected:template

#4298 #4296 の差し戻し
  src/Eccube/Entity/Order.php
  tests/Eccube/Tests/Entity/OrderTest.php
Labels: 軽減税率対応

#4300 不課税の値引き明細を追加できるように対応
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Form/Type/Admin/OrderItemType.php
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/order_item_prototype.twig
  src/Eccube/Resource/template/admin/Order/order_item_type.twig
Labels: 軽減税率対応

#4301 バージョン番号を更新
  src/Eccube/Common/Constant.php
Labels: improvement
