Repository EC-CUBE/ec-cube, pull requests merged in 2019-06, with the labels that each got.

#4175 お問い合わせテンプレートのheader,footerの修正
  src/Eccube/Resource/template/default/Mail/contact_mail.twig
  src/Eccube/Service/MailService.php
Labels: Status: ready-for-merge, affected:template, bug:Middle

#4179 サイズが大きなデザプレが反映できるようにアップロード最大ファイルサイズを10Mに変更
  .htaccess
Labels: improvement

#4177 商品csvで送料を設定できない不具合の修正
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: bug:Low
