Repository EC-CUBE/ec-cube, pull requests merged in 2019-07, with the labels that each got.

#4205 EA01TopCestお知らせ確認URLの変更
  codeception/acceptance/EA01TopCest.php
Labels: improvement

#4192 postgresqlのDBのバージョンが10.xの場合に、Webインストーラーで発生する不具合修正
  src/Eccube/Command/InstallerCommand.php
  src/Eccube/Controller/Install/InstallController.php
  tests/Eccube/Tests/Web/Install/InstallControllerTest.php
Labels: bug:Low

#4203 拡張に備えてprivate functionをprotectedに変更
  src/Eccube/Controller/Admin/AdminController.php
  src/Eccube/Controller/Admin/Order/OrderController.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Controller/ProductController.php
  src/Eccube/Service/OrderHelper.php
Labels: Status: needs-review

#4188 Change build environment to xenial
  .travis.yml
  codeception.sh
Labels: Status: ready-for-merge, improvement

#4196 注文受付メールの単価表示に関して再修正
  src/Eccube/Resource/template/default/Mail/order.html.twig
  src/Eccube/Resource/template/default/Mail/order.twig
Labels: Status: ready-for-merge, affected:template, bug:Low

#4198 会員管理>会員一覧の「誕生月」ラベルが翻訳されていない
  src/Eccube/Form/Type/Admin/SearchCustomerType.php
Labels: Status: ready-for-merge, bug:Low

#4210 マイページ／お気に入り画面の表示件数の調整
  app/config/eccube/packages/eccube.yaml
Labels: Status: ready-for-merge, improvement

#4216 PDFのロゴ画像をファイル管理から変更できる機能を追加
  src/Eccube/Command/LoadDataFixturesEccubeCommand.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Service/OrderPdfService.php
  tests/Eccube/Tests/Web/Install/InstallControllerTest.php
Labels: Status: ready-for-merge, enhancement

#4211 Codeception を PHP7.3 で実行するように変更
  .travis.yml
Labels: Status: ready-for-merge, improvement

#4219 PHP7.3 で debug toolbar が表示されなくなったのを修正
  src/Eccube/DataCollector/EccubeDataCollector.php
Labels: Status: ready-for-merge, bug:Low

#4222 メンテナンスファイルのパスを環境変数だけで変更できるようにする
  app/config/eccube/packages/eccube.yaml
  index.php
Labels: improvement

#4226 会員削除時メッセージの修正
  src/Eccube/Controller/Admin/Customer/CustomerController.php
Labels: bug:Low

#4204 Dockerfile を追加
  .dockerignore
  .htaccess
  Dockerfile
  dockerbuild/.htaccess
  dockerbuild/php.ini
  web.config
Labels: Status: ready-for-merge, enhancement

#4117 同名の Entity が存在した場合、Proxy ファイルを上書きしないよう修正
  .gitignore
  .travis.yml
  codeception.sh
  codeception/acceptance/EA10PluginCest.php
  src/Eccube/Command/UpdateSchemaDoctrineCommand.php
  src/Eccube/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  src/Eccube/Doctrine/ORM/Mapping/Driver/ReloadSafeAnnotationDriver.php
  src/Eccube/Kernel.php
  src/Eccube/Service/EntityProxyService.php
  src/Eccube/Service/PluginService.php
  src/Eccube/Service/SchemaService.php
  tests/Eccube/Tests/Command/UpdateSchemaDoctrineCommandTest.php
  tests/Eccube/Tests/Service/EntityProxyServiceTest.php
  tests/Eccube/Tests/Service/PluginServiceTest.php
  tests/Eccube/Tests/Service/PluginServiceWithEntityExtensionTest.php
Labels: Status: needs-review, affected:plugin, bug:High

#4240 EA01TopCest：遷移先のURLチェック処理を修正
  codeception/acceptance/EA01TopCest.php
Labels: bug:Low

#4242 READMEからwikiのコピーライトポリシーにリンクするように修正(4系)
  README.md
Labels: document

#4243 READMEからwikiのコピーライトポリシーにリンクするように修正(3系)
  README.md
Labels: document

#4244 READMEからwikiのコピーライトポリシーにリンクするように修正(3.1系)
  README.md
Labels: document

#4245 3.1.xブランチはunstable版であるということをREADMEに明記した
  README.md
Labels: document

#4221 マスタデータ管理でOrderStatusを追加できない不具合を修正
  src/Eccube/Controller/Admin/Setting/System/MasterdataController.php
  src/Eccube/Entity/Master/OrderStatus.php
  tests/Eccube/Tests/Web/Admin/Setting/System/MasterdataControllerTest.php
Labels: Status: needs-review, bug:Low

#4241 タグが紐付いている商品を、商品一覧より削除できるように変更
  src/Eccube/Entity/Product.php
  tests/Eccube/Tests/Web/Admin/Product/ProductContorllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4233 カテゴリー名が２行以上になっても上下の余白を保つ
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/project/_11.2.header.scss
Labels: Status: ready-for-merge, affected:template, bug:Low
