Repository EC-CUBE/ec-cube, pull requests merged in 2019-05, with the labels that each got.

#4152 [3.0] composer update 2019-04-26
  composer.lock
Labels: enhancement

#3166 PluginServiceのplugin_id指定をEntity名に修正
  src/Eccube/Service/PluginService.php
Labels: bug

#3167 ページング時にURLパラメータが存在していた時のページングに対応できないため、URLパラメータがあってもページングできるように対応
  src/Eccube/Resource/template/default/pagination.twig
Labels: Status: needs-review, enhancement

#3168 パスワードの再発行時に存在しないメールアドレスが入力されたら入力チェックエラーとして表示するように対応
  src/Eccube/Controller/ForgotController.php
Labels: Status: discussion, enhancement

#4155 重複したdlの閉じタグを削除
  src/Eccube/Resource/template/default/Forgot/reset.twig
Labels: Status: ready-for-merge, affected:template, bug:Low

#4153 [4.0] composer update 2019-04-26
  composer.lock
Labels: enhancement

#4170 複数配送の際に、配送通知メール文頭の宛先名は注文者であるべき
  src/Eccube/Resource/template/default/Mail/shipping_notify.html.twig
  src/Eccube/Resource/template/default/Mail/shipping_notify.twig
Labels: Status: needs-review, affected:template, bug:Low
