Repository EC-CUBE/ec-cube, pull requests merged in 2019-03, with the labels that each got.

#4093 プラグインインストール時のエラーが表示されない場合があるのを修正
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
Labels: Status: ready-for-merge, bug:Low

#4090 CartItemにgetIdメソッドを追加
  src/Eccube/Entity/CartItem.php
Labels: Status: ready-for-merge, enhancement

#4100 管理画面URLの正規表現がインストーラとセキュリティ管理で異なっていたので修正
  codeception/acceptance/EA01TopCest.php
  src/Eccube/Form/Type/Admin/SecurityType.php
  tests/Eccube/Tests/Form/Type/Admin/SecurityTypeTest.php
Labels: Status: ready-for-merge, bug:Low

#4099 価格を含む商品規格の編集時に商品の更新日時が更新されるように修正
  src/Eccube/Controller/Admin/Product/ProductController.php
  tests/Eccube/Tests/Web/Admin/Product/ProductContorllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4111 githubのドキュメントを 3系 -> 4系 に更新
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: document

#4115 mailcatcher のバージョンを 0.6.5 に固定（3.1）
  .travis.yml
Labels: Status: ready-for-merge, bug:Low

#4114 管理画面からの受注登録時にもpre_order_idを発行(4.0)
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Service/OrderHelper.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
Labels: Status: ready-for-merge, affected:外部仕様, bug:Low

#3816 数字入力の最大文字数設定
  src/Eccube/Form/Type/TelType.php
  src/Eccube/Form/Type/ZipType.php
Labels: Status: ready-for-merge

#3591 コードエディタのサイズを調整可能に変更
  src/Eccube/Resource/template/admin/Content/block_edit.twig
  src/Eccube/Resource/template/admin/Content/css.twig
  src/Eccube/Resource/template/admin/Content/js.twig
  src/Eccube/Resource/template/admin/Content/page_edit.twig
  src/Eccube/Resource/template/admin/Setting/Shop/mail.twig
Labels: Status: ready-for-merge, affected:admin_template, enhancement

#3903 【3系】pre_order_idが受注全体でユニークとなるように変更
  src/Eccube/Service/ShoppingService.php
Labels: Status: ready-for-merge

#4113 管理画面からの受注登録時にもpre_order_idを発行(3.1)
  src/Eccube/Controller/Admin/Order/EditController.php
Labels: Status: ready-for-merge, bug:Low

#4045 Add PHP7.3 to Travis
  .travis.yml
  composer.json
  composer.lock
  symfony.lock
Labels: Status: ready-for-merge, enhancement

#4122 ファイル管理：画像の場合はサムネイル表示を行うように対応
  src/Eccube/Resource/template/admin/Content/file.twig
  src/Eccube/Twig/Extension/EccubeExtension.php
  tests/Eccube/Tests/Twig/Extension/EccubeExtensionTest.php
Labels: Status: ready-for-merge, enhancement

#4123 plugin_search.twigのinfoクラスのmin-heightを修正
  src/Eccube/Resource/template/admin/Store/plugin_search.twig
Labels: Status: ready-for-merge, bug:Low
