Repository EC-CUBE/ec-cube, pull requests merged in 2019-09, with the labels that each got.

#4302 軽減税率対応
  app/DoctrineMigrations/Version20190821081036.php
  app/config/eccube/services.yaml
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/component/_7.3.cart.scss
  src/Eccube/Common/Constant.php
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Controller/Admin/Order/ShippingController.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Entity/Order.php
  src/Eccube/Entity/OrderItem.php
  src/Eccube/Form/Type/Admin/OrderItemType.php
  src/Eccube/Repository/TaxRuleRepository.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/en/dtb_product_class.csv
  src/Eccube/Resource/doctrine/import_csv/en/dtb_product_stock.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_product_class.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_product_stock.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/order_item_prototype.twig
  src/Eccube/Resource/template/admin/Order/order_item_type.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
  src/Eccube/Resource/template/default/Mail/order.html.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mypage/history.twig
  src/Eccube/Resource/template/default/Shopping/confirm.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
  src/Eccube/Service/OrderPdfService.php
  src/Eccube/Service/PointHelper.php
  src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
  src/Eccube/Service/TaxRuleService.php
  src/Eccube/Twig/Extension/TaxExtension.php
  tests/Eccube/Tests/Entity/OrderTest.php
  tests/Eccube/Tests/Form/Type/Admin/OrderItemTypeTest.php
  tests/Eccube/Tests/Repository/ShippingRepositoryTest.php
  tests/Eccube/Tests/Service/CartServiceTest.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/TaxProcessorTest.php
  tests/Eccube/Tests/Twig/Extension/TaxExtensionTest.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
  tests/Eccube/Tests/Web/Admin/Order/ShippingControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: enhancement

#4309 マイグレーション時のエラーを修正
  app/DoctrineMigrations/Version20190821081036.php
Labels: bug:High

#4323 drawrボタンにcursorを設定
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/project/_11.2.header.scss
Labels: affected:template, bug:Low, css

#4321 font-sizeが逆に設定されいてるのを修正
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/component/_1.2.typo.scss
  html/template/default/assets/scss/project/_14.1.product.scss
Labels: Status: ready-for-merge, affected:template, bug:Low

#4331 商品別税率設定の修正
  src/Eccube/Entity/TaxRule.php
  tests/Eccube/Tests/Entity/TaxRuleTest.php
  tests/Eccube/Tests/Repository/TaxRuleRepositoryTest.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/TaxProcessorTest.php
Labels: Status: ready-for-merge, affected:外部仕様, bug:High

#4322 納品書PDFに店舗の都道府県がない問題を修正
  src/Eccube/Service/OrderPdfService.php
Labels: Status: ready-for-merge, bug:Low

#4334 Webインストーラーのウィザード進捗をわかりやすくしました。
  html/template/install/assets/css/dashboard.css
Labels: improvement
