Repository EC-CUBE/ec-cube, pull requests merged in 2020-02, with the labels that each got.

#4444 travis対応
  .travis.yml
Labels: bug:Low

#4430 Remove htaccess unnecessary sharp
  .htaccess
Labels: Status: ready-for-merge, improvement

#4453 トップページの誤字修正
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: ready-for-merge, bug:Low

#4446 Slack の招待URLを修正
  README.md
Labels: Status: ready-for-merge, documentation

#4451 受注一覧 検索条件ラベルの間違い修正
  src/Eccube/Form/Type/Admin/SearchOrderType.php
Labels: Status: ready-for-merge, bug:Low

#4419 vendorの綴誤りを修正。
  docker-compose.yml
Labels: Status: ready-for-merge, bug:Low

#4359 Fix #4327
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_13.4.cartModal.scss
Labels: Status: ready-for-merge, affected:template, bug:Low, css

#4449 商品一覧件数セッションキー名、受注一覧との重複を解消
  src/Eccube/Controller/Admin/Product/ProductController.php
Labels: Status: ready-for-merge, bug:Low

#4438 「※ は軽減税率対象商品です。」表示判断を追加
  src/Eccube/Resource/template/default/Mail/order.html.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mypage/history.twig
  src/Eccube/Resource/template/default/Shopping/confirm.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
  src/Eccube/Service/OrderPdfService.php
Labels: Status: ready-for-merge, affected:plugin, improvement

#4429 他のディレクトリに合わせて .htaccess を追加
  .github/.htaccess
  var/.htaccess
Labels: Status: ready-for-merge, improvement

#4425 READMEのnpmコマンドの間違いを修正
  README.md
Labels: Status: ready-for-merge, documentation

#4459 Dockerfileを軽量化。レイヤを減らしてビルド速度を改善。
  Dockerfile
Labels: Status: ready-for-merge, improvement

#4471 remove ShoppingType.php
  src/Eccube/Form/Type/ShoppingType.php
Labels: bug:Low

#4454 sprintf()の引数が足りず正しくエラーが出力されなかったので修正
  src/Eccube/Doctrine/Common/CsvDataFixtures/Loader.php
Labels: Status: ready-for-merge, bug:Low

#4460 管理機能-受注一覧 : CSV出力を行っても「出荷ID」が見つからないがおそらく「配送ID」がそれであるためCSVヘッダータイトルデータを修正.
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_csv.csv
Labels: Status: ready-for-merge, bug:Low

#4396 Composer update
  .travis.yml
  app/config/eccube/packages/dev/doctrine.yaml
  app/config/eccube/packages/test/doctrine.yaml
  composer.json
  composer.lock
  src/Eccube/Controller/ShoppingController.php
  symfony.lock
  tests/Eccube/Tests/Doctrine/ORM/Tools/PaginationTest.php
Labels: Status: ready-for-merge, improvement

#4474 API: GraphQLとOAuth2.0の実装
  .env.dist
  .travis.yml
  README.md
  app/config/eccube/bundles.php
  app/config/eccube/packages/nyholm_psr7.yaml
  app/config/eccube/packages/security.yaml
  app/config/eccube/packages/trikoder_oauth2.yaml
  app/config/eccube/routes/trikoder_oauth2.yaml
  app/config/eccube/services.yaml
  appveyor.yml
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Eccube/Controller/Admin/OAuth2/OAuth2Controller.php
  src/Eccube/Controller/ApiController.php
  src/Eccube/DependencyInjection/EccubeExtension.php
  src/Eccube/EventListener/AuthorizationRequestResolveListener.php
  src/Eccube/EventListener/UserResolveListener.php
  src/Eccube/Form/Type/Admin/OAuth2AuthorizationType.php
  src/Eccube/GraphQL/Types.php
  src/Eccube/Resource/template/admin/OAuth2/authorization.twig
  src/Eccube/Security/Core/Encoder/UserPasswordEncoder.php
  symfony.lock
  tests/Eccube/Tests/Web/Admin/LoginControllerTest.php
  tests/Eccube/Tests/Web/Admin/OAuth2/OAuth2ControllerTest.php
Labels: Status: discussion, Status: needs-review, affected:外部仕様, enhancement, experimental
