Repository EC-CUBE/ec-cube, pull requests merged in 2020-12, with the labels that each got.

#4433 ページ管理の編集対象に会員登録(確認ページ)を加える #4428
  app/DoctrineMigrations/Version20201127000000.php
  src/Eccube/Controller/Admin/Content/LayoutController.php
  src/Eccube/Controller/Admin/Content/PageController.php
  src/Eccube/Controller/ContactController.php
  src/Eccube/Controller/EntryController.php
  src/Eccube/Controller/Mypage/WithdrawController.php
  src/Eccube/Entity/Page.php
  src/Eccube/Form/Type/Admin/MainEditType.php
  src/Eccube/Repository/PageRepository.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_page.csv
  src/Eccube/Resource/doctrine/import_csv/en/dtb_page_layout.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_page.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_page_layout.csv
  src/Eccube/Resource/template/admin/Content/page_edit.twig
Labels: Status: needs-review, affected:admin_template, enhancement

#4782 package-api-41beta.ec-cube.net 作りました。
  app/config/eccube/packages/eccube.yaml
Labels: experimental

#4787 eccube:install コマンドでプラグインの有効処理を追加
  src/Eccube/Command/InstallerCommand.php
  src/Eccube/Command/PluginCommandTrait.php
Labels: experimental

#4784 [4.1] Web API プラグインが初期インストールされるようにパッケージングスクリプトを更新
  .github/workflows/deploy.yml
Labels: experimental

#4786 [4.1] EC-CUBEインストール時にAjaxでプラグインを有効化する
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Controller/InstallPluginController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/install/complete.twig
  src/Eccube/Resource/template/install/frame.twig
Labels: experimental

#4783 機種依存文字が文字化けする不具合を修正
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Controller/Admin/AbstractCsvImportController.php
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: bug:Low

#4791 [4.1] バージョンを4.1-betaに更新
  src/Eccube/Common/Constant.php
Labels: experimental

#4778 CSVで商品規格を登録時に任意の項目がない場合のエラーを修正
  src/Eccube/Controller/Admin/Product/CsvImportController.php
Labels: bug:Middle

#4805 商品CSVの分割アップロード
  app/config/eccube/packages/eccube.yaml
  codeception/_support/Page/Admin/ProductCsvUploadPage.php
  codeception/acceptance/EA03ProductCest.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Form/Type/Admin/CsvImportType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Product/csv_product.twig
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: improvement

#4711 Entity拡張時にオリジナルのファイルを優先して参照するよう変更
  src/Eccube/Service/EntityProxyService.php
  tests/Eccube/Tests/Service/EntityProxyServiceTest.php
Labels: bug

#4720 マスタEntityでclass_existsをチェックするよう変更
  src/Eccube/Entity/Master/Authority.php
  src/Eccube/Entity/Master/Country.php
  src/Eccube/Entity/Master/CsvType.php
  src/Eccube/Entity/Master/CustomerOrderStatus.php
  src/Eccube/Entity/Master/CustomerStatus.php
  src/Eccube/Entity/Master/DeviceType.php
  src/Eccube/Entity/Master/Job.php
  src/Eccube/Entity/Master/OrderItemType.php
  src/Eccube/Entity/Master/OrderStatus.php
  src/Eccube/Entity/Master/OrderStatusColor.php
  src/Eccube/Entity/Master/PageMax.php
  src/Eccube/Entity/Master/Pref.php
  src/Eccube/Entity/Master/ProductListMax.php
  src/Eccube/Entity/Master/ProductListOrderBy.php
  src/Eccube/Entity/Master/ProductStatus.php
  src/Eccube/Entity/Master/RoundingType.php
  src/Eccube/Entity/Master/SaleType.php
  src/Eccube/Entity/Master/Sex.php
  src/Eccube/Entity/Master/TaxDisplayType.php
  src/Eccube/Entity/Master/TaxType.php
  src/Eccube/Entity/Master/Work.php
Labels: improvement

#4804 会員CSVダウンロード項目にポイントを追加
  app/DoctrineMigrations/Version20201218044542.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_csv.csv
Labels: Status: ready-for-merge, improvement

#4739 htmlメールを出力する際に、ディレクトリ名などに「.」が含まれていたら正常に出力されない不具合修正
  src/Eccube/Controller/Admin/Setting/Shop/MailController.php
Labels: Status: ready-for-merge, bug:Low

#4799 定義されていない不要なメッセージ出力を削除
  src/Eccube/Controller/Mypage/DeliveryController.php
  tests/Eccube/Tests/Web/Mypage/DeliveryControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4753 Dockerリビルド時の効率改善
  Dockerfile
Labels: improvement

#4800 管理画面のデザイン修正
  src/Eccube/Resource/template/admin/Setting/Shop/mail.twig
  src/Eccube/Resource/template/admin/Setting/Shop/tax_rule.twig
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
Labels: affected:admin_template

#4806 composerのミラー設定とhirak/prestissimoが効いていないのを修正
  Dockerfile
Labels: improvement

#4485 管理画面ダッシュボードの売り上げ状況をイベントでのカスタマイズした際の、数値とグラフの集計ロジックを合わせる
  src/Eccube/Controller/Admin/AdminController.php
Labels: affected:plugin, improvement

#4789 価格、カートボタンの文言をtextからhtmlに変更
  html/template/default/assets/js/eccube.js
  src/Eccube/Twig/Extension/EccubeExtension.php
  tests/Eccube/Tests/Twig/Extension/EccubeExtensionTest.php
Labels: Status: ready-for-merge, affected:template, improvement

#4756 永続化されたカートとセッションのカートが同一の場合はマージしない
  src/Eccube/Service/CartService.php
Labels: Status: fix-me, bug:Middle

#4810 composer2だとprestissimoはエラーになる
  Dockerfile
Labels: Status: ready-for-merge, improvement

#4813 [4.1] Apply composer update "symfony/*"
  composer.lock
  symfony.lock
Labels: Status: ready-for-merge, dependencies, improvement
