Repository EC-CUBE/ec-cube, pull requests merged in 2020-03, with the labels that each got.

#4343 仮会員が無効の場合、会員登録完了後直ぐにブラウザが閉じられたり通信が途絶えたりすると、仮会員として作成されてしまう不具合修正
  src/Eccube/Controller/EntryController.php
Labels: Status: needs-review, bug:Low

#4220 タイポの修正
  html/template/admin/assets/css/maps/app.css.map
  html/template/admin/assets/css/maps/app.min.css.map
  html/template/admin/assets/css/maps/bootstrap.css.map
  html/template/admin/assets/css/maps/bootstrap.min.css.map
  html/template/admin/assets/css/maps/tempusdominus-bootstrap-4.min.css.map
  html/template/admin/assets/css/tempusdominus-bootstrap-4.min.css
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/maps/style.min.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_12.2.eyecatch.scss
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/Block/eyecatch.twig
Labels: Status: needs-review, affected:template, bug:Low

#4354 iOSでformパーツを選択したときに画面が拡大する問題を修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/mixins/_forms.scss
  html/template/default/assets/scss/project/_11.2.header.scss
Labels: Status: ready-for-merge

#4357 iphoneでdrawerボタンのアイコンが上に寄っているのを修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_11.2.header.scss
Labels: Status: ready-for-merge

#4362 Change the way how dispatch template event
  app/config/eccube/packages/twig.yaml
  src/Eccube/DependencyInjection/Compiler/TemplateListenerPass.php
  src/Eccube/Kernel.php
  src/Eccube/Twig/Environment.php
  src/Eccube/Twig/Extension/TwigIncludeExtension.php
  src/Eccube/Twig/Template.php
  tests/Eccube/Tests/Web/TemplateEventListenerTest.php
Labels: Status: ready-for-merge

#4383 EditorConfig の対応
  .editorconfig
  .github/workflows/action.yml
Labels: improvement

#4400 Fix #4209　商品の在庫数が足りないときに受注のステータスを「注文取消し」から「対応中」に変更しすると、システムエラーが発生する不具合を修正
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Service/PurchaseFlow/Processor/StockDiffProcessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/StockDiffProcessorTest.php
Labels: bug:Low

#4410 ログの安全性向上
  src/Eccube/Log/Processor/SessionProcessor.php
Labels: affected:外部仕様, improvement

#4404 BrowserSyncのnpm scriptを一般的なコマンド名に変更
  gulpfile.js
  package.json
Labels: Status: ready-for-merge, improvement

#4405 unsignedが設定されているためお取り寄せ(商品入荷後)が機能していない
  app/DoctrineMigrations/Version20200303053716.php
  src/Eccube/Entity/DeliveryDuration.php
  tests/Eccube/Tests/Entity/DeliveryDurationTest.php
Labels: Status: ready-for-merge, bug:Low

#4422 管理画面商品一覧で在庫なしの絞り込み結果修正
  src/Eccube/Controller/Admin/AdminController.php
  src/Eccube/Repository/ProductRepository.php
Labels: bug:Low

#4415 Nginx用設定ファイルのサンプル追加
  .htaccess
  nginx.conf.sample
Labels: Status: ready-for-merge, improvement

#4423 会員登録でポイント数が入力されていない場合0を登録
  src/Eccube/Form/Type/Admin/CustomerType.php
Labels: bug:Low

#4414 PHP7.4対応
  .github/workflows/action.yml
  .travis.yml
  codeception/_support/Page/Admin/PluginManagePage.php
  codeception/_support/Page/Admin/PluginStoreInstallPage.php
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Form/Type/AddCartType.php
  src/Eccube/Form/Type/Admin/PluginLocalInstallType.php
  src/Eccube/Form/Type/Admin/PluginManagementType.php
  src/Eccube/Form/Type/Admin/TemplateType.php
  src/Eccube/Repository/AbstractRepository.php
  src/Eccube/Service/Composer/ComposerProcessService.php
  tests/Eccube/Tests/Util/StringUtilTest.php
Labels: enhancement

#4432 タグ管理画面にエンティティ拡張の自動出力を追加
  src/Eccube/Resource/template/admin/Product/tag.twig
Labels: Status: ready-for-merge, affected:admin_template, enhancement

#4434 規格選択時規格名と管理名の両方を表示する
  src/Eccube/Form/Type/Admin/ProductClassMatrixType.php
Labels: Status: ready-for-merge, improvement

#4436 4xx系のエラーログ出力レベルINFOに修正
  src/Eccube/EventListener/ExceptionListener.php
Labels: Status: needs-review, improvement

#4437 会員編集画面で表示の色分けはmtb_order_status_colorを使用するように変更する
  src/Eccube/Resource/template/admin/Customer/edit.twig
Labels: Status: needs-review, affected:admin_template, bug:Low

#4431 Basic認証をかけた場合、Google Chrome79でアクセスすると真っ白の画面となる問題に対応
  app/config/eccube/packages/security.yaml
  tests/Eccube/Tests/Web/Admin/LoginControllerTest.php
Labels: improvement

#4439 [fix]refs #4316 CLIインストール時、管理画面URLがadminに固定されてしまう状況の解消
  src/Eccube/Command/InstallerCommand.php
Labels: improvement

#4464 Docker Compose環境利用時に、DBにSQLiteを利用すると書込権限がなくエラーとなる問題に対処.
  .dockerignore
  Dockerfile
Labels: Status: needs-review, bug:Low

#4442 【EC-CUBE4】会員登録時にIDとパスワードは同じものを使用出来ない様にする #4248
  src/Eccube/Form/Type/Admin/CustomerType.php
  src/Eccube/Form/Type/Front/EntryType.php
  src/Eccube/Form/Type/Front/PasswordResetType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Form/Type/Admin/CustomerTypeTest.php
  tests/Eccube/Tests/Form/Type/Front/EntryTypeTest.php
  tests/Eccube/Tests/Form/Type/Front/PasswordResetTypeTest.php
Labels: Status: ready-for-merge, improvement

#4462 プラグインの有効無効判定時にDBALの定義を作成しないように修正
  src/Eccube/DependencyInjection/EccubeExtension.php
Labels: Status: ready-for-merge, bug:Low
