Repository EC-CUBE/ec-cube, pull requests merged in 2020-05, with the labels that each got.

#4524 PHP7.4 で notice が発生して再インストールできないのを修正
  src/Eccube/DependencyInjection/EccubeExtension.php
Labels: Status: ready-for-merge

#4526 店舗設定・税率設定の適用日時エラー文を追加
  src/Eccube/Form/Type/Admin/TaxRuleType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: ready-for-merge, bug:Low

#4538 カテゴリ編集フォームでファイルを送信できるようにする
  src/Eccube/Resource/template/admin/Product/category.twig
Labels: Status: ready-for-merge, affected:template, improvement

#4535 Docker container に vim を追加
  Dockerfile
Labels: Status: ready-for-merge

#4483 eccube:composer:require-already-installedコマンドで404エラーが発生するのを修正
  src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
  src/Eccube/Service/PluginService.php
  tests/Eccube/Tests/Service/PluginServiceTest.php
Labels: Status: ready-for-merge, bug:High

#4530 キャッシュ削除後、デバッグツールバーでエラーが発生する問題を修正
  src/Eccube/Twig/Template.php
Labels: bug:High
