Repository EC-CUBE/ec-cube, pull requests merged in 2020-10, with the labels that each got.

#4714 Replace reference to unknown Exception
  src/Eccube/DataCollector/EccubeDataCollector.php
Labels: Status: ready-for-merge, bug:Low

#4715 Remove incorrect extra argument from log_error() calls
  src/Eccube/Controller/Admin/Customer/CustomerController.php
  src/Eccube/Controller/Admin/Customer/CustomerDeliveryEditController.php
Labels: Status: ready-for-merge, bug:Low

#4722 [Symfony4.4] Doctrineのキャッシュをクリアできるように修正
  src/Eccube/Util/CacheUtil.php
Labels: improvement

#4728 Entity Proxy をプログラム内で動的に変更した場合にエラーにならないように修正
  src/Eccube/Kernel.php
Labels: bug:Middle

#4730 Set cookie lifetime on test
  app/config/eccube/packages/test/framework.yaml
Labels: improvement

#4717 納品書の送料が２つ表示される問題を修正
  src/Eccube/Service/OrderPdfService.php
Labels: Status: ready-for-merge, improvement

#4731 AbstractRepository::save() のタイプヒント（アノテーション）の誤りを修正
  src/Eccube/Repository/AbstractRepository.php
Labels: Status: ready-for-merge, improvement

#4695 受注登録画面の商品検索で発生することがあるエラーを修正
  src/Eccube/Controller/Admin/Order/EditController.php
Labels: Status: ready-for-merge, bug:Middle

#4694 OWASP ZAP 連携用の docker-compose を追加
  .github/workflows/deploy.yml
  .htaccess
  docker-compose-owaspzap.yml
  zap/.gitignore
  zap/.htaccess
  zap/Dockerfile
  zap/README.md
  zap/admin.context
  zap/containing_urls.txt
  zap/front_guest.context
  zap/front_login.context
  zap/options.properties
  zap/selenium/ide/Manual_Inspection.side
  zap/selenium/ide/Manual_Inspection_Admin.side
  zap/selenium/ide/README.md
Labels: Status: ready-for-merge, enhancement

#4713 app/template/smartphone のgit管理
  .gitignore
  app/template/smartphone/.gitkeep
Labels: Status: ready-for-merge, improvement

#4736 納品書に会社名を出力するように対応
  src/Eccube/Service/OrderPdfService.php
Labels: Status: ready-for-merge, improvement

#4724 [Symfony4.4] Composer2 update
  .github/workflows/plugin-test.yml
  .travis.yml
  codeception/_data/plugins/Assets-1.0.0.tgz
  codeception/_data/plugins/Assets-1.0.1.tgz
  codeception/_data/plugins/Boomerang-1.0.0.tgz
  codeception/_data/plugins/Boomerang10-1.0.0.tgz
  codeception/_data/plugins/Bundle-1.0.0.tgz
  codeception/_data/plugins/Bundle-1.0.1.tgz
  codeception/_data/plugins/Emperor-1.0.0.tgz
  codeception/_data/plugins/Emperor-1.0.1.tgz
  codeception/_data/plugins/Horizon-1.0.0.tgz
  codeception/_data/plugins/Horizon-1.0.1.tgz
  codeception/_data/plugins/InstallError.tgz
  codeception/_data/plugins/Template-1.0.0.tgz
  composer.json
  composer.lock
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Repository/PluginRepository.php
  src/Eccube/Service/PluginService.php
  symfony.lock
  tests/Eccube/Tests/Repository/PluginRepositoryTest.php
Labels: Status: ready-for-merge, experimental

#4746 Dockerfile は Composer1 に固定
  .github/workflows/deploy.yml
  .github/workflows/e2e-test.yml
  .github/workflows/plugin-test.yml
  .github/workflows/unit-test.yml
  .travis.yml
  Dockerfile
  appveyor.yml
Labels: Status: ready-for-merge, improvement

#4751 会員一覧 購入商品検索で購入処理中・決済処理中を除外 #4735
  src/Eccube/Repository/CustomerRepository.php
  tests/Eccube/Tests/Web/Admin/Customer/CustomerControllerTest.php
Labels: Status: ready-for-merge, improvement

#4755 GitHub Actions を Composer1 に固定
  .github/workflows/plugin-test.yml
Labels: improvement
