Repository EC-CUBE/ec-cube, pull requests merged in 2020-07, with the labels that each got.

#4499 メール設定画面でメール本文を修正しても反映されない不具合修正
  src/Eccube/Controller/Admin/Setting/Shop/MailController.php
Labels: Status: ready-for-merge, bug:Low

#4472 fix save and close btn in admin/shipping, /admin/product/product/new,…
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: Status: ready-for-merge, affected:admin_template, bug:Low

#4605 商品名に「'」が入ると受注管理で商品を追加できない不具合の修正
  src/Eccube/Resource/template/admin/Order/search_product.twig
Labels: Status: ready-for-merge, bug:Low

#4598 SSL接続状態でインストールするとデフォルトで強制SSLを有効にする
  src/Eccube/Resource/template/install/step3.twig
Labels: Status: ready-for-merge, improvement

#4608 docker buildでエラーが出るので対処
  Dockerfile
Labels: Status: ready-for-merge, bug:Low

#4596 Symfony4.4対応
  app/config/eccube/services.yaml
  composer.lock
  phpunit.xml.dist
  symfony.lock
  tests/Eccube/Tests/Entity/DeliveryDurationTest.php
  tests/Eccube/Tests/Service/PluginServiceTest.php
  tests/Eccube/Tests/Web/AbstractWebTestCase.php
  tests/Eccube/Tests/Web/Admin/Product/CategoryContorllerTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithMultipleNonmemberTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithNonmemberTest.php
  tests/Eccube/Tests/Web/TemplateEventListenerTest.php
Labels: Status: ready-for-merge, experimental

#4500 ログインに失敗しても設定されている戻り先URLへ正常に遷移するように対応
  src/Eccube/Resource/template/default/Mypage/login.twig
Labels: Status: ready-for-merge:ok_hand:, bug:Low

#4625 Remove extra tables
  src/Eccube/Command/ComposerRemoveCommand.php
  src/Eccube/Doctrine/ORM/Mapping/Driver/NopAnnotationDriver.php
  src/Eccube/Kernel.php
  src/Eccube/Service/Composer/ComposerApiService.php
  src/Eccube/Service/PluginContext.php
  src/Eccube/Service/PluginService.php
  src/Eccube/Service/SchemaService.php
  symfony.lock
Labels: enhancement

#4634 PHP 7.1.3を超えるバージョンを必要とするプラグインを安全にインストールできるようにする
  src/Eccube/Service/Composer/ComposerApiService.php
Labels: bug:Low, experimental:microscope:
