Repository EC-CUBE/ec-cube, pull requests merged in 2020-08, with the labels that each got.

#4631 カテゴリ４階層目で新規登録フォームが表示されなくなる(eccube_category_nest_level=5)
  src/Eccube/Resource/template/admin/Product/category.twig
Labels: bug:Low

#4641 PostgreSQL環境で発生する数値エラーの修正
  src/Eccube/Repository/AbstractRepository.php
  src/Eccube/Repository/CustomerRepository.php
  src/Eccube/Repository/OrderRepository.php
  src/Eccube/Repository/ProductRepository.php
  tests/Eccube/Tests/Repository/CustomerRepositoryTest.php
  tests/Eccube/Tests/Repository/OrderRepositoryTest.php
  tests/Eccube/Tests/Repository/ProductRepositoryTest.php
Labels: Status: ready-for-merge:ok_hand:, bug

#4468 fix #4466 「カートに追加しました」とメッセージが表示される不具合を修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_13.4.cartModal.scss
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: ready-for-merge:ok_hand:, affected:template:seedling:, bug:Low, css:stars:

#4465 管理画面トップ 売上状況が9時間ずれる問題修正
  src/Eccube/Controller/Admin/AdminController.php
  tests/Eccube/Tests/Web/Admin/IndexControllerTest.php
Labels: Status: ready-for-merge:ok_hand:, bug:Middle

#4663 管理画面トップのおすすめプラグインとお知らせの内容の高さを合わせました。
  src/Eccube/Resource/template/admin/index.twig
Labels: improvement:confetti_ball:

#4664 プラグインで Symfony Bundle を利用可能にする（experimental/plugin_bundle ブランチの取り込み）
  .github/workflows/action.yml
  codeception/_data/plugins/Bundle-1.0.0.tgz
  codeception/_data/plugins/Bundle-1.0.1.tgz
  codeception/acceptance/EA10PluginCest.php
  src/Eccube/Command/ComposerRemoveCommand.php
  src/Eccube/Doctrine/ORM/Mapping/Driver/NopAnnotationDriver.php
  src/Eccube/Kernel.php
  src/Eccube/Service/Composer/ComposerApiService.php
  src/Eccube/Service/PluginContext.php
  src/Eccube/Service/PluginService.php
  src/Eccube/Service/SchemaService.php
  symfony.lock
Labels: enhancement

#4658 VSCode Remote Containersの設定ファイルを追加
  .devcontainer/devcontainer.json
  .htaccess
  web.config
Labels: Status: ready-for-merge:ok_hand:, improvement:confetti_ball:

#4669 easycorp/easy-log-handler を必須ライブラリに変更
  composer.json
  composer.lock
Labels: bug, dependencies
