Repository EC-CUBE/ec-cube, pull requests merged in 2020-11, with the labels that each got.

#4726 UserProviderでCustomer/Memberのサブクラスもサポートする
  src/Eccube/Security/Core/User/CustomerProvider.php
  src/Eccube/Security/Core/User/MemberProvider.php
Labels: Status: ready-for-merge, bug:Middle

#4742 ブロック管理一覧画面でファイル名を表示するように対応
  src/Eccube/Resource/template/admin/Content/block.twig
Labels: Status: ready-for-merge, affected:admin_template, improvement

#4741 ページ管理一覧画面でルート名、URL、ファイル名を表示するように対応
  src/Eccube/Controller/Admin/Content/PageController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/page.twig
Labels: Status: ready-for-merge, affected:admin_template, improvement

#4743 郵便番号、電話番号の入力形式をTelTypeに変更
  src/Eccube/Form/Type/PhoneNumberType.php
  src/Eccube/Form/Type/PostalType.php
Labels: Status: ready-for-merge, affected:plugin, improvement

#4749 動作確認環境をシステム要件と実態に合わせて更新
  README.md
Labels: Status: ready-for-merge, document

#4719 プラグイン生成コマンドによって生成されるEntityでclass_existsをチェックするよう変更
  src/Eccube/Command/PluginGenerateCommand.php
Labels: Status: ready-for-merge, improvement

#4767 商品画像削除時、他の商品画像が参照するファイルは削除しないよう変更
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/ProductContorllerTest.php
Labels: Status: ready-for-merge, improvement

#4768 購入手続き中でもPurchaseContextでユーザー情報を取得できるようにする
  src/Eccube/Controller/ShippingMultipleController.php
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Service/PurchaseFlow/PurchaseContext.php
Labels: Status: ready-for-merge, improvement

#4750 [4.1] Remove @dev to composer.json
  composer.json
  composer.lock
Labels: improvement

#4766 Feature/#4716 管理者ページ-受注一覧における検索条件の修正
  src/Eccube/Repository/OrderRepository.php
  tests/Eccube/Tests/Repository/OrderRepositoryTest.php
Labels: Status: ready-for-merge, improvement

#4770 HTMLの属性maxlengthのtype修正
  src/Eccube/Form/Type/Admin/LoginType.php
  src/Eccube/Form/Type/Front/CustomerLoginType.php
  src/Eccube/Form/Type/Front/ForgotType.php
  src/Eccube/Form/Type/Front/PasswordResetType.php
Labels: Status: ready-for-merge, bug:Low
