Repository EC-CUBE/ec-cube, pull requests merged in 2020-09, with the labels that each got.

#4666 ログのダウンロード機能を追加
  src/Eccube/Controller/Admin/Setting/System/LogController.php
  src/Eccube/Form/Type/Admin/LogType.php
  src/Eccube/Resource/template/admin/Setting/System/log.twig
Labels: enhancement

#4677 注文確認メール（HTML）の見出しが本文と同じフォントサイズになっていたのを修正しました。
  src/Eccube/Resource/template/default/Mail/order.html.twig
Labels: improvement

#4661 pre-commit-hookでのphp-cs-fixerの実行
  package-lock.json
  package.json
Labels: Status: ready-for-merge, improvement

#4676 docker / docker-compose のコンテナでnodejsを利用できるようにする
  Dockerfile
  docker-compose.yml
Labels: Status: ready-for-merge, improvement

#4699 インストール時にプロダクションモードをデフォルトに変更
  .env.dist
  .env.install
  src/Eccube/Command/InstallerCommand.php
Labels: improvement

#4680 毎月1日にUnitTestが落ちる問題を修正
  tests/Eccube/Tests/Web/Admin/IndexControllerTest.php
Labels: bug:Low

#4672 受注編集ページ内での顧客検索のパラメータの条件を調整
  src/Eccube/Controller/Admin/Order/EditController.php
Labels: bug:Low

#4671 GitHub Actions が実行しやすいように jobs を分割
  .github/workflows/action.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e-test.yml
  .github/workflows/plugin-test.yml
  .github/workflows/unit-test.yml
Labels: improvement

#4665 OrderNoをTimeZoneの変更に対応
  src/Eccube/Service/PurchaseFlow/Processor/OrderNoProcessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/OrderNoProcessorTest.php
Labels: bug:Low

#4682 商品のmin|max集計でエラーが発生するのを修正
  src/Eccube/Entity/Product.php
  tests/Eccube/Tests/Entity/ProductTest.php
Labels: Status: ready-for-merge, bug:Low

#4685 WhereClauseでfalseとして評価されるパラメータを受け取れるよう変更
  src/Eccube/Doctrine/Query/WhereClause.php
  tests/Eccube/Tests/Doctrine/Query/WhereClauseTest.php
Labels: Status: ready-for-merge, affected:plugin, bug:Low

#4688 タグ削除エラー時のメッセージid修正
  src/Eccube/Controller/Admin/Product/TagController.php
Labels: Status: ready-for-merge, bug:Low

#4693 Change mailHistoryRepository access to protected
  src/Eccube/Service/MailService.php
Labels: Status: ready-for-merge, improvement

#4701 不必要に二重に呼び出されているコンタクトフォームの処理を削除
  src/Eccube/Controller/ContactController.php
Labels: Status: ready-for-merge, bug:Low

#4704 受注登録で商品追加時、規格が登録され全ての規格の在庫がゼロの時、JavaScriptエラーになるのを修正
  src/Eccube/Resource/template/admin/Order/search_product.twig
Labels: Status: ready-for-merge, affected:admin_template, bug:Low

#4709 管理画面の会員管理/お届け先登録で必須項目に マークをつける
  src/Eccube/Resource/template/admin/Customer/delivery_edit.twig
Labels: Status: ready-for-merge, affected:admin_template, improvement
