Repository EC-CUBE/ec-cube, pull requests merged in 2020-04, with the labels that each got.

#4503 .gitignoreにvscodeの設定ディレクトリを追加
  .gitignore
Labels: improvement

#4479 インストール直後の税率を8から10に変更。
  src/Eccube/Entity/TaxRule.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_tax_rule.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_tax_rule.csv
  tests/Eccube/Tests/Service/TaxRuleServiceTest.php
  tests/Eccube/Tests/Web/Admin/Order/ShippingControllerTest.php
Labels: Status: ready-for-merge

#4501 さくらサーバのOSバージョンアップに伴いX_SAKURA_FORWARDED_FORは不要になったため削除
  .htaccess
Labels: improvement

#4495 TemplateEventからTwigのコードが取れない不具合を修正
  src/Eccube/Twig/Template.php
Labels: bug:High

#4505 プラグインに Codeception を同梱できるよう修正
  app/config/eccube/services.yaml
Labels: improvement

#4514 ページ管理で作成されたファイルをignoreされないように修正
  .gitignore
Labels: improvement

#4506 apt-get install libicu-devでエラーが発生する問題を解消。（aptのリモートリポジトリとの相性が悪い）
  Dockerfile
Labels: bug:Low

#4512 エラーメッセージの表示位置を変更
  src/Eccube/Resource/template/admin/Content/file.twig
Labels: bug:Low

#4490 【fix】受注登録画面の利用ポイント(use_point)フォームのバリデーションをrequire=trueに修正
  src/Eccube/Form/Type/Admin/OrderType.php
Labels: bug:Low

#4452 注文手続き中に税率が変更された場合の反映
  src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/TaxProcessorTest.php
Labels: Status: ready-for-merge, improvement

#4511 エラーメッセージの文言変更と説明文の記述ミスの修正
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: improvement

#4513 注文ステップだけでなく、注文履歴でも注文概要ボックスをスクロールするよう修正
  html/template/default/assets/js/function.js
Labels: improvement

#4496 Customizeディレクトリでもservices.yamlが定義できるように機能拡張
  app/Customize/Resource/config/.gitkeep
  src/Eccube/Kernel.php
Labels: enhancement

#4518 ref #3975 pathの追加
  app/Customize/Resource/locale/.gitkeep
  app/config/eccube/packages/translation.yaml
Labels: Status: ready-for-merge, improvement
