Repository EC-CUBE/ec-cube, pull requests merged in 2020-06, with the labels that each got.

#4548 Webインストーラで画面遷移できないのを修正
  src/Eccube/DependencyInjection/EccubeExtension.php
Labels: bug:Critical

#4570 CSS生成時に normalize.css がインライン化されるように修正
  gulpfile.js
  html/template/admin/assets/css/app.css
  html/template/admin/assets/css/app.css.map
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/style.scss
  package-lock.json
  package.json
Labels: bug:Middle, css

#4572 NativeFileSessionHandlerの引数へSessionのsave_pathを設定
  app/config/eccube/services.yaml
Labels: bug:High

#4575 管理画面の商品画像登録処理の改善
  src/Eccube/Form/Type/Admin/ProductType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: improvement

#4566 不要なコメントを削除
  src/Eccube/DependencyInjection/EccubeExtension.php
Labels: bug:Low

#4563 大きなサイズのCSVを扱えるようタイムアウトを延長
  src/Eccube/Doctrine/Common/CsvDataFixtures/CsvFixture.php
Labels: improvement

#4581 プラグインの雛形を作るときに release.yml も同梱する
  src/Eccube/Command/PluginGenerateCommand.php
Labels: Status: ready-for-merge, improvement

#4573 session.save_path のテストを追加
  codeception/acceptance/EA08SysteminfoCest.php
Labels: Status: ready-for-merge

#4531 商品の公開ステータスや課税区分などにコメントを追加
  src/Eccube/Entity/Master/OrderItemType.php
  src/Eccube/Entity/Master/ProductStatus.php
  src/Eccube/Entity/Master/TaxDisplayType.php
  src/Eccube/Entity/Master/TaxType.php
Labels: documentation

#4585 composer update
  composer.lock
  symfony.lock
Labels: Status: ready-for-merge, dependencies

#4593 user_data 直下の .gitkeep は不要なので削除
  html/user_data/.gitkeep
Labels: improvement

#4588 複数配送時に在庫数が減らない不具合を修正
  src/Eccube/Service/PurchaseFlow/Processor/StockReduceProcessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/StockReduceProcessorTest.php
Labels: Status: ready-for-merge, bug:High

#4527 プラグインのテンプレートを上書きできるように対応
  app/template/plugin/.gitkeep
  codeception/_data/plugins/Template-1.0.0.tgz
  codeception/_support/Page/Admin/CacheManagePage.php
  codeception/acceptance/EA10PluginCest.php
  src/Eccube/DependencyInjection/EccubeExtension.php
Labels: Status: ready-for-merge, documentation, enhancement

#4591 .editorconfigへのアクセスを制限
  .htaccess
  web.config
Labels: Status: ready-for-merge, bug:Low

#4599 レイアウト削除失敗時のメッセージを適切に変更
  src/Eccube/Controller/Admin/Content/LayoutController.php
  tests/Eccube/Tests/Web/Admin/Content/LayoutControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#4597 ページ管理：商品詳細のmetaタグの `product:retailer_title` を店舗名に変更
  src/Eccube/Resource/doctrine/import_csv/en/dtb_page.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_page.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug:Low

#4523 Gulpをタスクごとにファイルを分割
  .gitignore
  .htaccess
  gulp/build/build.js
  gulp/build/start.js
  gulp/config.js
  gulp/task/scss-min.js
  gulp/task/scss.js
  gulp/task/server.js
  gulpconfig.js.sample
  gulpfile.js
  html/template/admin/assets/css/maps/app.css.map
  html/template/admin/assets/css/maps/app.min.css.map
  html/template/admin/assets/css/maps/bootstrap.css.map
  html/template/admin/assets/css/maps/bootstrap.min.css.map
  html/template/admin/assets/css/maps/tempusdominus-bootstrap-4.min.css.map
  html/template/default/assets/css/maps/style.css.map
  html/template/default/assets/css/maps/style.min.css.map
  package.json
  web.config
Labels: improvement

#4580 Windowsでscssのコンパイル先のパスを修正しました。macとwindows両方で動きます。
  gulp/task/scss-min.js
  gulp/task/scss.js
Labels: Status: ready-for-merge, bug:Low
