Repository EC-CUBE/ec-cube, pull requests merged in 2021-11, with the labels that each got.

#5201 開発用コンテナでプラグインインストール時に発生する証明書エラーの対応
  Dockerfile
Labels: bug:Low

#4997 受注編集時にすでに受注にセットされている顧客情報を書き換えない
  src/Eccube/Form/Type/Admin/OrderType.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#5030 受注管理画面：表示項目「出荷ID」の追加
  src/Eccube/Resource/template/admin/Order/index.twig
Labels: enhancement, Status: ready-for-merge

#5066 重複したステートメントを削除
  src/Eccube/Service/OrderHelper.php
Labels: Status: ready-for-merge, bug:Low

#5179 パッケージから docker-composer.owaspzap.daemon.yml を削除
  package.sh
Labels: bug:Low

#5183 OWASP ZAP 自動化手順の README 追加
  zap/selenium/ci/TypeScript/README.md
Labels: document

#5012 PULL_REQUEST_TEMPLATE の修正
  .github/PULL_REQUEST_TEMPLATE.md
Labels: improvement

#5213 受注登録でお届け先に氏名が表示されない #4980
  src/Eccube/Resource/template/admin/Order/edit.twig
Labels: bug:Low

#5209 fixed タグ管理の項目追加の自動表示位置が誤り #4981
  src/Eccube/Resource/template/admin/Product/tag.twig
Labels: affected:admin_template, improvement

#5182 SQLite3 使用時、SiteKit, GMC プラグインはインストーラの有効化ボタンを表示しないよう修正
  src/Eccube/Resource/template/install/complete.twig
Labels: improvement

#5218 ユニットテストのPHPバージョンをシステム要件に合わせる
  .github/workflows/unit-test.yml
Labels: improvement

#5026 PHP7.4, PostgreSQL14 で GitHub Actions を実行する
  .github/workflows/coverage.yml
  .github/workflows/deny-test.yml
  .github/workflows/deploy.yml
  .github/workflows/dockerbuild.yml
  .github/workflows/e2e-bc-test.yml
  .github/workflows/e2e-test.yml
  .github/workflows/plugin-test.yml
  .github/workflows/unit-test.yml
  .github/workflows/vaddy-1.yml
  .github/workflows/vaddy-2.yml
Labels: Status: ready-for-merge, improvement

#5045 利用されていないコードを削除
  src/Eccube/Controller/Admin/Order/MailController.php
  src/Eccube/Event/EccubeEvents.php
  src/Eccube/Resource/template/admin/Order/mail_view.twig
  tests/Eccube/Tests/Web/Admin/Order/MailControllerTest.php
Labels: Status: ready-for-merge, improvement

#5204 Cart.php内でthis返却の実装漏れを修正
  src/Eccube/Entity/Cart.php
Labels: improvement

#5195 classcategory_name2が重複しているため不要な記述を削除
  src/Eccube/Resource/template/default/Mail/order.twig
Labels: Status: ready-for-merge, bug:Low

#5197 ページ管理のmetatagの文字数制限の修正
  src/Eccube/Form/Type/Admin/MainEditType.php
  tests/Eccube/Tests/Form/Type/Admin/MainEditTypeTest.php
Labels: Status: ready-for-merge, bug:Low

#5190 gulp-sass v5に対応
  gulp/task/scss-min.js
  gulp/task/scss.js
  package-lock.json
  package.json
Labels: Status: ready-for-merge, bug:Low

#5056 Form/Type/Admin/OrderTypeの「company_name」が重複していたので片方を削除
  src/Eccube/Form/Type/Admin/OrderType.php
Labels: Status: ready-for-merge, bug:Low

#4990 Generator で Product 作成時に ProductTag もセットする
  app/config/eccube/packages/codeception/generator.yaml
  app/config/eccube/packages/dev/generator.yaml
  app/config/eccube/packages/test/generator.yaml
  tests/Eccube/Tests/Doctrine/ORM/Tools/PaginationTest.php
  tests/Eccube/Tests/Fixture/Generator.php
  tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataTest.php
  tests/Eccube/Tests/Web/CartValidationTest.php
Labels: Status: ready-for-merge, improvement

#4903 商品一覧・編集画面の規格情報並び順をsort_noで制御
  src/Eccube/Controller/Admin/Product/ProductController.php
Labels: Status: ready-for-merge, bug:Low

#5220 Docker のPHPバージョン、 DATABASE_SERVER_VERSION を修正
  Dockerfile
  docker-compose.mysql.yml
  docker-compose.pgsql.yml
Labels: improvement

#4975 管理画面 商品のタグによる絞り込み
  src/Eccube/Form/Type/Admin/SearchProductType.php
  src/Eccube/Repository/ProductRepository.php
  src/Eccube/Resource/template/admin/Product/index.twig
  tests/Eccube/Tests/Repository/AbstractProductRepositoryTestCase.php
  tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataAdminTest.php
Labels: enhancement, Status: ready-for-merge

#5011 .dockerignore に bin/.phpunit と node_modules を追加
  .dockerignore
Labels: improvement

#5205 Fixed 基本設定画面のgood_tradedとmessageの文字数制限の修正 #5193
  src/Eccube/Form/Type/Admin/ShopMasterType.php
  tests/Eccube/Tests/Form/Type/Admin/ShopMasterTypeTest.php
Labels: Status: ready-for-merge, bug:Low

#5227 カートエンティティのgetCustomerの戻り値をnullableにする
  src/Eccube/Entity/Cart.php
Labels: bug:Low

#5238 テストコードの修正
  tests/Eccube/Tests/Repository/AbstractProductRepositoryTestCase.php
  tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataAdminTest.php
Labels: bug:Low

#5239 Undefined offset: 0 で E2Eテストが止まっていたのを修正
  codeception/acceptance/EA04OrderCest.php
Labels: bug:Low

#5237 カバレッジ出力に pcov を使用する
  .github/workflows/coverage.yml
Labels: improvement

#5211 ItemValidatorでProductClassがvisibleかチェック
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Service/PurchaseFlow/Processor/ProductStatusValidator.php
  tests/Eccube/Tests/Service/CartServiceTest.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/ProductStatusValidatorTest.php
  tests/Eccube/Tests/Web/AbstractShoppingControllerTestCase.php
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithMultipleNonmemberTest.php
Labels: Status: ready-for-merge, bug:Middle

#5116 CartItem.setCart()内でthis返却の実装漏れを修正
  src/Eccube/Entity/CartItem.php
Labels: Status: ready-for-merge, bug:Low

#5146 Fixed/issue5111 サイトマップ 商品情報出力の際に、在庫切れ非表示オプションを有効にしても表示されるを改修
  src/Eccube/Controller/SitemapController.php
Labels: Status: ready-for-merge, bug:Low

#5189 docker-composeでビルド時にnodejsのインストールにコケる不具合の対応
  Dockerfile
Labels: Status: ready-for-merge, bug:Low

#5090 [4.1] eccube:plugin:generate コマンドを composer2 対応
  src/Eccube/Command/PluginGenerateCommand.php
Labels: Status: ready-for-merge, improvement

#5174 データベースが常にsqliteになってしまって動かない不具合の修正
  src/Eccube/Command/InstallerCommand.php
Labels: Status: ready-for-merge, bug:Low

#4977 Facade クラスの不要な処理を修正
  src/Eccube/DependencyInjection/Facade/AnnotationReaderFacade.php
  src/Eccube/DependencyInjection/Facade/LoggerFacade.php
  src/Eccube/DependencyInjection/Facade/TranslatorFacade.php
  src/Eccube/Kernel.php
  src/Eccube/Resource/functions/log.php
Labels: Status: ready-for-merge, bug:Low

#5024 スマホとかで規格選択のセレクトボックスがはみ出る不具合の対応
  html/template/default/assets/css/style.css
  html/template/default/assets/scss/component/_3.2.inputMisc.scss
Labels: Status: ready-for-merge, bug:Low

#5208 検索エンジンにindexされてほしくないページにnoindexが設定されていない #5110
  app/DoctrineMigrations/Version20211111050712.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_page.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_page.csv
Labels: Status: ready-for-merge, bug:Low

#5236 バージョン番号を 4.1.1 に更新
  package-lock.json
  package.json
  src/Eccube/Common/Constant.php
Labels: Status: ready-for-merge

#5240 Apply composer update 'symfony/*'
  bin/phpunit
  composer.json
  composer.lock
  symfony.lock
Labels: Status: ready-for-merge, improvement

#5027 ファイル名のタイポ修正
  tests/Eccube/Tests/Web/Admin/Product/CategoryControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/ClassCategoryControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/ClassNameControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/ProductControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/TagControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#5234 お問い合わせ内容フォームラベルをform.contentsに修正
  src/Eccube/Resource/template/default/Contact/index.twig
Labels: bug:Low, affected:template

#5242 Basic認証サンプルの削除
  .htaccess
Labels: Status: ready-for-merge, improvement

#4974 定休日カレンダー機能を実装
  app/DoctrineMigrations/Version20210316120000.php
  app/config/eccube/packages/eccube_nav.yaml
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_12.9.calendar.scss
  html/template/default/assets/scss/style.scss
  src/Eccube/Controller/Admin/Setting/Shop/CalendarController.php
  src/Eccube/Controller/Block/CalendarController.php
  src/Eccube/Entity/Calendar.php
  src/Eccube/Form/Type/Admin/CalendarType.php
  src/Eccube/Repository/CalendarRepository.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_block.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_block.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/calendar.twig
  src/Eccube/Resource/template/default/Block/calendar.twig
  tests/Eccube/Tests/Form/Type/Admin/CalendarTypeTest.php
  tests/Eccube/Tests/Repository/CalendarRepositoryTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/CalendarControllerTest.php
  tests/Eccube/Tests/Web/Block/CalendarControllerTest.php
Labels: enhancement

#5228 購入確認画面での不明なspanの閉じタグを削除
  src/Eccube/Resource/template/default/Shopping/confirm.twig
Labels: bug:Low

#5230 ゲスト購入時、「ご注文手続き」の「お届け先を追加する」押下時にシステムエラーが発生する不具合の修正
  src/Eccube/Controller/NonMemberShoppingController.php
Labels: bug:High
