Repository EC-CUBE/ec-cube, pull requests merged in 2021-08, with the labels that each got.

#5100 利用していないルーティングの削除
  src/Eccube/Controller/Admin/Product/ProductController.php
Labels: improvement

#5097 skip や incomplete とマークされているテストの一部を修正
  codeception/acceptance/EA07BasicinfoCest.php
  codeception/acceptance/EA08SysteminfoCest.php
  codeception/acceptance/EF02ProductCest.php
  tests/Eccube/Tests/Command/PluginDevelopEntityFromDbTest.php
  tests/Eccube/Tests/Command/PluginDevelopEntityFromYamlTest.php
  tests/Eccube/Tests/Command/PluginDevelopGenerateTest.php
  tests/Eccube/Tests/Command/QuestionHelperMock.php
  tests/Eccube/Tests/EventListener/ForwardOnlyListenerTest.php
  tests/Eccube/Tests/Form/Type/Admin/LogTypeTest.php
  tests/Eccube/Tests/Form/Type/Install/Step4TypeTest.php
  tests/Eccube/Tests/Repository/AbstractRepositoryTestCase.php
  tests/Eccube/Tests/Service/EntityProxyServiceTest.php
  tests/Eccube/Tests/Service/MailServiceTest.php
  tests/Eccube/Tests/Service/Payment/PaymentMethodTest.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerWithMultipleTest.php
  tests/Eccube/Tests/Web/Admin/Order/OrderControllerTest.php
  tests/Eccube/Tests/Web/Mypage/MypageControllerTest.php
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
Labels: Status: ready-for-merge, improvement

#5102 4.0/4.1-feature/4.1-core ブランチの内容を 4.1 ブランチに取り込み
  src/Eccube/Controller/Admin/Content/CacheController.php
  src/Eccube/Controller/Admin/Content/MaintenanceController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Resource/template/admin/Content/cache.twig
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
  tests/Eccube/Tests/Web/Admin/Content/MaintenanceControllerTest.php
Labels: improvement

#5104 Webインストーラでのプラグイン有効化時にインストール処理を追加
  src/Eccube/Controller/InstallPluginController.php
Labels: improvement

#5105 php-cs-fixer を実行
  codeception/_support/Page/Admin/CategoryManagePage.php
  src/Eccube/Command/ComposerRemoveCommand.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Controller/Admin/Setting/System/TwoFactorAuthController.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Controller/InstallPluginController.php
  src/Eccube/Controller/SitemapController.php
  src/Eccube/EventListener/MaintenanceListener.php
  src/Eccube/EventListener/TwoFactorAuthListener.php
  src/Eccube/Form/EventListener/HTMLPurifierListener.php
  src/Eccube/Form/Extension/HTMLPurifierTextTypeExtension.php
  src/Eccube/Form/Type/Admin/TwoFactorAuthType.php
  src/Eccube/Service/SystemService.php
  src/Eccube/Service/TwoFactorAuthService.php
  tests/Eccube/Tests/Repository/AbstractProductRepositoryTestCase.php
  tests/Eccube/Tests/Web/ProductControllerTest.php
Labels: improvement

#5106 バージョンを 4.1-beta3 に変更
  package.json
  src/Eccube/Common/Constant.php
Labels: improvement

#5103 4.1beta3: パッケージに初期インストールプラグインを追加
  .github/workflows/deploy.yml
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Resource/doctrine/import_csv/en/dtb_plugin.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_plugin.csv
Labels: enhancement

#5112 意図しないディレクトリ・ファイル露出のテスト
  .github/workflows/deny-test.yml
  .github/workflows/deploy.yml
  codeception/acceptance/CL01DenyCest.php
  composer.json
  composer.lock
  package.sh
  symfony.lock
Labels: Status: ready-for-merge, improvement

#5118 4.1 beta3 ブランチの内容を取り込み
  .github/workflows/deny-test.yml
  .github/workflows/deploy.yml
  app/config/eccube/packages/eccube.yaml
  codeception/acceptance/CL01DenyCest.php
  composer.json
  composer.lock
  package.sh
  src/Eccube/Resource/doctrine/import_csv/en/dtb_plugin.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_plugin.csv
  symfony.lock
Labels: enhancement

#4970 EC-CUBE4.1でメンバーのパスワードが更新できないバグ修正
  codeception/acceptance/EA08SysteminfoCest.php
  src/Eccube/Controller/Admin/Setting/System/MemberController.php
  src/Eccube/Entity/Member.php
  src/Eccube/Form/Type/Admin/MemberType.php
  src/Eccube/Resource/template/admin/Setting/System/member_edit.twig
  tests/Eccube/Tests/Form/Type/Admin/MemberTypeTest.php
  tests/Eccube/Tests/Web/Admin/Setting/System/MemberControllerTest.php
Labels: Status: ready-for-merge, bug:Critical

#5010 ログイン履歴機能のマイグレーションを追加
  app/DoctrineMigrations/Version20210412073123.php
Labels: enhancement, Status: ready-for-merge

#5126 APIインストール時に生成される鍵をパッケージから削除
  package.sh
Labels: Status: ready-for-merge, bug:Critical

#5127 不要な.gitkeepを削除
  html/user_data/.gitkeep
Labels: Status: ready-for-merge, bug:Low

#5125 4.1-beta3 : 管理画面 ファイルアップロード UI の修正
  src/Eccube/Resource/template/admin/Form/bootstrap_4_horizontal_layout.html.twig
  src/Eccube/Resource/template/admin/Store/plugin_install.twig
  src/Eccube/Resource/template/admin/Store/plugin_table.twig
Labels: bug:Middle, affected:admin_template

#5130 受注CSVで、お届け時間IDが出力されない問題の修正
  app/DoctrineMigrations/Version20210831190000.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_csv.csv
Labels: bug:Low
