Repository EC-CUBE/ec-cube, pull requests merged in 2021-04, with the labels that each got.

#5003 docker-compose.owaspzap.yml のファイル名変更に伴う修正漏れ
  .github/workflows/deploy.yml
Labels: Status: ready-for-merge, bug:Low

#5002 4.1-beta2 への機能取り込み
  app/DoctrineMigrations/Version20210401120000.php
  app/config/eccube/packages/security.yaml
  app/config/eccube/services.yaml
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_11.2.header.scss
  index.php
  src/Eccube/Controller/Admin/Content/MaintenanceController.php
  src/Eccube/Controller/SitemapController.php
  src/Eccube/EventListener/MaintenanceListener.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Form/Type/Admin/SearchProductType.php
  src/Eccube/Repository/ProductRepository.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_page.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_page.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Content/page_edit.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Resource/template/default/meta.twig
  src/Eccube/Resource/template/default/sitemap.xml.twig
  src/Eccube/Resource/template/default/sitemap_index.xml.twig
  src/Eccube/Security/Http/Authentication/EccubeLogoutSuccessHandler.php
  src/Eccube/Service/SystemService.php
  tests/Eccube/Tests/Repository/AbstractProductRepositoryTestCase.php
  tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataAdminTest.php
  tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataTest.php
  tests/Eccube/Tests/Web/ProductControllerTest.php
  tests/Eccube/Tests/Web/TopControllerTest.php
Labels: improvement

#5009 [4.1-beta2]マージ漏れ修正と docker build のテストを追加
  .github/workflows/dockerbuild.yml
  Dockerfile
  codeception/_envs/github_action_docker.yml
Labels: Status: ready-for-merge, improvement

#5001 Apply composer update to 4.1-core
  codeception/acceptance/EA04OrderCest.php
  codeception/acceptance/EA05CustomerCest.php
  codeception/acceptance/EF03OrderCest.php
  codeception/acceptance/EF04CustomerCest.php
  codeception/acceptance/EF06OtherCest.php
  composer.json
  composer.lock
  symfony.lock
  tests/Eccube/Tests/Web/Admin/Customer/CustomerControllerTest.php
  tests/Eccube/Tests/Web/Admin/Product/ProductContorllerTest.php
Labels: Status: ready-for-merge, improvement

#5008 バージョンを 4.1-beta2 に変更
  package.json
  src/Eccube/Common/Constant.php
Labels: improvement
