Repository EC-CUBE/ec-cube, pull requests merged in 2021-03, with the labels that each got.

#4919 非推奨の文字列を修正
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: ready-for-merge, improvement

#4918 フォルダ名に関するエラーメッセージ
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: ready-for-merge, bug:Low

#4941 Scrutinizer 及び AppVeyor は活用されていないため削除
  .scrutinizer.yml
  README.md
  appveyor.yml
Labels: Status: ready-for-merge, improvement

#4936 カートの順番が逆転する問題を修正
  src/Eccube/Service/CartService.php
Labels: Status: ready-for-merge, improvement

#4940 手数料を考慮して利用条件の判定を行うように修正
  src/Eccube/Controller/Admin/Setting/Shop/DeliveryController.php
  src/Eccube/Form/Type/Shopping/OrderType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Service/OrderHelper.php
  tests/Eccube/Tests/Form/Type/Shopping/OrderTypeTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/DeliveryControllerTest.php
Labels: Status: ready-for-merge, affected:admin_template, bug:Middle

#4902 DockerでGDでjpegやwebpを扱える様にDokerfileを変更
  Dockerfile
Labels: Status: ready-for-merge, enhancement

#4945 フロントテンプレートの互換テストを追加
  .github/workflows/e2e-bc-test.yml
Labels: Status: ready-for-merge, improvement

#4944 管理画面のテンプレートのアップロードページのツールチップを設定する
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Store/template_add.twig
Labels: Status: ready-for-merge, affected:admin_template, bug:Low

#4943 Codecov によるコードカバレッジを追加
  .coveralls.yml
  .github/workflows/coverage.yml
  README.md
  composer.json
  composer.lock
  symfony.lock
Labels: Status: ready-for-merge, improvement

#4927 Twig2.9以降filterタグは非推奨なのでapplyタグに変更
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_edit.twig
  src/Eccube/Resource/template/admin/Setting/System/authority.twig
Labels: Status: ready-for-merge, improvement

#4900 webp画像が存在する場合に、.jpgや.pngでアクセスが来てもwebpを返す様に変更
  .htaccess
Labels: Status: ready-for-merge, enhancement

#4953 カート内商品の順番が逆転する問題を修正
  src/Eccube/Entity/Cart.php
Labels: Status: ready-for-merge, improvement

#4950 bin/console eccube:fixtures:generate --with-image=cats を動作するよう修正
  src/Eccube/Command/GenerateDummyDataCommand.php
  tests/Eccube/Tests/Fixture/Generator.php
Labels: Status: ready-for-merge, improvement

#4935 商品画像アップロード即削除時の挙動を修正
  src/Eccube/Controller/Admin/Product/ProductController.php
Labels: Status: ready-for-merge, improvement

#4908 新着商品・新着情報のRSSフィード機能
  src/Eccube/Controller/RssFeedController.php
  src/Eccube/Resource/template/default/Feed/news.twig
  src/Eccube/Resource/template/default/Feed/products.twig
  src/Eccube/Resource/template/default/default_frame.twig
  tests/Eccube/Tests/Web/RssFeedControllerTest.php
Labels: affected:template, enhancement

#4956 PHPUnitのバージョンアップ
  bin/phpunit
  codeception/_support/AcceptanceTester.php
  codeception/_support/Page/Admin/OrderManagePage.php
  composer.json
  composer.lock
  phpunit.xml.dist
  symfony.lock
Labels: Status: ready-for-merge, improvement

#4965 E2Eテストの詳細検索ボタン修正
  codeception/_support/Page/Admin/OrderManagePage.php
Labels: Status: ready-for-merge, improvement

#4962 \Eccube\Application が残存していたため削除
  src/Eccube/Form/Type/Admin/TagType.php
  src/Eccube/Kernel.php
Labels: Status: ready-for-merge, improvement

#4964 console e:f:generate が動作しないのを修正
  Dockerfile
  dockerbuild/php.ini
  src/Eccube/Command/GenerateDummyDataCommand.php
Labels: Status: ready-for-merge, improvement

#4924 forタグにif条件の追加はTwig2.10で非推奨なので修正
  src/Eccube/Resource/template/admin/Content/block_edit.twig
  src/Eccube/Resource/template/admin/Content/layout.twig
  src/Eccube/Resource/template/admin/Content/news_edit.twig
  src/Eccube/Resource/template/admin/Content/page_edit.twig
  src/Eccube/Resource/template/admin/Customer/delivery_edit.twig
  src/Eccube/Resource/template/admin/Customer/edit.twig
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Product/category.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Product/product_class.twig
  src/Eccube/Resource/template/admin/Product/tag.twig
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_edit.twig
  src/Eccube/Resource/template/admin/Setting/Shop/mail.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
  src/Eccube/Resource/template/admin/Setting/System/member_edit.twig
  src/Eccube/Resource/template/default/Contact/confirm.twig
  src/Eccube/Resource/template/default/Contact/index.twig
  src/Eccube/Resource/template/default/Entry/confirm.twig
  src/Eccube/Resource/template/default/Entry/index.twig
  src/Eccube/Resource/template/default/Mypage/change.twig
  src/Eccube/Resource/template/default/Mypage/delivery_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_multiple_edit.twig
Labels: Status: ready-for-merge, affected:admin_template, affected:template, improvement

#4925 Doctrine ORM3.0ではサポートされないので、flushにエンティティを指定している処理を修正。
  src/Eccube/Command/GenerateDummyDataCommand.php
  src/Eccube/Command/PluginGenerateCommand.php
  src/Eccube/Controller/Admin/Content/LayoutController.php
  src/Eccube/Controller/Admin/Content/PageController.php
  src/Eccube/Controller/Admin/Customer/CustomerController.php
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Controller/Admin/Order/MailController.php
  src/Eccube/Controller/Admin/Order/OrderController.php
  src/Eccube/Controller/ShippingMultipleController.php
  src/Eccube/Entity/CartItem.php
  src/Eccube/Repository/BlockPositionRepository.php
  src/Eccube/Repository/CategoryRepository.php
  src/Eccube/Repository/ClassCategoryRepository.php
  src/Eccube/Repository/ClassNameRepository.php
  src/Eccube/Repository/CustomerAddressRepository.php
  src/Eccube/Repository/CustomerFavoriteProductRepository.php
  src/Eccube/Repository/MemberRepository.php
  src/Eccube/Repository/NewsRepository.php
  src/Eccube/Repository/OrderPdfRepository.php
  src/Eccube/Repository/TagRepository.php
  src/Eccube/Service/CartService.php
  src/Eccube/Service/PluginService.php
Labels: Status: ready-for-merge, improvement

#4967 4.0の変更取り込み
  .coveralls.yml
  .github/workflows/coverage.yml
  .scrutinizer.yml
  README.md
  appveyor.yml
  codeception/_support/Page/Admin/OrderManagePage.php
  composer.json
  composer.lock
  html/template/admin/assets/pdf/logo.png
  src/Eccube/Command/GenerateDummyDataCommand.php
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/Admin/Setting/Shop/DeliveryController.php
  src/Eccube/Entity/Cart.php
  src/Eccube/Form/Type/Shopping/OrderType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_edit.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Resource/template/admin/Setting/System/authority.twig
  src/Eccube/Resource/template/admin/Store/template_add.twig
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationFailureHandler.php
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationSuccessHandler.php
  src/Eccube/Service/CartService.php
  src/Eccube/Service/OrderHelper.php
  symfony.lock
  tests/Eccube/Tests/Fixture/Generator.php
  tests/Eccube/Tests/Form/Type/Shopping/OrderTypeTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/DeliveryControllerTest.php
  tests/Eccube/Tests/Web/AuthenticationHandlerTest.php
Labels: improvement

#4971 非推奨の文字列を修正
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: ready-for-merge, improvement

#4968 Hogeプラグインのcomposer.jsonを修正
  app/Plugin/HogePlugin/composer.json
Labels: Status: ready-for-merge, bug:Low

#4833 Bump version from jQuery 3.3.1 to 3.5.1
  html/template/install/assets/js/vendor/jquery-3.3.1.min.js
  html/template/install/assets/js/vendor/jquery-3.5.1.min.js
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/error.twig
  src/Eccube/Resource/template/admin/login_frame.twig
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Resource/template/install/frame.twig
Labels: Status: ready-for-merge, affected:admin_template, affected:plugin, affected:template, javascript

#4979 Travis CI の実行内容は GitHub Actions に置き換え済みなので削除する
  .github/workflows/deploy.yml
  .travis.yml
Labels: Status: ready-for-merge, improvement

#4934 カートの在庫切れ文言表示方法を変更
  html/template/default/assets/js/eccube.js
  src/Eccube/Resource/template/common/lang.twig
Labels: Status: ready-for-merge, affected:template, improvement, javascript

#4942 CSVインポートの時に文字列に含まれる改行コードを残すようにする
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Service/CsvImportService.php
  tests/Eccube/Tests/Service/CsvImportServiceTest.php
Labels: Status: ready-for-merge, bug:Low

#4933 商品詳細画面の商品画像を lazyload に対応
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: ready-for-merge, affected:template, enhancement

#4983 Badge を GitHub Actions に変更
  README.md
Labels: Status: ready-for-merge, improvement

#4984 codeception.sh を Travis CI 連携廃止に伴い削除
  .github/workflows/deploy.yml
  codeception.sh
Labels: Status: ready-for-merge, improvement

#4978 管理画面ログイン履歴とIPアドレスによるアクセス拒否を実装
  .env.dist
  app/DoctrineMigrations/Version20210319122142.php
  app/config/eccube/packages/eccube.yaml
  app/config/eccube/packages/eccube_nav.yaml
  codeception/_support/AcceptanceTester.php
  codeception/_support/Page/Admin/LoginHistoryPage.php
  codeception/acceptance/EA08SysteminfoCest.php
  src/Eccube/Controller/Admin/Setting/System/LoginHistoryController.php
  src/Eccube/Controller/Admin/Setting/System/SecurityController.php
  src/Eccube/Entity/LoginHistory.php
  src/Eccube/Entity/Master/LoginHistoryStatus.php
  src/Eccube/EventListener/IpAddrListener.php
  src/Eccube/EventListener/LoginHistoryListener.php
  src/Eccube/Form/Type/Admin/SearchLoginHistoryType.php
  src/Eccube/Form/Type/Admin/SecurityType.php
  src/Eccube/Form/Type/Master/LoginHistoryStatusType.php
  src/Eccube/Repository/LoginHistoryRepository.php
  src/Eccube/Repository/Master/LoginHistoryStatusRepository.php
  src/Eccube/Repository/QueryKey.php
  src/Eccube/Resource/doctrine/import_csv/en/definition.yml
  src/Eccube/Resource/doctrine/import_csv/en/mtb_login_history_status.csv
  src/Eccube/Resource/doctrine/import_csv/ja/definition.yml
  src/Eccube/Resource/doctrine/import_csv/ja/mtb_login_history_status.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/System/login_history.twig
  src/Eccube/Resource/template/admin/Setting/System/security.twig
  tests/Eccube/Tests/EccubeTestCase.php
  tests/Eccube/Tests/EventListener/LoginHistoryListenerTest.php
  tests/Eccube/Tests/Fixture/Generator.php
  tests/Eccube/Tests/Form/Type/Admin/SearchLoginHistoryTypeTest.php
  tests/Eccube/Tests/Form/Type/Admin/SecurityTypeTest.php
  tests/Eccube/Tests/Repository/LoginHistoryRepositoryGetQueryBuilderBySearchDataAdminTest.php
  tests/Eccube/Tests/Web/Admin/Setting/System/LoginHistoryControllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/System/SecurityControllerTest.php
Labels: Status: ready-for-merge, affected:admin_template, enhancement

#4992 nginx.conf.sample に bin ディレクトリを追加
  nginx.conf.sample
Labels: Status: ready-for-merge, improvement

#4955 docker-compose ファイルを分割する
  Dockerfile
  docker-compose.dev.yml
  docker-compose.mysql.yml
  docker-compose.owaspzap.yml
  docker-compose.pgsql.yml
  docker-compose.yml
  dockerbuild/docker-php-entrypoint
  dockerbuild/php.ini
Labels: Status: ready-for-merge, document, improvement

#4989 管理画面のお知らせのE2Eテストをリダイレクトに対応
  codeception/acceptance/EA01TopCest.php
Labels: improvement
