Repository EC-CUBE/ec-cube, pull requests merged in 2021-07, with the labels that each got.

#4986 商品詳細ページに構造化データを追加
  src/Eccube/Resource/template/default/Product/detail.twig
  tests/Eccube/Tests/Web/ProductControllerTest.php
Labels: affected:template, enhancement

#5058 商品一覧・商品詳細ページの商品画像 imgタグに、alt属性を追加
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: ready-for-merge, affected:template

#5077 テキストメール用の Escaper を実装
  src/Eccube/Resource/template/default/Mail/contact_mail.twig
  src/Eccube/Resource/template/default/Mail/customer_withdraw_mail.twig
  src/Eccube/Resource/template/default/Mail/entry_complete.twig
  src/Eccube/Resource/template/default/Mail/entry_confirm.twig
  src/Eccube/Resource/template/default/Mail/forgot_mail.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mail/reset_complete_mail.twig
  src/Eccube/Resource/template/default/Mail/shipping_notify.twig
  src/Eccube/Twig/Extension/SafeTextmailEscaperExtension.php
  tests/Eccube/Tests/Service/CsvImportServiceTest.php
  tests/Eccube/Tests/Web/Admin/Order/ShippingControllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/MailControllerTest.php
  tests/Eccube/Tests/Web/ContactControllerTest.php
  tests/Eccube/Tests/Web/EntryControllerTest.php
  tests/Eccube/Tests/Web/Mypage/WithdrawControllerTest.php
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
Labels: enhancement

#5019 検索結果0件のページと在庫切れのページを noindex とする
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Resource/template/default/meta.twig
  tests/Eccube/Tests/Web/ProductControllerTest.php
Labels: enhancement

#4808 4.1.x用にsitemap.index, sitemap.xml出力機能追加
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Controller/SitemapController.php
  src/Eccube/Resource/template/default/sitemap.xml.twig
  src/Eccube/Resource/template/default/sitemap_index.xml.twig
  tests/Eccube/Tests/Web/SitemapControllerTest.php
Labels: Status: ready-for-merge, enhancement

#5017 管理画面へ2段階認証機能を追加
  .env.dist
  app/config/eccube/packages/eccube.yaml
  codeception/acceptance/EA08SysteminfoCest.php
  composer.json
  composer.lock
  src/Eccube/Controller/Admin/Setting/System/TwoFactorAuthController.php
  src/Eccube/Entity/Member.php
  src/Eccube/EventListener/TwoFactorAuthListener.php
  src/Eccube/Form/Type/Admin/MemberType.php
  src/Eccube/Form/Type/Admin/TwoFactorAuthType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/System/member.twig
  src/Eccube/Resource/template/admin/Setting/System/member_edit.twig
  src/Eccube/Resource/template/admin/Setting/System/two_factor_auth_edit.twig
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/two_factor_auth.twig
  src/Eccube/Resource/template/admin/two_factor_auth_set.twig
  src/Eccube/Service/TwoFactorAuthService.php
  symfony.lock
Labels: Status: ready-for-merge, enhancement

#5085 テキストメール用の Escaper を実装 #5077 を4.1ブランチへ反映
  src/Eccube/Resource/template/default/Mail/contact_mail.twig
  src/Eccube/Resource/template/default/Mail/customer_withdraw_mail.twig
  src/Eccube/Resource/template/default/Mail/entry_complete.twig
  src/Eccube/Resource/template/default/Mail/entry_confirm.twig
  src/Eccube/Resource/template/default/Mail/forgot_mail.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mail/reset_complete_mail.twig
  src/Eccube/Resource/template/default/Mail/shipping_notify.twig
  src/Eccube/Twig/Extension/SafeTextmailEscaperExtension.php
  tests/Eccube/Tests/Service/CsvImportServiceTest.php
  tests/Eccube/Tests/Web/Admin/Order/ShippingControllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/MailControllerTest.php
  tests/Eccube/Tests/Web/ContactControllerTest.php
  tests/Eccube/Tests/Web/EntryControllerTest.php
  tests/Eccube/Tests/Web/Mypage/WithdrawControllerTest.php
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
Labels: enhancement

#5086 [4.1] package-api の composer2 対応
  app/config/eccube/packages/eccube.yaml
Labels: improvement

#5081 フロント入力項目のサニタイズ
  app/config/eccube/bundles.php
  app/config/eccube/services.yaml
  composer.json
  composer.lock
  src/Eccube/Form/EventListener/HTMLPurifierListener.php
  src/Eccube/Form/Extension/HTMLPurifierTextTypeExtension.php
  symfony.lock
  tests/Eccube/Tests/Web/ContactControllerTest.php
  tests/Eccube/Tests/Web/EntryControllerTest.php
Labels: enhancement

#5079 htmlディレクトリ以下でのPHPの実行を抑制
  html/.htaccess
Labels: enhancement

#5088 4.1-coreを4.1へ反映
  app/config/eccube/bundles.php
  app/config/eccube/services.yaml
  composer.json
  composer.lock
  html/.htaccess
  src/Eccube/Form/EventListener/HTMLPurifierListener.php
  src/Eccube/Form/Extension/HTMLPurifierTextTypeExtension.php
  symfony.lock
  tests/Eccube/Tests/Web/ContactControllerTest.php
  tests/Eccube/Tests/Web/EntryControllerTest.php
Labels: enhancement

#5091 バージョンを 4.1-beta3 に変更
  .github/workflows/deploy.yml
  package.json
  src/Eccube/Common/Constant.php
Labels: improvement

#5074 インストール完了画面で有効化するプラグインを選択する
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Controller/InstallPluginController.php
  src/Eccube/Resource/template/install/complete.twig
  src/Eccube/Resource/template/install/frame.twig
Labels: Status: ready-for-merge, enhancement

#5087 ファイル管理のアップロード可能ファイルを制限
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: Status: ready-for-merge, enhancement

#5093 Apply composer update
  composer.lock
  src/Eccube/Command/ComposerInstallCommand.php
  src/Eccube/Command/ComposerRemoveCommand.php
  src/Eccube/Command/ComposerRequireAlreadyInstalledPluginsCommand.php
  src/Eccube/Command/ComposerRequireCommand.php
  src/Eccube/Command/ComposerUpdateCommand.php
  src/Eccube/Command/DeleteCartsCommand.php
  src/Eccube/Command/GenerateDummyDataCommand.php
  src/Eccube/Command/GenerateProxyCommand.php
  src/Eccube/Command/InstallerCommand.php
  src/Eccube/Command/LoadDataFixturesEccubeCommand.php
  src/Eccube/Command/PluginDisableCommand.php
  src/Eccube/Command/PluginEnableCommand.php
  src/Eccube/Command/PluginGenerateCommand.php
  src/Eccube/Command/PluginInstallCommand.php
  src/Eccube/Command/PluginSchemaUpdateCommand.php
  src/Eccube/Command/PluginUninstallCommand.php
  src/Eccube/Command/PluginUpdateCommand.php
  src/Eccube/Command/UpdateSchemaDoctrineCommand.php
  src/Eccube/Controller/AbstractShoppingController.php
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
  src/Eccube/Controller/CartController.php
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Service/Payment/Method/Cash.php
  src/Eccube/Service/Payment/Method/CreditCard.php
  src/Eccube/Twig/Template.php
  symfony.lock
Labels: Status: ready-for-merge, dependencies, improvement

#5016 E2Eテストのカバレッジを計測する
  .github/workflows/coverage.yml
  .github/workflows/dockerbuild.yml
  .github/workflows/e2e-bc-test.yml
  .github/workflows/e2e-test.yml
  .github/workflows/plugin-test.yml
  .github/workflows/unit-test.yml
  codeception.yml
  codeception/_envs/github_action.yml
  codeception/_support/Page/Admin/CategoryManagePage.php
  codeception/_support/Page/Admin/OrderManagePage.php
  codeception/_support/Page/Admin/ProductCsvUploadPage.php
  codeception/_support/Page/Admin/ProductManagePage.php
  codeception/acceptance.suite.yml
  codeception/acceptance/EA04OrderCest.php
  codeception/acceptance/EF02ProductCest.php
  codeception/acceptance/EF03OrderCest.php
  codeception/acceptance/EF05MypageCest.php
Labels: Status: ready-for-merge, improvement

#5095 eccube:install コマンドでは Api プラグインを有効化しない
  src/Eccube/Command/InstallerCommand.php
Labels: Status: ready-for-merge, improvement

#5092 キャッシュ削除時のメンテナンスタイミングを調整
  src/Eccube/Controller/Admin/Content/CacheController.php
  src/Eccube/Controller/Admin/Content/MaintenanceController.php
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Resource/template/admin/Content/cache.twig
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
  tests/Eccube/Tests/Web/Admin/Content/MaintenanceControllerTest.php
Labels: improvement
