Repository EC-CUBE/ec-cube, pull requests merged in 2021-09, with the labels that each got.

#5128 ログインしたメンバーを削除できるように修正
  src/Eccube/Repository/MemberRepository.php
  tests/Eccube/Tests/Repository/MemberRepositoryTest.php
Labels: Status: ready-for-merge, bug:Middle

#5131 beta3で取り込まれた未検証のPRをRevert
  app/config/eccube/packages/security.yaml
  app/config/eccube/services.yaml
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_11.2.header.scss
  index.php
  src/Eccube/Controller/Admin/Content/MaintenanceController.php
  src/Eccube/EventListener/MaintenanceListener.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Form/Type/Admin/SearchProductType.php
  src/Eccube/Repository/ProductRepository.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Security/Http/Authentication/EccubeLogoutSuccessHandler.php
  src/Eccube/Service/SystemService.php
  tests/Eccube/Tests/Repository/AbstractProductRepositoryTestCase.php
  tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataAdminTest.php
  tests/Eccube/Tests/Repository/ProductRepositoryGetQueryBuilderBySearchDataTest.php
Labels: bug:Critical

#5133 受注一覧を受注ステータスで絞り込みできないのを修正
  src/Eccube/Controller/Admin/Order/OrderController.php
Labels: bug:High

#5132 一括ステータス更新を同期処理に変更
  codeception/acceptance/EA04OrderCest.php
  src/Eccube/Resource/template/admin/Order/confirmationModal_js.twig
Labels: bug:Middle

#5143 class名指定時の崩れを修正
  src/Eccube/Resource/template/admin/Form/bootstrap_4_horizontal_layout.html.twig
Labels: bug:Low

#5137 package-apiのURLを本番用に更新
  app/config/eccube/packages/eccube.yaml
Labels: improvement

#5136 バージョンの更新
  package.json
  src/Eccube/Common/Constant.php
Labels: improvement

#5142 下層ディレクトリにec-cubeを設置した場合、2段階認証のトークン入力に失敗する不具合の修正
  src/Eccube/Service/TwoFactorAuthService.php
Labels: bug:High

#5157 非推奨になっている呼び出しを修正
  app/config/eccube/packages/doctrine.yaml
  app/config/eccube/packages/twig.yaml
  app/config/eccube/services.yaml
  composer.json
  composer.lock
  src/Eccube/Doctrine/DBAL/Types/UTCDateTimeType.php
  src/Eccube/Doctrine/DBAL/Types/UTCDateTimeTzType.php
  src/Eccube/Event/EventDispatcherWrapper.php
Labels: bug:Critical

#5154 VAddy設定追加
  .github/workflows/vaddy-1.yml
  .github/workflows/vaddy-2.yml
  codeception/_envs/vaddy.yml
  codeception/_support/Page/Admin/ApiOauthEditPage.php
  codeception/_support/Page/Admin/ApiOauthPage.php
  codeception/_support/Page/Admin/ApiWebHookEditPage.php
  codeception/_support/Page/Admin/ApiWebHookPage.php
  codeception/_support/Page/Admin/CouponEditPage.php
  codeception/_support/Page/Admin/CouponManagePage.php
  codeception/_support/Page/Admin/MailMagazineEditPage.php
  codeception/_support/Page/Admin/MailMagazineHistoryPage.php
  codeception/_support/Page/Admin/MailMagazinePage.php
  codeception/_support/Page/Admin/MailMagazineTemplateEditPage.php
  codeception/_support/Page/Admin/MailMagazineTemplatePage.php
  codeception/_support/Page/Admin/ProductReviewManagePage.php
  codeception/_support/Page/Admin/RecommendEditPage.php
  codeception/_support/Page/Admin/RecommendManagePage.php
  codeception/_support/Page/Admin/RelatedProductEditPage.php
  codeception/_support/Page/Admin/SalesReportPage.php
  codeception/_support/Page/Front/ProductReviewPage.php
  codeception/acceptance/EA03ProductCest.php
  codeception/acceptance/EA04OrderCest.php
  codeception/acceptance/EA05CustomerCest.php
  codeception/acceptance/EA06ContentsManagementCest.php
  codeception/acceptance/EA07BasicinfoCest.php
  codeception/acceptance/EA08SysteminfoCest.php
  codeception/acceptance/EA09ShippingCest.php
  codeception/acceptance/EF01TopCest.php
  codeception/acceptance/EF02ProductCest.php
  codeception/acceptance/EF03OrderCest.php
  codeception/acceptance/EF04CustomerCest.php
  codeception/acceptance/EF05MypageCest.php
  codeception/acceptance/EF06OtherCest.php
  codeception/acceptance/Plugin/PL01RecommendCest.php
  codeception/acceptance/Plugin/PL02CouponCest.php
  codeception/acceptance/Plugin/PL03MailMagazineCest.php
  codeception/acceptance/Plugin/PL04SalesReportCest.php
  codeception/acceptance/Plugin/PL05RelatedProductCest.php
  codeception/acceptance/Plugin/PL06SecurityCheckCest.php
  codeception/acceptance/Plugin/PL07ProductReviewCest.php
  codeception/acceptance/Plugin/PL08ApiCest.php
  codeception/acceptance/Plugin/PL09SiteKitCest.php
  codeception/acceptance/Plugin/PL10GMCCest.php
  codeception/acceptance/VaddyCest.php
  src/Eccube/Controller/Admin/Setting/Shop/DeliveryController.php
Labels: enhancement

#5160 E2Eテスト改善 EA06_ContentsManagementCest
  codeception/acceptance/EA06ContentsManagementCest.php
Labels: Status: ready-for-merge

#5163 E2Eテスト改善 EA09ShippingCest
  codeception/acceptance/EA09ShippingCest.php
Labels: Status: ready-for-merge

#5164 E2Eテスト改善 EA08SysteminfoCest
  codeception/acceptance/EA08SysteminfoCest.php
Labels: Status: ready-for-merge

#5166 E2Eテスト改善 EF06 お問い合わせフォームのテスト追加
  codeception/acceptance/EF06OtherCest.php
Labels: Status: ready-for-merge

#5169 OWASP ZAP のアクティブスキャンを自動化する試み
  .github/workflows/penetration-test.yml
  docker-compose.owaspzap.daemon.yml
  zap/.gitignore
  zap/options.properties
  zap/selenium/ci/TypeScript/.editorconfig
  zap/selenium/ci/TypeScript/babel.config.js
  zap/selenium/ci/TypeScript/package.json
  zap/selenium/ci/TypeScript/test/admin/order_mail.test.ts
  zap/selenium/ci/TypeScript/test/front_guest/contact.test.ts
  zap/selenium/ci/TypeScript/test/front_login/contact.test.ts
  zap/selenium/ci/TypeScript/tsconfig.json
  zap/selenium/ci/TypeScript/utils/Progress.ts
  zap/selenium/ci/TypeScript/utils/SeleniumCapabilities.ts
  zap/selenium/ci/TypeScript/utils/ZapClient.ts
  zap/selenium/ci/TypeScript/yarn.lock
  zap/sessions/.gitkeep
Labels: enhancement, Status: ready-for-merge

#5148 HerokuのPostgreSQLバージョンを更新
  app.json
Labels: Status: ready-for-merge, bug:Low

#5113 UnitTestとE2Eのカバレッジを分離
  .github/workflows/coverage.yml
Labels: improvement
