Repository EC-CUBE/ec-cube, pull requests merged in 2021-01, with the labels that each got.

#4820 デバッグツールバーの URL 修正
  src/Eccube/Resource/template/toolbar/eccube.html.twig
Labels: bug:Low

#4832 Fix product duplicate message.
  src/Eccube/Resource/locale/messages.en.yaml
Labels: bug:Low

#4834 ポイント付与比率の下限を1から0に変更する
  src/Eccube/Form/Type/Admin/ShopMasterType.php
  tests/Eccube/Tests/Form/Type/Admin/ShopMasterTypeTest.php
Labels: improvement

#4818 [4.1] Readmeを4.1に書き換え
  README.md
Labels: document

#4880 browser-syncと関連ライブラリを最新化
  package-lock.json
  package.json
Labels: dependencies

#4835 PHPStan による静的解析の導入
  .github/workflows/deploy.yml
  .github/workflows/phpstan.yml
  .gitignore
  phpstan.neon.dist
  src/Eccube/EventListener/TransactionListener.php
Labels: enhancement

#4844 対応状況管理機能の追加
  app/config/eccube/packages/eccube_nav.yaml
  codeception/_support/Page/Admin/OrderStatusSettingsPage.php
  codeception/acceptance/EA07BasicinfoCest.php
  src/Eccube/Controller/Admin/Setting/Shop/OrderStatusController.php
  src/Eccube/Form/Type/Admin/MasterdataType.php
  src/Eccube/Form/Type/Admin/OrderStatusSettingType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/order_status.twig
  tests/Eccube/Tests/Web/Admin/Setting/Shop/OrderStatusControllerTest.php
Labels: enhancement
