Repository EC-CUBE/ec-cube, pull requests merged in 2021-06, with the labels that each got.

#5068 [4.1-core] bump plugin-installer to 2.0.0
  composer.json
  composer.lock
Labels: improvement

#5071 Update 4.0.6
  .htaccess
  composer.lock
  package.json
  src/Eccube/Common/Constant.php
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Service/Composer/ComposerApiService.php
  symfony.lock
Labels: improvement

#5048 Composer Update
  composer.lock
  symfony.lock
Labels: Status: ready-for-merge, dependencies

#5078 [4.0.6-p1] .htaccess の修正不備に対応
  .htaccess
  package.json
  src/Eccube/Common/Constant.php
Labels: bug:Critical

#5073 4.0.6 / 4.0.6-p1 の変更（#5071 / #5078）の取り込み
  .htaccess
  composer.lock
  package.json
  src/Eccube/Common/Constant.php
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Service/Composer/ComposerApiService.php
  symfony.lock
Labels: bug:Critical, improvement
