Repository EC-CUBE/ec-cube, pull requests merged in 2021-02, with the labels that each got.

#4888 商品規格の条件誤り
  src/Eccube/Resource/template/default/Mypage/index.twig
Labels: affected:template, bug:Low

#4889 ファイル管理で名前の重複するディレクトリを作ろうとした時にエラーメッセージを出す
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: Status: ready-for-merge, improvement

#4891 PHPStan を require-dev に入れる
  .github/workflows/phpstan.yml
  composer.json
  composer.lock
  phpstan.neon.dist
  src/Eccube/Controller/Admin/Content/PageController.php
  symfony.lock
Labels: Status: ready-for-merge, improvement

#4892 カート追加時モーダル枠の白い部分をクリックした時は何も反応させない
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: ready-for-merge, affected:template, bug:Low

#4921 E2Eテストが落ちる問題の修正
  codeception/_support/Page/Admin/OrderManagePage.php
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Order/order_pdf.twig
  src/Eccube/Resource/template/admin/Product/index.twig
Labels: Status: ready-for-merge, affected:template, bug:Low, javascript

#4913 PHP-CS-Fixerの更新と設定変更
  .php_cs.dist
  composer.lock
Labels: Status: ready-for-merge, improvement

#4906 ご注文手続き画面で商品種別が入れ替わる問題の修正
  src/Eccube/Controller/ShippingMultipleController.php
  src/Eccube/Controller/ShoppingController.php
Labels: Status: ready-for-merge, bug:Low

#4894 利用条件の判定を、自身の手数料を考慮して計算するように修正
  src/Eccube/Form/Type/Shopping/OrderType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Service/OrderHelper.php
  tests/Eccube/Tests/Form/Type/Shopping/OrderTypeTest.php
  tests/Eccube/Tests/Service/OrderHelperTest.php
Labels: bug:Middle

#4794 .gitignoreの見直し
  .gitignore
  html/user_data/.gitkeep
Labels: Status: ready-for-merge, improvement

#4938 [4.1-feature] 4.0ブランチの不具合修正を取り込み
  .github/workflows/phpstan.yml
  codeception/_support/Page/Admin/OrderManagePage.php
  composer.json
  composer.lock
  phpstan.neon.dist
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Controller/Admin/Content/PageController.php
  src/Eccube/Controller/ShippingMultipleController.php
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Order/order_pdf.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/default/Mypage/index.twig
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/Product/list.twig
  symfony.lock
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: bug

#4917 ログイン時に不正な転送先を指定した場合は400を返すよう変更
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationFailureHandler.php
  src/Eccube/Security/Http/Authentication/EccubeAuthenticationSuccessHandler.php
  tests/Eccube/Tests/Web/AuthenticationHandlerTest.php
Labels: Status: ready-for-merge, bug:Low
