Repository EC-CUBE/ec-cube, pull requests merged in 2022-07, with the labels that each got.

#5417 [4.2]サブディレクトリにEC-CUBEをインストールすると,管理画面の商品画像が読み込めなくなるのを修正
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
Labels: Status: ready-for-merge, bug:High

#5423 [4.2] 管理画面の JavaScript エラーを修正
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  src/Eccube/Resource/template/admin/index.twig
Labels: bug:Low

#5431 [4.2]パスワードを空欄にした場合, エラーになるのを修正
  src/Eccube/Entity/Member.php
  tests/Eccube/Tests/Web/Admin/Setting/System/MemberControllerTest.php
Labels: bug:High

#5430 [4.2]ArrayAccess の deprecated を修正
  src/Eccube/Common/EccubeConfig.php
  src/Eccube/Entity/AbstractEntity.php
Labels: bug:Low

#5428 [4.2]フリーエリアのpurify漏れを修正
  src/Eccube/Resource/template/default/Product/detail.twig
  tests/Eccube/Tests/Web/ProductControllerTest.php
Labels: bug:Low

#5422 [4.2] RESTRICT_FILE_UPLOADの警告が重複しないよう修正
  src/Eccube/Controller/AbstractController.php
  src/Eccube/Controller/Admin/Content/BlockController.php
  src/Eccube/Controller/Admin/Content/CssController.php
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Controller/Admin/Content/JsController.php
  src/Eccube/Controller/Admin/Content/PageController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Controller/Admin/Store/TemplateController.php
Labels: bug:Low

#5421 [4.2]モーダルの背景をクリックするとモーダルが消えてしまうのを修正
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
  src/Eccube/Resource/template/admin/Product/csv_product.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/admin/Setting/Shop/mail.twig
  src/Eccube/Resource/template/admin/Store/plugin_confirm.twig
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
  src/Eccube/Resource/template/install/complete.twig
Labels: bug:Low

#5369 コンテナビルド時にEC-CUBEを初期化せずに、コンテナ初回起動時に初期化する。
  .github/workflows/deny-test.yml
  .github/workflows/dockerbuild.yml
  Dockerfile
  docker-compose.mysql.yml
  docker-compose.pgsql.yml
  docker-compose.yml
  dockerbuild/docker-php-entrypoint
  dockerbuild/grant_to_dbuser.sql
Labels: Status: ready-for-merge, improvement

#5435 [4.2] カバレッジのテストが落ちていたのを修正
  .github/workflows/coverage.yml
Labels: bug

#5437 [4.2] 適格請求書発行事業者登録番号のツールチップを修正
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
Labels: bug:Low

#5418 [4.2]WebAPI プラグインの削除に失敗する問題の修正
  .github/workflows/plugin-test.yml
  codeception/_data/plugins/Bundle-1.0.0.tgz
  codeception/_data/plugins/Bundle-1.0.1.tgz
  src/Eccube/Service/PluginService.php
Labels: bug:High

#5407 fix issue/5252 - CSVインポート時にデリミタがエスケープされていることがある
  src/Eccube/Controller/Admin/AbstractCsvImportController.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Service/CsvImportService.php
  src/Eccube/Stream/Filter/ConvertLineFeedFilter.php
  src/Eccube/Stream/Filter/SjisToUtf8EncodingFilter.php
  tests/Eccube/Tests/Service/CsvImportServiceTest.php
  tests/Eccube/Tests/Stream/Filter/ConvertLineFeedFilterTest.php
  tests/Eccube/Tests/Stream/Filter/SjisToUtf8EncodingFilterTest.php
  tests/Fixtures/sjis.csv
Labels: bug:Low

#5445 Guzzle の脆弱性に対応
  composer.lock
Labels: Status: ready-for-merge, security

#5447 Security upgrade jquery-ui from 1.13.1 to 1.13.2
  package-lock.json
  package.json
Labels: Status: ready-for-merge, security

#5456 [4.2]ウィンドウ幅が630px未満の場合, 画像サイズが崩れるのを修正
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/Product/list.twig
Labels: bug:Low

#5459 spell miss?
  bin/template_jp.php
Labels: bug:Low

#5389 update gulp-sass
  package-lock.json
  package.json
Labels: Status: ready-for-merge, bug:Low

#5441 英語メッセージのtypoを修正
  src/Eccube/Resource/locale/messages.en.yaml
Labels: Status: ready-for-merge, bug:Low

#5438 商品CSV登録で商品コードの項目がなければ更新を無視するように対応
  src/Eccube/Controller/Admin/Product/CsvImportController.php
Labels: Status: ready-for-merge, improvement

#5443 PHP8とMySQLでプラグインアップデートコマンドを実行すると no active transaction になるのを修正
  .github/workflows/plugin-test.yml
  src/Eccube/EventListener/TransactionListener.php
  src/Eccube/Service/PluginService.php
Labels: Status: ready-for-merge, bug:High

#5464 受注登録時に電話番号のバリデーションを効くように修正
  src/Eccube/Form/Type/PhoneNumberType.php
  tests/Eccube/Tests/Form/Type/Admin/OrderTypeTest.php
Labels: bug:Low

#5467 [4.2] パスワード未入力時のエラーメッセージが重複するのを修正
  src/Eccube/Form/Type/RepeatedPasswordType.php
Labels: Status: ready-for-merge, bug:Low

#5468 [4.2]MAILER_DSN にデフォルト値を設定
  app/config/eccube/packages/mailer.yaml
Labels: bug:Low

#5466 受注登録画面の使用されていないhiddenを削除
  src/Eccube/Resource/template/admin/Order/edit.twig
Labels: Status: ready-for-merge, bug:Low

#5474 [4.2] パスワードの要件を PCI DSS ver4.0 に準拠させる
  app/config/eccube/packages/eccube.yaml
  codeception/_support/Page/Admin/SystemMemberEditPage.php
  codeception/_support/Page/Front/EntryPage.php
  codeception/acceptance/EA05CustomerCest.php
  codeception/acceptance/EA08SysteminfoCest.php
  codeception/acceptance/EF04CustomerCest.php
  codeception/acceptance/EF05MypageCest.php
  src/Eccube/Form/Type/Admin/ChangePasswordType.php
  src/Eccube/Form/Type/Install/Step3Type.php
  src/Eccube/Form/Type/RepeatedPasswordType.php
  src/Eccube/Resource/locale/validators.en.yaml
  src/Eccube/Resource/locale/validators.ja.yaml
  tests/Eccube/Tests/Form/Type/Admin/CustomerTypeTest.php
  tests/Eccube/Tests/Form/Type/Admin/MemberTypeTest.php
  tests/Eccube/Tests/Form/Type/Front/EntryTypeTest.php
  tests/Eccube/Tests/Form/Type/Front/PasswordResetTypeTest.php
  tests/Eccube/Tests/Form/Type/Install/Step3TypeTest.php
  tests/Eccube/Tests/Form/Type/RepeatedPasswordTypeTest.php
  tests/Eccube/Tests/Web/Admin/Customer/CustomerEditControllerTest.php
  tests/Eccube/Tests/Web/Admin/IndexControllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/System/MemberControllerTest.php
  tests/Eccube/Tests/Web/EntryControllerTest.php
  tests/Eccube/Tests/Web/Mypage/ChangeControllerTest.php
Labels: improvement, security
