Repository EC-CUBE/ec-cube, pull requests merged in 2022-06, with the labels that each got.

#5255 会員登録完了ページ等　本文とボタンの横幅（グリッド）の修正
  src/Eccube/Resource/template/default/Contact/complete.twig
  src/Eccube/Resource/template/default/Entry/activate.twig
  src/Eccube/Resource/template/default/Entry/complete.twig
  src/Eccube/Resource/template/default/Mypage/change_complete.twig
  src/Eccube/Resource/template/default/Mypage/withdraw_complete.twig
  src/Eccube/Resource/template/default/Shopping/complete.twig
Labels: Status: ready-for-merge, affected:template

#5245 規格のラベルが表示されない不具合を修正
  src/Eccube/Resource/template/default/Product/detail.twig
Labels: Status: ready-for-merge, affected:template, improvement

#5378 PostgreSQL利用時にシステムエラーが発生する不具合を修正
  src/Eccube/Controller/Install/InstallController.php
Labels: bug:Low

#5258 マイページ／注文履歴詳細　戻るボタン位置の調整
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_15.2.order.scss
  src/Eccube/Resource/template/default/Mypage/history.twig
Labels: Status: fix-me, affected:template

#4796 DBの文字コードをutf8mb4に対応
  .env.dist
  .github/workflows/unit-test.yml
  app/config/eccube/packages/doctrine.yaml
  docker-compose.mysql.yml
  docker-compose.pgsql.yml
  docker-compose.yml
  src/Eccube/Command/InstallerCommand.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Entity/Product.php
  tests/Eccube/Tests/Web/Admin/Product/ProductControllerTest.php
Labels: improvement

#5384 最新のMailCatcherイメージでのエラーを修正
  codeception/acceptance/EA04OrderCest.php
  codeception/acceptance/EA05CustomerCest.php
  codeception/acceptance/EF03OrderCest.php
  codeception/acceptance/EF04CustomerCest.php
  codeception/acceptance/EF06OtherCest.php
  composer.json
  composer.lock
Labels: bug:Low

#5380 RememberMeトークンでログインした場合はパスワード再発行画面にアクセス可能とする
  src/Eccube/Controller/ForgotController.php
Labels: Status: ready-for-merge, bug:Low

#5382 [4.2] インボイス対応
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_7.3.cart.scss
  src/Eccube/Entity/BaseInfo.php
  src/Eccube/Entity/Order.php
  src/Eccube/Form/Type/Admin/ShopMasterType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
  src/Eccube/Resource/template/default/Mail/order.html.twig
  src/Eccube/Resource/template/default/Mail/order.twig
  src/Eccube/Resource/template/default/Mypage/history.twig
  src/Eccube/Resource/template/default/Shopping/confirm.twig
  src/Eccube/Resource/template/default/Shopping/index.twig
  src/Eccube/Service/OrderPdfService.php
  src/Eccube/Service/TaxRuleService.php
  tests/Eccube/Tests/Entity/OrderTest.php
Labels: enhancement, Status: ready-for-merge

#5388 認証キー発行処理をcookieに依存しない実装に変更
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Resource/template/admin/Store/authentication_setting.twig
Labels: bug:Low

#5402 [4.2]ファイルアップロード可能な機能を制限するオプションを追加
  .env.dist
  .github/workflows/e2e-test.yml
  app/config/eccube/packages/eccube.yaml
  codeception/acceptance/EA06ContentsManagementCest.php
  codeception/acceptance/EA08SysteminfoCest.php
  codeception/acceptance/EA10PluginCest.php
  src/Eccube/Controller/Admin/Content/BlockController.php
  src/Eccube/Controller/Admin/Content/CssController.php
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Controller/Admin/Content/JsController.php
  src/Eccube/Controller/Admin/Content/PageController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Controller/Admin/Store/TemplateController.php
  src/Eccube/EventListener/RestrictFileUploadListener.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: enhancement

#5406 fix issues/5351 kana01, kana02 が nullable: true となっているが、どちらか一方が null だと検索にヒットしない
  src/Eccube/Repository/CustomerRepository.php
  src/Eccube/Repository/OrderRepository.php
  tests/Eccube/Tests/Repository/CustomerRepositoryGetQueryBuilderBySearchDataTest.php
  tests/Eccube/Tests/Repository/OrderRepositoryGetQueryBuilderBySearchDataAdminTest.php
Labels: Status: ready-for-merge, bug:Low

#5408 fix issues/5202 - CSVダウンロードにて重複や抜けが生じる可能性について
  src/Eccube/Controller/Admin/Product/ProductController.php
  tests/Eccube/Tests/Web/Admin/Product/ProductControllerTest.php
Labels: bug:Low

#5392 [#5372] HTMLテキスト入力箇所のサニタイズ について。
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Product/csv_category.twig
  src/Eccube/Resource/template/admin/Product/csv_product.twig
  src/Eccube/Resource/template/admin/Setting/Shop/mail_view.twig
  src/Eccube/Resource/template/admin/Store/plugin_detail_modal.twig
  src/Eccube/Resource/template/default/Block/news.twig
  src/Eccube/Resource/template/default/Product/detail.twig
  src/Eccube/Resource/template/default/Product/list.twig
  src/Eccube/Resource/template/default/Shopping/complete.twig
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
  tests/Eccube/Tests/Web/ProductControllerTest.php
  tests/Eccube/Tests/Web/ShoppingControllerTest.php
  tests/Eccube/Tests/Web/TopControllerTest.php
Labels: Status: ready-for-merge, improvement, security

#5405 fix issues/5363 - 商品送料を有効にした場合、「1行目をすべての行に複製」クリックで、商品送料が消えてしまう
  src/Eccube/Resource/template/admin/Product/product_class.twig
Labels: Status: ready-for-merge, bug:Low

#5390 メンテナンストークンにSecure属性を設定する
  src/Eccube/EventListener/MaintenanceListener.php
Labels: Status: ready-for-merge, bug:Low

#5404 fix issue/5364 - Entity拡張でproxyが正しく生成されない場合がある
  src/Eccube/Service/EntityProxyService.php
Labels: Status: ready-for-merge, bug:Middle

#5028 カテゴリ管理のすべてのカテゴリにIDを表示する
  src/Eccube/Resource/template/admin/Product/category.twig
Labels: Status: ready-for-merge, improvement

#5022 CWVのCLS対応のために商品一覧画像のwidth、height追加
  src/Eccube/Resource/template/default/Product/list.twig
Labels: Status: ready-for-merge, improvement

#5023 CWVのCLS対応のために商品詳細画像のwidth、height追加
  src/Eccube/Resource/template/default/Product/detail.twig
Labels: Status: ready-for-merge, improvement

#5395 [4.2] jQuery-File-Upload を filepond に変更する
  gulp/task/scss-min.js
  gulp/task/scss.js
  html/bundle/admin.bundle.js
  html/bundle/admin.bundle.js.LICENSE.txt
  html/bundle/admin.bundle.js.map
  html/template/admin/assets/css/app.css
  html/template/admin/assets/css/app.css.map
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/css/app.min.css.map
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/css/fileupload/demo-ie8.css
  html/template/admin/assets/css/fileupload/demo.css
  html/template/admin/assets/css/fileupload/jquery.fileupload-noscript.css
  html/template/admin/assets/css/fileupload/jquery.fileupload-ui-noscript.css
  html/template/admin/assets/css/fileupload/jquery.fileupload-ui.css
  html/template/admin/assets/css/fileupload/jquery.fileupload.css
  html/template/admin/assets/css/fileupload/style.css
  html/template/admin/assets/js/bundle.js
  html/template/admin/assets/js/vendor/fileupload/jquery.fileupload-process.js
  html/template/admin/assets/js/vendor/fileupload/jquery.fileupload-validate.js
  html/template/admin/assets/js/vendor/fileupload/jquery.fileupload.js
  html/template/admin/assets/js/vendor/fileupload/jquery.iframe-transport.js
  html/template/admin/assets/js/vendor/fileupload/vendor/jquery.ui.widget.js
  html/template/admin/assets/scss/component/_bootstrapOriginal.scss
  html/template/admin/assets/scss/component/_form.scss
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  package-lock.json
  package.json
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
  tests/Eccube/Tests/Web/Admin/Product/ProductControllerTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/PaymentControllerTest.php
Labels: Status: ready-for-merge, improvement
