Repository EC-CUBE/ec-cube, pull requests merged in 2022-08, with the labels that each got.

#5482 電話番号、郵便番号バリデーションで不適切な文字が通過するので修正
  src/Eccube/Controller/NonMemberShoppingController.php
  src/Eccube/Form/Type/PhoneNumberType.php
  src/Eccube/Form/Type/PostalType.php
  tests/Eccube/Tests/Form/Type/PhoneNumberTypeTest.php
  tests/Eccube/Tests/Form/Type/PostalTypeTest.php
  tests/Eccube/Tests/Web/ShoppingControllerWithNonmemberTest.php
Labels: bug:Low

#5475 [4.2] 特定商取引設定のE2Eテストを追加
  codeception/_support/Page/Admin/TradelawSettingPage.php
  codeception/_support/Page/Front/HelpTradelawPage.php
  codeception/acceptance/EA07BasicinfoCest.php
Labels: improvement

#5458 jquery-uiを更新
  html/bundle/admin.bundle.js
  html/bundle/admin.bundle.js.LICENSE.txt
  html/bundle/admin.bundle.js.map
Labels: improvement

#5462 新規会員登録のスタイル修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_3.1.inputText.scss
  html/template/default/assets/scss/project/_19.1.register.scss
  src/Eccube/Resource/template/default/Entry/index.twig
Labels: bug:Low, affected:template

#5479 月末が土日で金曜日にテストがエラーになるのを修正
  tests/Eccube/Tests/Web/Block/CalendarControllerTest.php
Labels: bug:Low

#5480 [4.2]先頭にゼロがつかない日, 時間にテストがエラーになるのを修正
  tests/Eccube/Tests/Web/Admin/Setting/Shop/TaxRuleControllerTest.php
Labels: bug:Low

#5472 postgresql利用時のtranslateのFROMの修正
  src/Eccube/Doctrine/ORM/Query/Normalize.php
  tests/Eccube/Tests/Doctrine/ORM/Query/NormalizeTest.php
Labels: bug:Low

#5473 Add a login throttling to firewalls.
  .env.dist
  app/config/eccube/packages/eccube.yaml
  app/config/eccube/packages/security.yaml
  codeception/_data/plugins/Bundle-1.0.0.tgz
  codeception/_data/plugins/Bundle-1.0.1.tgz
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Eccube/EventListener/LoginHistoryListener.php
  src/Eccube/Resource/locale/validators.ja.yaml
  symfony.lock
Labels: enhancement, security

#5469 テスト対象のフォームごとに確認するように変更
  tests/Eccube/Tests/Form/Type/Admin/OrderTypeTest.php
Labels: improvement

#5470 受注登録時に郵便番号のバリデーションが効くように修正
  src/Eccube/Form/Type/PostalType.php
  tests/Eccube/Tests/Form/Type/Admin/OrderTypeTest.php
Labels: bug:Low

#5463 お届け先の複数指定 数量及びボタンスタイル修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_15.2.order.scss
  src/Eccube/Resource/template/default/Shopping/shipping_multiple.twig
Labels: bug:Low, affected:template

#5490 フッターのページ下部固定及び、HTMLタグの修正
  codeception/_support/AcceptanceTester.php
  codeception/_support/Page/Front/HelpTradelawPage.php
  codeception/_support/Page/Front/ShoppingLoginPage.php
  codeception/acceptance/EA06ContentsManagementCest.php
  codeception/acceptance/EF05MypageCest.php
  codeception/acceptance/EF06OtherCest.php
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_11.2.header.scss
  src/Eccube/Resource/template/default/default_frame.twig
Labels: bug:Low, affected:template

#5486 ボタンがdisabledのときテキストが白色になるよう修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/mixins/_btn.scss
Labels: bug:Low, bugbounty2022:pr:entry

#5485 マイページの注文履歴一覧のスタイル修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_16.1.history.scss
Labels: bug:Low, bugbounty2022:pr:entry

#5497 フロントのfont-familyをEC-CUBE4.1と同じものにする
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/mixins/_projects.scss
Labels: Status: ready-for-merge, bug:Low

#5495 [4.2]`eccube:fixtures:generate --without-image` が反転していたのを修正
  src/Eccube/Command/GenerateDummyDataCommand.php
Labels: Status: ready-for-merge, bug:Low

#5494 お届け先の複数指定画面でボタンのボーダーが表示されないバグ修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/mixins/_projects.scss
  src/Eccube/Resource/template/default/Shopping/shipping_multiple.twig
Labels: bug:Low

#5502 bootstrap5が複数回importされるバグ修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/mixins/_btn.scss
  html/template/default/assets/scss/style.scss
Labels: bug:Low

#5505 管理画面受注検索画面の複合検索の不具合修正
  src/Eccube/Repository/OrderRepository.php
  tests/Eccube/Tests/Repository/OrderRepositoryTest.php
Labels: bug:Low

#5516 #5505 のテストコード修正
  tests/Eccube/Tests/Repository/OrderRepositoryTest.php
Labels: bug:Low

#5517 定休日カレンダーの編集時にキャンセルすると編集中のタイトル/日付のままになるバグ修正
  src/Eccube/Resource/template/admin/Setting/Shop/calendar.twig
Labels: Status: ready-for-merge, bug:Low

#5506 メンテナスモードのアラートのスタイル調整
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_1.1.heading.scss
  html/template/default/assets/scss/component/_2.2.closebutton.scss
  html/template/default/assets/scss/component/_2.3.otherbutton.scss
  html/template/default/assets/scss/component/_3.1.inputText.scss
  html/template/default/assets/scss/component/_4.1.icon.scss
  html/template/default/assets/scss/component/_5.1.grid.scss
  html/template/default/assets/scss/component/_5.2.layout.scss
  html/template/default/assets/scss/component/_7.2.search.scss
  html/template/default/assets/scss/component/_7.3.cart.scss
  html/template/default/assets/scss/component/_9.1.mypage.scss
  html/template/default/assets/scss/mixins/_btn.scss
  html/template/default/assets/scss/mixins/_projects.scss
  html/template/default/assets/scss/mixins/_variables.scss
  html/template/default/assets/scss/project/_11.2.header.scss
  html/template/default/assets/scss/project/_20.1.404.scss
  html/template/default/assets/scss/style.scss
Labels: bug:Low

#5515 注文中に規格を非表示に変更しても購入完了できるバグ修正
  app/config/eccube/packages/purchaseflow.yaml
  src/Eccube/Service/PurchaseFlow/Processor/ClassCategoryValidator.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/ClassCategoryValidatorTest.php
Labels: Status: ready-for-merge, bug:Middle

#5518 guzzlehttpの脆弱性に対応
  composer.json
  composer.lock
Labels: Status: ready-for-merge

#5519 Apply composer update
  composer.json
  composer.lock
  src/Eccube/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
  src/Eccube/Resource/template/default/Shopping/login.twig
  tests/Eccube/Tests/Web/AuthenticationHandlerTest.php
Labels: Status: ready-for-merge

#5528 .env.distのTRUSTED_HOSTSの記述を完全一致の形式に変更
  .env.dist
Labels: Status: ready-for-merge, improvement

#5538 税率設定の編集時にキャンセルすると編集中の値のままになるバグ修正
  src/Eccube/Resource/template/admin/Setting/Shop/tax_rule.twig
Labels: Status: ready-for-merge, bug:Low

#5524 デフォルトのblueカラーをbootstrap3にする
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/mixins/_variables.scss
Labels: Status: ready-for-merge, bug:Low

#5542 fix: upgrade chart.js from 3.8.0 to 3.8.2
  html/bundle/admin.bundle.js
  html/bundle/admin.bundle.js.LICENSE.txt
  html/bundle/admin.bundle.js.map
  package-lock.json
  package.json
Labels: Status: ready-for-merge

#5541 ラジオボタンのエラーメッセージにスタイルが当たるように修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_3.1.inputText.scss
  html/template/default/assets/scss/component/_3.2.inputMisc.scss
Labels: Status: ready-for-merge, bug:Low

#5548 管理画面ホームの売上状況の期間選択ボタンのスタイル修正
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/scss/component/_bootstrapOriginal.scss
Labels: Status: ready-for-merge, bug:Low

#5547 モーダルダイアログの終了ボタンの型を他と統一するように修正
  src/Eccube/Resource/template/admin/Content/news.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/admin/Setting/System/member.twig
Labels: Status: ready-for-merge, bug:Low

#5540 受注登録画面で商品の削除、追加を行うとエラーになる不具合を修正
  src/Eccube/Resource/template/admin/Order/edit.twig
Labels: Status: ready-for-merge, bug:Middle

#5546 お問合せフォームの郵便番号のエラーメッセージが2つ表示されるバグ修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_19.2.contact.scss
  src/Eccube/Resource/template/default/Contact/index.twig
Labels: Status: ready-for-merge, bug:Low, bugbounty2022:pr:entry

#5550 ログイン履歴画面のステータスにマウスオーバーすると、ステータスが消えるバグ修正
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/scss/component/_bootstrapOriginal.scss
Labels: bug:Low

#5537 税金計算０で割ったエラーを修正
  src/Eccube/Entity/Order.php
  tests/Eccube/Tests/Web/Admin/Order/AbstractEditControllerTestCase.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
Labels: bug:Low

#5551 出荷お知らせメールに配送方法を追加
  src/Eccube/Resource/template/default/Mail/shipping_notify.html.twig
  src/Eccube/Resource/template/default/Mail/shipping_notify.twig
Labels: Status: ready-for-merge, bug:Low

#5552 ご注文手続き画面の見出しにマージンを設ける修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_1.1.heading.scss
Labels: Status: ready-for-merge, bug:Low

#5558 注文時に支払い方法が非表示に変更された場合エラーが発生するよう修正
  app/config/eccube/packages/purchaseflow.yaml
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Service/PurchaseFlow/Processor/PaymentValidator.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/PaymentValidatorTest.php
Labels: bug:Low

#5565 Added check for existence of a folder with the same name as the uploa…
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug:Low

#5591 納品書出力画面のチェックボックスの表示位置を修正
  src/Eccube/Resource/template/admin/Order/order_pdf.twig
Labels: bug:Low

#5603 プラグイン画像のリンクにスペースが表示されないように修正
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
Labels: bug:Low

#5588 チェックボックスの位置を修正
  src/Eccube/Resource/template/install/step1.twig
  src/Eccube/Resource/template/install/step5.twig
Labels: bug:Low

#5587 インストール画面のシステムエラーに対応
  src/Eccube/Controller/Install/InstallController.php
Labels: bug:Low

#5607 商品CSV登録の一括登録ボタンのスタイルを修正
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/scss/component/_bootstrapOriginal.scss
Labels: bug:Low

#5582 インストール画面のアラートの修正
  src/Eccube/Resource/template/install/step1.twig
Labels: bug:Low

#5564 Change publish_date to include seconds.
  src/Eccube/Form/Type/Admin/NewsType.php
  src/Eccube/Resource/template/admin/Content/news.twig
Labels: bug:Low, bugbounty2022:pr:entry

#5585 svg.htmlをloadする
  src/Eccube/Resource/template/install/frame.twig
Labels: bug:Low

#5557 Remove loading fontawesome 4
  html/template/admin/assets/css/app.css
  html/template/admin/assets/css/app.css.map
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/css/app.min.css.map
  html/template/admin/assets/scss/component/_directory.scss
  html/template/admin/assets/scss/component/_form.scss
  html/template/admin/assets/scss/component/_icon.scss
  html/template/admin/assets/scss/component/_mainNavArea.scss
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/error.twig
Labels: bug:Low, bugbounty2022:pr:entry

#5614 Symfony5.4からUsernamePasswordTokenのコンストラクタの引数が変更されたので修正
  src/Eccube/Controller/EntryController.php
  tests/Eccube/Tests/Web/AbstractWebTestCase.php
Labels: Status: ready-for-merge

#5620 UsernameNotFoundExceptionがSymfony5.3から非推奨で6.0で削除されるのでUserNotFoundExceptionに変更
  src/Eccube/Security/Core/User/CustomerProvider.php
  src/Eccube/Security/Core/User/MemberProvider.php
Labels: Status: ready-for-merge

#5594 bootstrap_4を5に変更
  app/config/eccube/packages/twig.yaml
  src/Eccube/Resource/template/admin/Setting/System/log.twig
Labels: bug:Low

#5566 ファイルアップロードの失敗時にエラー内容自体を表示しないように修正
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug:Low, bugbounty2022:pr:entry

#5567 連続するスラッシュが含まれる場合はエラーとなるように変更
  src/Eccube/Form/Type/Admin/BlockType.php
  tests/Eccube/Tests/Form/Type/Admin/BlockTypeTest.php
Labels: bug:Low, bugbounty2022:pr:entry

#5626 FilePond：【styleItemPanelAspectRatio】指定追加
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: Status: ready-for-merge, bug:Low

#5630 date_secを使用する
  src/Eccube/Resource/template/admin/Content/news.twig
Labels: bug:Low

#5633 英単語のタイポを修正
  src/Eccube/Resource/locale/messages.en.yaml
Labels: Status: ready-for-merge, bug:Low

#5634 テストがローカルで動くように修正
  tests/Eccube/Tests/Web/Admin/Content/BlockControllerTest.php
  tests/Eccube/Tests/Web/Admin/Content/NewsControllerTest.php
Labels: bug:Low

#5679 テスト用Fixturesの生成でユニーク項目がユニークになるようにする
  tests/Eccube/Tests/Fixture/Generator.php
Labels: bug:Low

#5681 不要なファイルの削除
  src/Eccube/Form/Type/Admin/OrderItemForShippingRegistrationType.php
Labels: bug:Low

#5677 インストール済みプラグインの表示のずれを修正
  src/Eccube/Resource/template/admin/Store/plugin_table_official.twig
Labels: bug:Low

#5655 不要なspanタグを削除
  src/Eccube/Resource/template/admin/Setting/System/member.twig
Labels: bug:Low

#5671 出荷CSV登録のお問い合わせ番号のフォーマットチェックを追加
  src/Eccube/Controller/Admin/Order/CsvImportController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug:Low

#5661 メタタグが二重で出力されないように修正
  src/Eccube/Resource/template/default/default_frame.twig
Labels: bug:Low

#5662 スライダーのサムネイル画像にheightを追加
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_12.1.slider.scss
Labels: bug:Low

#5578 メール送信でシステムエラーになるのを回避する
  src/Eccube/Service/MailService.php
Labels: bug:Middle, bugbounty2022:pr:entry

#5666 herokuを消す
  Procfile
  README.md
  app.json
Labels: Status: ready-for-merge

#5685 ファイルのアップロード時にエラーメッセージを重複して表示しないように修正
  src/Eccube/Controller/Admin/Content/FileController.php
Labels: bug:Low

#5653 不要なスペースを削除
  src/Eccube/Repository/CustomerRepository.php
  src/Eccube/Repository/OrderRepository.php
  src/Eccube/Repository/ShippingRepository.php
Labels: Status: ready-for-merge

#5695 未使用のprivateプロパティやメソッド、インポート、ローカル変数を削除
  src/Eccube/Controller/Admin/Order/EditController.php
  src/Eccube/Controller/Admin/Order/MailController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/Admin/Setting/Shop/DeliveryController.php
  src/Eccube/Controller/Admin/Setting/System/LoginHistoryController.php
  src/Eccube/Controller/Admin/Store/OwnerStoreController.php
  src/Eccube/Controller/Admin/Store/PluginController.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Controller/NonMemberShoppingController.php
  src/Eccube/Controller/ProductController.php
  src/Eccube/Doctrine/Common/CsvDataFixtures/CsvFixture.php
  src/Eccube/Entity/AbstractEntity.php
  src/Eccube/Entity/Category.php
  src/Eccube/EventListener/ForwardOnlyListener.php
  src/Eccube/EventListener/LoginHistoryListener.php
  src/Eccube/Repository/ShippingRepository.php
  src/Eccube/Security/Voter/AuthorityVoter.php
  src/Eccube/Service/Composer/ComposerProcessService.php
  src/Eccube/Service/PluginService.php
  src/Eccube/Session/Storage/Handler/SameSiteNoneCompatSessionHandler.php
Labels: Status: needs-review

#5636 ツールチップのマウスオーバーが適用されない点を修正
  src/Eccube/Resource/template/admin/Setting/System/masterdata.twig
  src/Eccube/Resource/template/admin/Store/authentication_setting.twig
Labels: bug:Low

#5576 範囲外の日付を入力すると発生する不具合を修正しました。
  src/Eccube/Form/Type/Admin/CalendarType.php
  src/Eccube/Form/Type/Admin/CustomerType.php
  src/Eccube/Form/Type/Admin/NewsType.php
  src/Eccube/Form/Type/Admin/OrderPdfType.php
  src/Eccube/Form/Type/Admin/SearchCustomerType.php
  src/Eccube/Form/Type/Admin/SearchLoginHistoryType.php
  src/Eccube/Form/Type/Admin/SearchOrderType.php
  src/Eccube/Form/Type/Admin/SearchProductType.php
  src/Eccube/Resource/locale/validators.en.yaml
  src/Eccube/Resource/locale/validators.ja.yaml
  tests/Eccube/Tests/Form/Type/Admin/SearchOrderTypeTest.php
Labels: bug:Low

#5693 carbonのaddDay,addMonthのメソッド呼び出しを修正
  codeception/acceptance/EA07BasicinfoCest.php
  src/Eccube/Controller/Block/CalendarController.php
  tests/Eccube/Tests/Web/Block/CalendarControllerTest.php
Labels: Status: ready-for-merge

#5570 注文時に税率が変更された場合エラーが発生するよう修正
  app/config/eccube/packages/purchaseflow.yaml
  src/Eccube/Entity/Order.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Service/PurchaseFlow/Processor/TaxRateChangeValidator.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/TaxRateChangeValidatorTest.php
Labels: bug:Low, bugbounty2022:pr:entry, bugbounty2022:pr:testcode

#5643 Password入力フォームの修正
  src/Eccube/Form/Type/Admin/CustomerType.php
  src/Eccube/Form/Type/Admin/MemberType.php
  src/Eccube/Form/Type/RepeatedPasswordType.php
Labels: Status: ready-for-merge, bug:Low, bugbounty2022:pr:entry, bugbounty2022:pr:testcode, bugbounty2022:pr:recognition

#5651 性別の問題はいい機会なので対応しましょう
  src/Eccube/Resource/doctrine/import_csv/ja/mtb_sex.csv
Labels: Status: ready-for-merge, improvement

#5700 メール設定・CSV出力項目設定：ブラウザバック不具合の修正
  src/Eccube/Resource/template/admin/Setting/Shop/csv.twig
  src/Eccube/Resource/template/admin/Setting/Shop/mail.twig
Labels: Status: ready-for-merge, bug:Low, bugbounty2022:pr:entry

#5704 配送方法設定の必須マークを追加
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_edit.twig
Labels: Status: ready-for-merge, bug:Low, bugbounty2022:pr:entry

#5705 支払方法設定に必須マークを付与
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
Labels: Status: ready-for-merge, bug:Low

#5715 2FAのCOOKIE有無の条件分岐が逆だったので修正
  src/Eccube/Controller/Admin/Setting/System/TwoFactorAuthController.php
Labels: Status: ready-for-merge, bug:Low

#5733 システムログのダウンロード時に発生するエラーを修正
  src/Eccube/Controller/Admin/Setting/System/LogController.php
Labels: Status: ready-for-merge, bug:Low

#5736 マイページ、詳細の変数が間違えている
  src/Eccube/Resource/template/default/Mypage/history.twig
Labels: Status: ready-for-merge, bug:Low

#5734 お届け日の日付から時間を削除
  src/Eccube/Twig/Extension/IntlExtension.php
Labels: Status: ready-for-merge, bug:Low
