Repository EC-CUBE/ec-cube, pull requests merged in 2022-12, with the labels that each got.

#5878 管理・運用マニュアルへのリンクを追加
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/nav.twig
Labels: Status: ready-for-merge, improvement

#5858 フロント画面へのIPアクセス制限の実装
  app/config/eccube/packages/eccube.yaml
  codeception/_support/AcceptanceTester.php
  codeception/_support/Page/Admin/SystemSecurityPage.php
  codeception/_support/Page/Front/TopPage.php
  codeception/acceptance/EA08SysteminfoCest.php
  src/Eccube/Controller/Admin/Setting/System/SecurityController.php
  src/Eccube/EventListener/IpAddrListener.php
  src/Eccube/Form/Type/Admin/SecurityType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/System/security.twig
  tests/Eccube/Tests/EventListener/IpAddrListenerTest.php
  tests/Eccube/Tests/Form/Type/Admin/SecurityTypeTest.php
  tests/Eccube/Tests/Web/Admin/Setting/System/SecurityControllerTest.php
Labels: Status: ready-for-merge, affected:外部仕様, security

#5876 boolean の値をCSVダウンロードする場合、 false が空欄になってしまうのを修正
  src/Eccube/Service/CsvExportService.php
Labels: Status: ready-for-merge, bug:Low

#5880 管理画面：受注/会員一覧のページングの下部余白がなかったのを商品一覧に合わせて修正（pb-4クラス追加）
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/index.twig
Labels: Status: ready-for-merge, bug:Low

#5883 トップページへのリンクをurl関数ではなくbasePathを使った方法へ変更
  src/Eccube/Resource/template/default/error.twig
Labels: Status: ready-for-merge, bug:Low

#5881 スロットリング機能
  .github/workflows/e2e-test-throttling.yml
  app/config/eccube/bundles.php
  app/config/eccube/packages/eccube_rate_limiter.yaml
  app/config/eccube/packages/prod/eccube_rate_limiter.yaml
  app/config/eccube/packages/rate_limiter.yml
  app/config/eccube/packages/test/eccube_rate_limiter.yaml
  app/config/eccube/packages/test/rate_limiter.yml
  app/config/eccube/services.yaml
  codeception/acceptance/EF09ThrottlingCest.php
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/DependencyInjection/Compiler/AutoConfigurationTagPass.php
  src/Eccube/DependencyInjection/Configuration.php
  src/Eccube/DependencyInjection/EccubeExtension.php
  src/Eccube/EccubeBundle.php
  src/Eccube/EventListener/ExceptionListener.php
  src/Eccube/EventListener/RateLimiterListener.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/DependencyInjection/Compiler/AutoConfigurationTagPassTest.php
  tests/Eccube/Tests/DependencyInjection/ConfigurationTest.php
  tests/Eccube/Tests/DependencyInjection/EccubeExtensionTest.php
  tests/Eccube/Tests/EccubeBundleTest.php
  tests/Eccube/Tests/EventListener/RateLimiterListenerTest.php
Labels: enhancement, affected:外部仕様, security

#5890 下層ディレクトリにec-cubeを設置した場合、カート→レジに進むにてログインした場合にエラーになる #5863
  src/Eccube/Resource/template/default/Shopping/login.twig
Labels: Status: ready-for-merge, bug:Middle, affected:template
