Repository EC-CUBE/ec-cube, pull requests merged in 2022-01, with the labels that each got.

#5263 OWASP ZAP で Playwright を使用する
  .github/workflows/penetration-test.yml
  zap/selenium/ci/TypeScript/.gitignore
  zap/selenium/ci/TypeScript/README.md
  zap/selenium/ci/TypeScript/babel.config.js
  zap/selenium/ci/TypeScript/package.json
  zap/selenium/ci/TypeScript/playwright.config.ts
  zap/selenium/ci/TypeScript/test/admin/order_mail.test.ts
  zap/selenium/ci/TypeScript/test/front_guest/contact.test.ts
  zap/selenium/ci/TypeScript/test/front_login/contact.test.ts
  zap/selenium/ci/TypeScript/tsconfig.json
  zap/selenium/ci/TypeScript/utils/Progress.ts
  zap/selenium/ci/TypeScript/utils/SeleniumCapabilities.ts
  zap/selenium/ci/TypeScript/yarn.lock
Labels: experimental

#5266 複数出荷情報登録画面 お届け時間フォームラベルをadmin.order.delivery_timeに修正
  src/Eccube/Resource/template/admin/Order/shipping.twig
Labels: bug:Low

#5272 COMPOSE_FILE 環境変数を使用してコマンドを簡略化し見やすくする
  zap/selenium/ci/TypeScript/README.md
Labels: document, Status: ready-for-merge

#5271 XMLHttpRequest のフォームにCSRFトークンチェック追加
  src/Eccube/Controller/Admin/Product/ClassNameController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Controller/Admin/Setting/Shop/MailController.php
  src/Eccube/Controller/Admin/Setting/Shop/PaymentController.php
Labels: bug:Low

#5249 商品一覧やお気に入りページの商品画像の高さをなくす
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_9.1.mypage.scss
  html/template/default/assets/scss/project/_13.2.shelf.scss
Labels: Status: ready-for-merge, affected:template, improvement

#5267 jQuery のバージョンを ver 3.6.0 に上げる
  html/template/install/assets/js/vendor/jquery-3.5.1.min.js
  html/template/install/assets/js/vendor/jquery-3.6.0.min.js
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/error.twig
  src/Eccube/Resource/template/admin/login_frame.twig
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Resource/template/install/frame.twig
Labels: Status: ready-for-merge, affected:template, affected:admin_template

#5268 bootstrap のバージョンをアップデートする
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/css/tempusdominus-bootstrap-4.css
  html/template/admin/assets/css/tempusdominus-bootstrap-4.min.css
  html/template/admin/assets/js/vendor/tempusdominus-bootstrap-4.js
  html/template/admin/assets/js/vendor/tempusdominus-bootstrap-4.min.js
  html/template/install/dist/js/bootstrap.js
  html/template/install/dist/js/bootstrap.min.js
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/error.twig
  src/Eccube/Resource/template/admin/login_frame.twig
Labels: Status: ready-for-merge, affected:template, affected:admin_template

#5140 EccubeExtension::getPhpFunctions() は非推奨とする
  src/Eccube/Twig/Extension/EccubeExtension.php
Labels: enhancement, security

#5260 お問い合わせ　textareaのエラー表示修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_3.1.inputText.scss
Labels: Status: ready-for-merge, bug:Low, affected:template

#5241 change OrderPdfService methods visibility
  src/Eccube/Controller/Admin/Order/OrderController.php
  src/Eccube/Service/OrderPdfService.php
Labels: Status: ready-for-merge, improvement

#5256 カートページ　商品名称、合計金額、ボタンの横幅修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_15.1.cart.scss
Labels: affected:template

#5274 TRUSTED_HOSTSを標準で有効にするように対応
  .github/workflows/e2e-test.yml
  docker-compose.yml
  dockerbuild/docker-php-entrypoint
  src/Eccube/Command/InstallerCommand.php
  src/Eccube/Controller/Admin/Setting/System/SecurityController.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Form/Type/Admin/SecurityType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/System/security.twig
  tests/Eccube/Tests/Form/Type/Admin/SecurityTypeTest.php
  tests/Eccube/Tests/Web/Admin/Setting/System/SecurityControllerTest.php
Labels: enhancement

#5257 マイページナビ　ホバーアクション等崩れ修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_9.1.mypage.scss
Labels: affected:template

#5038 管理画面：ソート機能追加（商品一覧・受注一覧・会員一覧）
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/js/function.js
  html/template/admin/assets/scss/component/_bootstrapOriginal.scss
  src/Eccube/Controller/Admin/Order/OrderController.php
  src/Eccube/Controller/Admin/Product/ProductController.php
  src/Eccube/Form/Type/Admin/SearchCustomerType.php
  src/Eccube/Form/Type/Admin/SearchOrderType.php
  src/Eccube/Form/Type/Admin/SearchProductType.php
  src/Eccube/Repository/CustomerRepository.php
  src/Eccube/Repository/OrderRepository.php
  src/Eccube/Repository/ProductRepository.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Customer/index.twig
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Product/index.twig
  src/Eccube/Resource/template/admin/search_items.twig
Labels: enhancement, affected:plugin, affected:admin_template

#5233 管理者はメンテナンスモードを回避可能に変更
  app/config/eccube/packages/security.yaml
  app/config/eccube/services.yaml
  codeception/_support/Page/Admin/MaintenanceManagePage.php
  codeception/acceptance/EA06ContentsManagementCest.php
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/project/_11.2.header.scss
  index.php
  src/Eccube/Controller/Admin/Content/MaintenanceController.php
  src/Eccube/EventListener/MaintenanceListener.php
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Security/Http/Authentication/EccubeLogoutSuccessHandler.php
  src/Eccube/Service/SystemService.php
Labels: enhancement

#4809 ref: #4807 4.1.x用にcanonical url追加
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/default_frame.twig
  src/Eccube/Resource/template/default/meta.twig
Labels: enhancement
