Repository EC-CUBE/ec-cube, pull requests merged in 2022-09, with the labels that each got.

#5694 非推奨なTcpdfFpdiをFpdiに変更
  composer.json
  composer.lock
  src/Eccube/Service/OrderPdfService.php
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#5755 emailの長さは254文字まで
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Form/Type/Admin/CustomerType.php
  src/Eccube/Form/Type/RepeatedEmailType.php
  tests/Eccube/Tests/Form/Type/Admin/CustomerTypeTest.php
Labels: bug:Low, bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#5739 ポイントの最大長チェックの追加
  src/Eccube/Form/Type/Admin/CustomerType.php
  src/Eccube/Form/Type/Admin/OrderType.php
  tests/Eccube/Tests/Form/Type/Admin/CustomerTypeTest.php
  tests/Eccube/Tests/Form/Type/Admin/OrderTypeTest.php
Labels: bug:Low, bugbounty2022:pr:entry, bugbounty2022:pr:testcode, bugbounty2022:pr:recognition

#5621 管理者ログイン画面のID, PWの長さ制限をeccube.yamlの設定値にそろえる
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Form/Type/Admin/LoginType.php
Labels: Status: fix-me, bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#5759 在庫数未設定時のエラーが表示されない不具合の修正
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: Status: ready-for-merge, bug:Low

#5740 ref #5725 商品コードバリデートの不整合
  src/Eccube/Form/Type/Admin/ProductClassEditType.php
  src/Eccube/Form/Type/Admin/ProductClassType.php
  tests/Eccube/Tests/Form/Type/Admin/ProductClassTypeTest.php
Labels: bug:Low, bugbounty2022:pr:entry, bugbounty2022:pr:testcode, bugbounty2022:pr:recognition

#5642 インストール画面もform_themeを設定
  src/Eccube/Resource/template/install/layout.html.twig
  src/Eccube/Resource/template/install/step3.twig
  src/Eccube/Resource/template/install/step4.twig
  src/Eccube/Resource/template/install/step5.twig
Labels: bug:Low, bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#5744 注文者でのソートが注文番号になっていた点を修正
  src/Eccube/Resource/template/admin/Order/index.twig
Labels: bugbounty2022:pr:entry, bugbounty2022:pr:recognition

#5764 [4.2] インストーラでのプラグイン有効化/無効化時にキャッシュ削除が失敗する場合があるのを修正
  src/Eccube/Controller/InstallPluginController.php
Labels: bug:High

#5760 [4.2] Add check invalid filename
  src/Eccube/Controller/Admin/Content/FileController.php
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: security

#5639 デフォルトテンプレートの修正
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/component/_1.2.typo.scss
  html/template/default/assets/scss/component/_3.2.inputMisc.scss
  html/template/default/assets/scss/project/_19.2.contact.scss
  html/template/install/assets/css/dashboard.css
  src/Eccube/Resource/template/default/Mypage/history.twig
Labels: Status: ready-for-merge, bug:Low

#5767 不要なファイルがパッケージに含まれるのを修正
  package.sh
Labels: bug:Low

#5762 スピナーがボタン内に見えなくなる 不具合の修正
  html/template/admin/assets/js/function.js
Labels: bug:Low

#5746 納品書のデフォルト値の表示処理を削除
  src/Eccube/Form/Type/Admin/OrderPdfType.php
  src/Eccube/Resource/template/admin/Order/order_pdf.twig
  src/Eccube/Service/OrderPdfService.php
  tests/Eccube/Tests/Web/Admin/Order/OrderPdfControllerTest.php
Labels: Status: ready-for-merge, bug:Low, bugbounty2022:pr:entry

#5769 remember_meにsecure属性を設定
  app/config/eccube/packages/security.yaml
Labels: bug:Low

#5763 upload_max_filesize の指定が PHP8 で効いていなかったのを修正
  .htaccess
Labels: bug:Low

#5771 [4.2] Docker ホストのユーザーの UID と GID を www-data にマッピングする
  docker-compose.dev.yml
  dockerbuild/docker-php-entrypoint
Labels: Status: ready-for-merge, bug:Low

#5742 PDFの罫線の高さがそろわない不具合を修正
  src/Eccube/Service/OrderPdfService.php
Labels: bug:Low, bugbounty2022:pr:entry

#5780 [4.2]インストーラ完了画面のプラグイン有効化/無効化ボタンをトグルボタンに変更
  html/template/install/assets/css/dashboard.css
  src/Eccube/Resource/template/install/complete.twig
Labels: improvement

#5571 受注編集画面にポイント付与率を追加
  src/Eccube/Form/Type/Admin/OrderItemType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Order/edit.twig
  src/Eccube/Resource/template/admin/Order/order_item_prototype.twig
  src/Eccube/Resource/template/admin/Order/order_item_type.twig
  src/Eccube/Resource/template/admin/Order/search_product.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
  src/Eccube/Service/PointHelper.php
  src/Eccube/Service/PurchaseFlow/Processor/AddPointProcessor.php
Labels: bug:Middle, bugbounty2022:pr:entry

#5793 [4.2]受注ダミーデータ生成時にポイント付与率を設定する
  tests/Eccube/Tests/Fixture/Generator.php
Labels: improvement

#5572 ref #5529 購入完了時点のポイント付与率を保存する
  app/config/eccube/packages/purchaseflow.yaml
  src/Eccube/Service/PurchaseFlow/Processor/PointRateProcessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/PointRateProcessorTest.php
Labels: bugbounty2022:pr:entry

#5788 [4.2] 商品詳細画面で画像ファイルのドラッグ、ドロップで枠内に収まらないと画像がブラウザに表示されるくなる 不具合の修正
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: bug:Low

#5794 二要素認証の編集時に画面にエラーが表示されないくなる 不具合の修正
  src/Eccube/Resource/template/admin/Setting/System/two_factor_auth_edit.twig
Labels: bug:Low

#5778 メンバー編集時に[ログインID]が表示されない くなる 不具合の修正
  src/Eccube/Form/Type/Admin/MemberType.php
Labels: bug:Low

#5750 割引の取得にソート機能を追加
  src/Eccube/Entity/Order.php
Labels: bug:Low, bugbounty2022:pr:entry

#5775 規格分類をすべて非表示にしたときの価格の表示についてくなる 不具合の修正
  src/Eccube/Resource/template/default/Product/detail.twig
Labels: bug:Low

#5800 4.1ブランチをマージ
  codeception/_support/Page/Admin/DeliveryEditPage.php
  codeception/acceptance/EA07BasicinfoCest.php
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_edit.twig
Labels: security

#5802 bootstrap5に合わせてクローズボタンを修正
  src/Eccube/Resource/template/admin/Store/plugin_detail_modal.twig
Labels: Status: ready-for-merge, bug:Low

#5807 [4.2]クーポン利用時に「税率が変更されました」のメッセージが表示されるのを修正
  src/Eccube/Service/PurchaseFlow/Processor/TaxRateChangeValidator.php
Labels: bug:High

#5622 git actionのキャッシュの修正
  .github/workflows/unit-test.yml
Labels: improvement, bugbounty2022:pr:entry

#5624 git actionsが冗長なので少しだけ整理
  .github/actions/composer/action.yml
  .github/workflows/coverage.yml
  .github/workflows/deny-test.yml
  .github/workflows/deploy.yml
  .github/workflows/dockerbuild.yml
  .github/workflows/e2e-test.yml
  .github/workflows/phpstan.yml
  .github/workflows/plugin-test.yml
  .github/workflows/unit-test.yml
  .github/workflows/vaddy-1.yml
  .github/workflows/vaddy-2.yml
Labels: improvement, bugbounty2022:pr:entry
