Repository EC-CUBE/ec-cube, pull requests merged in 2022-04, with the labels that each got.

#5312 [OWASP ZAP] 商品CSV登録 雛形ダウンロードを追加
  .github/workflows/penetration-test.yml
  zap/selenium/ci/TypeScript/test/admin/product_csv_template.test.ts
Labels: Status: ready-for-merge

#5327 E2Eテスト追加: ポイント設定
  codeception/_support/Page/Admin/CustomerManagePage.php
  codeception/_support/Page/Admin/OrderEditPage.php
  codeception/_support/Page/Admin/ShopSettingPage.php
  codeception/_support/Page/Front/CartPage.php
  codeception/_support/Page/Front/HistoryPage.php
  codeception/_support/Page/Front/ShoppingPage.php
  codeception/acceptance/EA07BasicinfoCest.php
Labels: Status: ready-for-merge

#5316 商品CSV登録 販売制限数、通常価格の未指定の場合を追加
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: Status: ready-for-merge, improvement

#5352 E2Eテストの修正(EF0101-UC01-T02 TOPページ 新着情報)
  codeception/acceptance/EF01TopCest.php
Labels: bug:Low

#5348 商品在庫テーブルにレコードが存在しなかった場合にエラーで止まる fix
  src/Eccube/Controller/Admin/Product/CsvImportController.php
Labels: Status: ready-for-merge, bug:Low

#5349 納品書PDFで複数行になる商品明細がページをまたぐとレイアウトが崩れる #5326
  src/Eccube/Service/OrderPdfService.php
Labels: bug:Low

#5350 カテゴリ編集フォームでエラーがあっても気づかない
  src/Eccube/Resource/template/admin/Product/category.twig
Labels: bug:Low

#5355 deprecated error fix.
  index.php
Labels: Status: ready-for-merge, improvement

#5357 forタグにif条件の追加はTwig2.10で非推奨なので修正
  src/Eccube/Resource/template/admin/Setting/System/login_history.twig
  src/Eccube/Resource/template/admin/search_items.twig
  src/Eccube/Resource/template/default/Shopping/confirm.twig
Labels: Status: ready-for-merge, affected:template, improvement

#5337 [OWASP ZAP] 商品管理>カテゴリ管理 CSVダウンロードを追加
  .github/workflows/penetration-test.yml
  zap/selenium/ci/TypeScript/test/admin/product_category_export.test.ts
Labels: Status: fix-me
