Repository EC-CUBE/ec-cube, pull requests merged in 2022-02, with the labels that each got.

#5290 composer config 実行時に `--no-interaction` オプションを追加
  src/Eccube/Service/Composer/ComposerApiService.php
Labels: bug:Middle

#5291 デフォルトで利用するComposerプラグインを許可する
  composer.json
Labels: bug:Middle

#5286 カレンダーの翌月判定の誤りを修正
  codeception/acceptance/EA07BasicinfoCest.php
  src/Eccube/Controller/Block/CalendarController.php
  tests/Eccube/Tests/Web/Block/CalendarControllerTest.php
Labels: bug:Low

#5295 [4.1.2] 管理画面CSS 配送方法設定の削除ボタンが見えない件を修正
  html/template/admin/assets/css/bootstrap.css
  html/template/admin/assets/css/bootstrap.css.map
  html/template/admin/assets/css/bootstrap.min.css
  html/template/admin/assets/css/bootstrap.min.css.map
  html/template/admin/assets/scss/component/_bootstrapOriginal.scss
Labels: Status: ready-for-merge, bug:Low

#5298 ファイル管理のファイル削除時、 select_file に空のパラメータを渡せないよう修正
  src/Eccube/Controller/Admin/Content/FileController.php
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: bug:Middle

#5299 カバレッジが取得できなくなっているのを修正
  .github/workflows/coverage.yml
Labels: Status: ready-for-merge
