Repository EC-CUBE/ec-cube, pull requests merged in 2022-10, with the labels that each got.

#5826 [4.2] 出荷CSV登録で、問い合わせ番号に空白を登録するとエラーになる不具合を修正
  src/Eccube/Controller/Admin/Order/CsvImportController.php
  tests/Eccube/Tests/Web/Admin/Order/CsvImportControllerTest.php
Labels: Status: ready-for-merge, bug:Low

#5824 [4.2] お問い合わせの入力文字数を制限する
  src/Eccube/Form/Type/Front/ContactType.php
Labels: bug:Low

#5832 [4.2] ポイントがマイナスの場合、受注を更新できない くなる 不具合の修正
  src/Eccube/Service/PurchaseFlow/Processor/PointDiffProcessor.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/PointDiffProcessorTest.php
Labels: bug:Low

#5837 php8.1のdeprecatedを修正
  src/Eccube/DependencyInjection/Compiler/PluginPass.php
Labels: bug:Low

#5828 [4.1.x, 4.2.x] 値をスペースで更新してから更新をキャンセルすると、元の値が消える不具合の修正
  src/Eccube/Form/Type/Admin/CalendarType.php
  src/Eccube/Resource/template/admin/Product/category.twig
  src/Eccube/Resource/template/admin/Product/class_category.twig
  src/Eccube/Resource/template/admin/Product/class_name.twig
  src/Eccube/Resource/template/admin/Product/tag.twig
  src/Eccube/Resource/template/admin/Setting/Shop/delivery_time_prototype.twig
Labels: Status: ready-for-merge, bug:Low

#5752 検索結果が数値の場合は、カンマを表示するように修正
  src/Eccube/Resource/template/admin/search_items.twig
  src/Eccube/Twig/Extension/EccubeExtension.php
Labels: improvement, bugbounty2022:pr:entry

#5835 仮会員に登録用メールを再送した際に用いる認証URLは送信毎に再生成するように修正
  src/Eccube/Controller/Admin/Customer/CustomerController.php
  tests/Eccube/Tests/Web/Admin/Customer/CustomerControllerTest.php
Labels: security

#5843 `eccube:composer:require` コマンドに `--from` オプションを追加
  src/Eccube/Command/ComposerRequireCommand.php
  src/Eccube/Service/Composer/ComposerApiService.php
Labels: enhancement, document

#5845 大文字小文字を区別するファイルシステムで eccube:composer:remove が失敗するのを修正
  src/Eccube/Service/Composer/ComposerApiService.php
Labels: bug:Low

#5801 PHPバージョンごとに Docker イメージを作成する
  .github/workflows/dockerbuild.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement

#5848 docker containerのm1対応
  Dockerfile
Labels: bug:Low
