Repository EC-CUBE/ec-cube, pull requests merged in 2023-01, with the labels that each got.

#5900 IP制限リスト機能に存在したバグを改修
  src/Eccube/EventListener/IpAddrListener.php
  tests/Eccube/Tests/EventListener/IpAddrListenerTest.php
Labels: Status: ready-for-merge, bug:High

#5905 拡張したエンティティの項目に標準のスタイルを当てる修正
  src/Eccube/Resource/template/default/Contact/confirm.twig
  src/Eccube/Resource/template/default/Contact/index.twig
  src/Eccube/Resource/template/default/Entry/confirm.twig
  src/Eccube/Resource/template/default/Entry/index.twig
  src/Eccube/Resource/template/default/Mypage/change.twig
  src/Eccube/Resource/template/default/Mypage/delivery_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_edit.twig
  src/Eccube/Resource/template/default/Shopping/shipping_multiple_edit.twig
Labels: Status: ready-for-merge, bug:Low

#5908 管理画面：受注対応状況設定の表の余分な余白を削除（p-0クラス追加）
  src/Eccube/Resource/template/admin/Setting/Shop/order_status.twig
Labels: Status: ready-for-merge, bug:Low

#5910 定休日カレンダー設定のthが1つ足りなかった箇所を追加
  src/Eccube/Resource/template/admin/Setting/Shop/calendar.twig
Labels: Status: ready-for-merge, bug:Low

#5911 ステータス未指定の一括更新時にモーダルが表示されないように修正
  src/Eccube/Resource/template/admin/Order/confirmationModal_js.twig
Labels: Status: ready-for-merge, bug:Low

#5914 管理画面：認証キーの新規発行時、captchaキーを入力後Enterでも新規発行できるようにしたい
  src/Eccube/Resource/template/admin/Store/authentication_setting.twig
Labels: Status: ready-for-merge, improvement

#5882 画像ファイルアップロードのエラーメッセージをわかりやすく表示する
  html/bundle/admin.bundle.js
  html/bundle/admin.bundle.js.map
  html/bundle/front.bundle.js.map
  html/bundle/install.bundle.js.map
  html/template/admin/assets/js/bundle.js
  src/Eccube/Resource/template/admin/Product/product.twig
  src/Eccube/Resource/template/admin/Setting/Shop/payment_edit.twig
Labels: Status: ready-for-merge, affected:admin_template, improvement

#5867 ファイル管理で許可した拡張子以外アップロード不可に変更
  app/config/eccube/packages/eccube.yaml
  codeception/acceptance/EA06ContentsManagementCest.php
  src/Eccube/Controller/Admin/Content/FileController.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Admin/Content/FileControllerTest.php
Labels: affected:外部仕様, improvement, security

#5870 管理画面の会員の注文履歴にページネーションを追加
  codeception/acceptance/EA05CustomerCest.php
  src/Eccube/Controller/Admin/Customer/CustomerEditController.php
  src/Eccube/Resource/template/admin/Customer/edit.twig
  src/Eccube/Resource/template/admin/pager.twig
  tests/Eccube/Tests/Web/Admin/Customer/CustomerEditControllerTest.php
Labels: Status: ready-for-merge, affected:admin_template, improvement

#5853 [4.2] 商品規格の初期化時は物理削除する
  src/Eccube/Controller/Admin/Product/ProductClassController.php
  tests/Eccube/Tests/Web/Admin/Product/ProductClassControllerTest.php
Labels: bug:Middle

#5875 商品CSVダウンロード/アップロードに「商品規格表示フラグ」を追加
  app/DoctrineMigrations/Version20230116061053.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_csv.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  tests/Eccube/Tests/Web/Admin/Product/CsvImportControllerTest.php
Labels: bug:Low

#5916 規格の物理削除に伴うE2Eテストの修正
  codeception/acceptance/EA03ProductCest.php
Labels: bug:Low
