Repository EC-CUBE/ec-cube, pull requests merged in 2023-06, with the labels that each got.

#5774 商品登録画面のフリーエリアにて発生するシステムエラーの修正
  src/Eccube/Form/Type/Admin/DeliveryType.php
  src/Eccube/Form/Type/Admin/ProductType.php
Labels: bug:Low

#5343 管理画面URLを「cart」にした場合、カート画面への遷移時に管理画面が表示される
  src/Eccube/Form/Type/Admin/SecurityType.php
  tests/Eccube/Tests/Form/Type/Admin/SecurityTypeTest.php
Labels: bug:Low

#5989 feat:会員による重要操作時のメール通知機能
  app/DoctrineMigrations/Version20230515023836.php
  codeception/acceptance/EF03OrderCest.php
  src/Eccube/Command/LoadDataFixturesEccubeCommand.php
  src/Eccube/Controller/Install/InstallController.php
  src/Eccube/Controller/Mypage/ChangeController.php
  src/Eccube/Controller/Mypage/DeliveryController.php
  src/Eccube/Controller/ShippingMultipleController.php
  src/Eccube/Controller/ShoppingController.php
  src/Eccube/Entity/BaseInfo.php
  src/Eccube/Form/Type/Admin/ShopMasterType.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_base_info.csv
  src/Eccube/Resource/doctrine/import_csv/en/dtb_mail_template.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_base_info.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_mail_template.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
  src/Eccube/Resource/template/default/Mail/customer_change_notify.html.twig
  src/Eccube/Resource/template/default/Mail/customer_change_notify.twig
  src/Eccube/Service/MailService.php
  tests/Eccube/Tests/Service/MailServiceTest.php
  tests/Eccube/Tests/Web/Admin/Setting/Shop/PaymentControllerTest.php
Labels: security

#6007 ubuntuの更新
  .github/workflows/penetration-test.yml
  .github/workflows/vaddy-1.yml
  .github/workflows/vaddy-2.yml
Labels: Status: ready-for-merge, bug:Low

#5979 会員情報変更後のメッセージ変更
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug, Status: ready-for-merge, bug:Low
