Repository EC-CUBE/ec-cube, pull requests merged in 2023-03, with the labels that each got.

#5952 GitHub Actions の dockerbuild で push する際に PHP7.4 のイメージを使用していたのを修正
  .github/workflows/dockerbuild.yml
Labels: Status: ready-for-merge, bug:Low

#5964 fix:商品登録>販売種別のエラーを表示する修正
  src/Eccube/Resource/template/admin/Product/product.twig
Labels: Status: ready-for-merge, bug:Low

#5925 管理画面>セキュリティ管理　「必須」アイコンの追加
  src/Eccube/Resource/template/admin/Setting/System/security.twig
Labels: bug:Low

#5921 管理画面内の日付絞り込み時、１度目だけ 今日の日付+T00:00 が設定される
  html/template/admin/assets/js/function.js
Labels: improvement
