Repository EC-CUBE/ec-cube, pull requests merged in 2023-05, with the labels that each got.

#5983 dockerbuildのubuntuバージョン更新
  .github/workflows/dockerbuild.yml
Labels: bug, bug:Low

#5825 [4.2] 範囲外の日付を入力するとシステムエラーが発生する不具合の修正
  src/Eccube/Form/Type/Admin/ShippingType.php
Labels: bug:Low

#5969 fontawesomeにintegrity追加
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/error.twig
Labels: Status: fix-me, bug:Low
