Repository EC-CUBE/ec-cube, pull requests merged in 2024-02, with the labels that each got.

#5974 受注テーブルのtaxに税率ごとの消費税額の合算を設定する
  src/Eccube/Entity/Order.php
  src/Eccube/Service/PurchaseFlow/PurchaseFlow.php
  tests/Eccube/Tests/Fixture/Generator.php
  tests/Eccube/Tests/Service/PurchaseFlow/ItemCollectionTest.php
  tests/Eccube/Tests/Service/PurchaseFlow/Processor/PaymentTotalNegativeValidatorTest.php
  tests/Eccube/Tests/Web/Admin/Order/EditControllerTest.php
Labels: Status: needs-review

#5951 feat:管理画面>商品一覧画面の「登録日」「更新日」検索へのバリデーション
  src/Eccube/Form/Type/Admin/SearchCustomerType.php
  src/Eccube/Form/Type/Admin/SearchOrderType.php
  src/Eccube/Form/Type/Admin/SearchProductType.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
Labels: bug, bug:Low

#5971 削除モーダルのダブルクリックをpointer-event:none で回避
  html/template/admin/assets/js/function.js
Labels: bug:Low

#6039 feat:デバッグモード有効時に通知する機能
  html/template/default/assets/css/style.css
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/notice_debug_mode.twig
  src/Eccube/Resource/template/default/default_frame.twig
Labels: improvement
