Repository EC-CUBE/ec-cube, pull requests merged in 2024-04, with the labels that each got.

#6110 バリデーションエラー発生後にログアウトされる件の修正
  src/Eccube/Controller/Mypage/ChangeController.php
Labels: bug, bug:Low

#4920 新着商品ブロックにて、商品を動的に表示する
  app/DoctrineMigrations/Version20240312170000.php
  app/config/eccube/packages/eccube.yaml
  src/Eccube/Controller/Block/AutoNewItemController.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_block.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_block.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/default/Block/auto_new_item.twig
  src/Eccube/Resource/template/default/Block/new_item.twig
  tests/Eccube/Tests/Web/Block/NewItemTest.php
Labels: enhancement, Status: ready-for-merge, affected:template

#6117 税率設定時に商品別税率を考慮していないのを修正
  src/Eccube/Form/Type/Admin/TaxRuleType.php
Labels: bug, bug:Low

#6128 HEADER_X_FORWARDED_ALLのエラーを修正
  index.php
Labels: bug, bug:High

#4912 Googleアナリティクス機能を追加
  app/DoctrineMigrations/Version20210216120000.php
  src/Eccube/Entity/BaseInfo.php
  src/Eccube/Form/Type/Admin/ShopMasterType.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_block.csv
  src/Eccube/Resource/doctrine/import_csv/en/dtb_block_position.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_block.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_block_position.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Setting/Shop/shop_master.twig
  src/Eccube/Resource/template/default/Block/google_analytics.twig
  tests/Eccube/Tests/Web/TopControllerTest.php
Labels: enhancement, affected:template

#6133 Bootstrap のバージョンアップに伴うデザイン修正
  html/template/admin/assets/css/app.css.map
  html/template/admin/assets/css/app.min.css
  html/template/admin/assets/css/app.min.css.map
  html/template/default/assets/css/style.css
  html/template/default/assets/css/style.css.map
  html/template/default/assets/css/style.min.css
  html/template/default/assets/css/style.min.css.map
  html/template/default/assets/scss/mixins/_btn.scss
Labels: bug, bug:Low

#5342 管理画面からphpinfoの情報を削除
  .env.dist
  app/config/eccube/packages/eccube.yaml
  codeception/acceptance/EA08SysteminfoCest.php
  docker-compose.yml
  src/Eccube/Controller/Admin/Setting/System/SystemController.php
  src/Eccube/Resource/template/admin/Setting/System/system.twig
Labels: Status: discussion, security

#5043 規格・規格分類：「CSV登録」作成, 「CSVダウンロード・CSV出力項目設定」追加
  app/DoctrineMigrations/Version20220603074035.php
  app/config/eccube/packages/eccube_nav.yaml
  codeception/_data/class_category.csv
  codeception/_data/class_name.csv
  codeception/_support/Page/Admin/ClassCategoryCsvUploadPage.php
  codeception/_support/Page/Admin/ClassCategoryManagePage.php
  codeception/_support/Page/Admin/ClassNameCsvUploadPage.php
  codeception/_support/Page/Admin/ClassNameManagePage.php
  codeception/acceptance/EA03ProductCest.php
  src/Eccube/Controller/Admin/Product/ClassCategoryController.php
  src/Eccube/Controller/Admin/Product/ClassNameController.php
  src/Eccube/Controller/Admin/Product/CsvImportController.php
  src/Eccube/Entity/Master/CsvType.php
  src/Eccube/Event/EccubeEvents.php
  src/Eccube/Resource/doctrine/import_csv/en/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/en/mtb_csv_type.csv
  src/Eccube/Resource/doctrine/import_csv/ja/dtb_csv.csv
  src/Eccube/Resource/doctrine/import_csv/ja/mtb_csv_type.csv
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/Product/class_category.twig
  src/Eccube/Resource/template/admin/Product/class_name.twig
  src/Eccube/Resource/template/admin/Product/csv_class_category.twig
  src/Eccube/Resource/template/admin/Product/csv_class_name.twig
Labels: enhancement

#6121 package-apiのエンドポイントを4.3用に変更
  app/config/eccube/packages/eccube.yaml
Labels: Status: ready-for-merge

#5147 PurchaseFlowのProcessorやValidatorにpriorityを設定できるようにする
  app/config/eccube/packages/purchaseflow.yaml
  app/config/eccube/services_test.yaml
  src/Eccube/DependencyInjection/Compiler/PurchaseFlowPass.php
  src/Eccube/Service/PurchaseFlow/Processor/PaymentValidator.php
  src/Eccube/Service/PurchaseFlow/Processor/TaxProcessor.php
  src/Eccube/Service/PurchaseFlow/PurchaseFlow.php
Labels: enhancement, Status: discussion

#6152 規格管理のCSVダウンロードが動作しない不具合を修正
  codeception/_support/Page/Admin/ClassCategoryManagePage.php
  codeception/_support/Page/Admin/ClassNameManagePage.php
  codeception/acceptance/EA03ProductCest.php
  src/Eccube/Controller/Admin/Product/ClassCategoryController.php
  src/Eccube/Controller/Admin/Product/ClassNameController.php
Labels: bug, bug:High

#6129 プラグインジェネレーターのConfigRepositoryのテンプレートを修正
  src/Eccube/Command/PluginGenerateCommand.php
Labels: bug, bug:Low
