Repository EC-CUBE/ec-cube, pull requests merged in 2024-01, with the labels that each got.

#6075 nodejs は sass と JavaScript ライブラリのビルドでしか使用しないため分離する
  Dockerfile
  README.md
  docker-compose.nodejs.yml
  html/bundle/03371bf1d5cbb1eab58e3a0130d1e9c2.js
  html/bundle/0794fa2b9c882c72fa7d586069b61055.js
  html/bundle/07f148ff205173f8832033bc8858892c.js
  html/bundle/0b923a43967ff893ec63b92dc4f19017.js
  html/bundle/11dc77ef2ea3a04834945a52f7de2072.js
  html/bundle/5a67fdd5293af0a35defd2574c05cd04.js
  html/bundle/63b15fb6fc8f897b22a4bf72b7e8452a.js
  html/bundle/7f407a1006eb830d6f0aaad96c133d26.js
  html/bundle/80a171b7595d1161735e23dec8efddd6.js
  html/bundle/8685c29b95a8295b28d826dd1c84a00b.js
  html/bundle/964646d64dd3196a9c27fe302511414a.js
  html/bundle/aaddd877950d1e3bf1b3ef0fc0ff596e.js
  html/bundle/admin.bundle.js
  html/bundle/admin.bundle.js.map
  html/bundle/b25188cf2652d63136d5e54c38abf84e.js
  html/bundle/b7b7be8216519adf62d75f123f9c6423.js
  html/bundle/bfe3cc7724e8bf4a4b0a281aeb44de98.js
  html/bundle/c32ec7d45ccd947b98fe458a8ca1405b.js
  html/bundle/c7c768809bd878e5b62da5b21575c1a8.js
  html/bundle/cf90a39d245bf7e6c1b41c7a9a28f0a1.js
  html/bundle/d2fe7592ff2fdda099b2b6355abe8c06.js
  html/bundle/d348e85dc2ed1ebfe2efcb918cb4a10f.js
  html/bundle/dbd05051a3ecf6b10e2f7b8904153f2d.js
  html/bundle/f0548260c0ac6b0e7cdb8909df1a5333.js
  html/bundle/f4b5e6253813413316fa56c85d891303.js
  html/bundle/front.bundle.js
  html/bundle/front.bundle.js.map
  html/bundle/install.bundle.js
  html/bundle/install.bundle.js.map
  package-lock.json
Labels: improvement

#6071 受注管理 >受注一覧>出荷済にするボタンでチェックボックスでしかチェック出来ない #6053　の対応
  src/Eccube/Resource/template/admin/Order/index.twig
  src/Eccube/Resource/template/admin/Order/shipping.twig
Labels: bug, bug:Low

#5995 isMaintenance変数が未定義の場合の処理を行います。
  src/Eccube/Resource/template/default/default_frame.twig
Labels: bug:Low

#6066 fix:必須バッチの追加と周りの修正
  src/Eccube/Resource/template/admin/Content/news_edit.twig
  src/Eccube/Resource/template/admin/Product/class_category.twig
  src/Eccube/Resource/template/admin/Product/class_name.twig
  src/Eccube/Resource/template/admin/Product/product_class.twig
  src/Eccube/Resource/template/admin/change_password.twig
Labels: bug, bug:Low

#6031 fix:インストール時のDBパスワード入力フォームからpurifyを外す
  src/Eccube/Form/Type/Install/Step4Type.php
Labels: bug, bug:Low

#6026 feat:管理画面へメンテナンスモードを通知する
  src/Eccube/EventListener/TwigInitializeListener.php
  src/Eccube/Resource/locale/messages.en.yaml
  src/Eccube/Resource/locale/messages.ja.yaml
  src/Eccube/Resource/template/admin/default_frame.twig
  src/Eccube/Resource/template/admin/info.twig
Labels: improvement
